import type { EventItem } from "./types";

export const EXPANDED_1850_1949 = [
  // 1850s
  {
    id: "taiping-rebellion-begins",
    title: "The Taiping Rebellion begins",
    year: 1850,
    category: "world",
    emoji: "🏯",
    color: "coral",
    fact: "Its leader claimed to be Jesus's younger brother, then built a rival state that shook Qing China for 14 years.",
    bonusFacts: [
      "The Taiping made Nanjing their capital and renamed it Tianjing, meaning Heavenly Capital.",
      "The conflict became one of history's deadliest civil wars, with estimates running into tens of millions.",
    ],
  },
  {
    id: "channel-telegraph-cable",
    title: "A telegraph cable crosses the Channel",
    year: 1850,
    category: "tech",
    emoji: "🌊",
    color: "sky",
    fact: "The first cable between England and France carried a message, then failed almost immediately after a fisherman snagged it.",
    bonusFacts: ["A tougher replacement opened in 1851 and made cross-Channel news nearly instantaneous."],
  },
  {
    id: "singer-sewing-patent",
    title: "Singer patents his sewing machine",
    year: 1851,
    category: "tech",
    emoji: "🧵",
    color: "sky",
    fact: "Isaac Singer improved existing machines with a straight needle, presser foot and foot-powered treadle.",
    bonusFacts: ["Singer's company helped popularize installment buying, letting households pay for machines over time."],
  },
  {
    id: "moby-dick-published",
    title: "Moby-Dick is published",
    year: 1851,
    category: "culture",
    emoji: "🐋",
    color: "lilac",
    fact: "Melville's whale-sized novel was a commercial disappointment during his lifetime before becoming a classic.",
    bonusFacts: ["The British edition appeared first under the title The Whale and lacked the epilogue explaining Ishmael's survival."],
  },
  {
    id: "foucault-pendulum",
    title: "Foucault's pendulum shows Earth turning",
    year: 1851,
    category: "discovery",
    emoji: "🔮",
    color: "mint",
    fact: "A huge swinging pendulum in Paris made Earth's rotation visible without looking at the sky.",
    bonusFacts: ["The public Pantheon demonstration used a 28-kilogram bob hanging from a wire about 67 meters long."],
  },
  {
    id: "international-chess-tournament",
    title: "The first international chess tournament",
    year: 1851,
    category: "culture",
    emoji: "♟️",
    color: "lilac",
    fact: "Sixteen leading players gathered in London, where the little-known Adolf Anderssen won the knockout tournament.",
    bonusFacts: ["Anderssen also played the dazzling friendly later nicknamed the Immortal Game during the event."],
  },
  {
    id: "giffard-powered-airship",
    title: "The first powered airship takes off",
    year: 1852,
    category: "tech",
    emoji: "🎈",
    color: "sky",
    fact: "Henri Giffard flew a steam-driven, cigar-shaped balloon about 27 kilometers from Paris.",
    bonusFacts: ["The engine produced only about three horsepower, but its propeller let the craft turn and travel under power."],
  },
  {
    id: "uncle-toms-cabin-book",
    title: "Uncle Tom's Cabin becomes a book",
    year: 1852,
    category: "culture",
    emoji: "📖",
    color: "lilac",
    fact: "Harriet Beecher Stowe's antislavery novel became a publishing phenomenon after first appearing in serial form.",
    bonusFacts: ["It sold roughly 300,000 copies in the United States in its first year, extraordinary for the period."],
  },
  {
    id: "india-first-passenger-railway",
    title: "India's first passenger railway opens",
    year: 1853,
    category: "world",
    emoji: "🚂",
    color: "coral",
    fact: "Three locomotives hauled 14 carriages from Bombay to Thane on a 34-kilometer inaugural journey.",
    bonusFacts: ["The train carried about 400 invited passengers and was greeted with a 21-gun salute."],
  },
  {
    id: "levi-strauss-business",
    title: "Levi Strauss opens his dry-goods business",
    year: 1853,
    category: "culture",
    emoji: "👖",
    color: "lilac",
    fact: "Strauss arrived in gold-rush San Francisco selling fabric and supplies; blue jeans would come two decades later.",
    bonusFacts: ["The famous riveted-trouser patent was shared with tailor Jacob Davis in 1873."],
  },
  {
    id: "brazil-first-railway",
    title: "Brazil's first railway opens",
    year: 1854,
    category: "world",
    emoji: "🚂",
    color: "coral",
    fact: "The short Mauá Railway connected a port on Guanabara Bay with the road toward Brazil's coffee-growing interior.",
  },
  {
    id: "treaty-of-kanagawa",
    title: "Japan signs the Treaty of Kanagawa",
    year: 1854,
    category: "world",
    emoji: "🗾",
    color: "coral",
    fact: "The agreement opened two Japanese ports to American ships after more than two centuries of tightly restricted foreign contact.",
  },
  {
    id: "john-snow-cholera-map",
    title: "John Snow maps a cholera outbreak",
    year: 1854,
    category: "discovery",
    emoji: "🗺️",
    color: "mint",
    fact: "Plotting deaths around London's Broad Street pump helped show that cholera traveled in contaminated water, not bad air.",
  },
  {
    id: "otis-elevator-demonstration",
    title: "Otis stages his safety-elevator stunt",
    year: 1854,
    category: "tech",
    emoji: "🛗",
    color: "sky",
    fact: "Elisha Otis stood on a raised platform while its rope was cut; his brake caught it instead of letting it crash.",
  },
  {
    id: "bessemer-process-announced",
    title: "Bessemer announces cheap steelmaking",
    year: 1855,
    category: "tech",
    emoji: "🏭",
    color: "sky",
    fact: "Blowing air through molten iron burned away impurities and eventually made steel far faster and cheaper to produce.",
  },
  {
    id: "neanderthal-fossil-found",
    title: "Neanderthal bones are found",
    year: 1856,
    category: "discovery",
    emoji: "🦴",
    color: "mint",
    fact: "Quarry workers in Germany's Neander Valley uncovered fossils later recognized as belonging to another kind of human.",
  },
  {
    id: "mauveine-discovered",
    title: "The first synthetic dye is discovered",
    year: 1856,
    category: "discovery",
    emoji: "🟣",
    color: "mint",
    fact: "Eighteen-year-old William Perkin was trying to make quinine when he accidentally created the vivid purple dye mauveine.",
  },
  {
    id: "first-passenger-elevator",
    title: "The first passenger elevator opens",
    year: 1857,
    category: "tech",
    emoji: "🏢",
    color: "sky",
    fact: "A steam-powered Otis lift began carrying shoppers between floors of New York's E.V. Haughwout department store.",
  },
  {
    id: "phonautograph-patented",
    title: "Sound is recorded for the first time",
    year: 1857,
    category: "tech",
    emoji: "〰️",
    color: "sky",
    fact: "The phonautograph traced sound waves onto soot-blackened paper, though its inventor never intended to play them back.",
  },
  {
    id: "indian-rebellion-begins",
    title: "The Indian Rebellion begins",
    year: 1857,
    category: "world",
    emoji: "🇮🇳",
    color: "coral",
    fact: "An uprising that began among East India Company soldiers spread widely and led Britain to take direct control of India.",
  },
  {
    id: "eureka-stockade",
    title: "Miners make a stand at Eureka",
    year: 1854,
    category: "world",
    emoji: "⛏️",
    color: "coral",
    fact: "Gold miners in colonial Australia rebelled against costly licenses; their brief defeat helped drive democratic reforms.",
  },
  {
    id: "first-atlantic-telegraph-cable",
    title: "The Atlantic cable sends its first messages",
    year: 1858,
    category: "tech",
    emoji: "⚡",
    color: "sky",
    fact: "Queen Victoria and President Buchanan exchanged greetings across the ocean, but the fragile cable died within weeks.",
  },
  {
    id: "darwin-wallace-evolution-paper",
    title: "Darwin and Wallace unveil natural selection",
    year: 1858,
    category: "discovery",
    emoji: "🦋",
    color: "mint",
    fact: "Their ideas were presented together in London while neither scientist was in the room.",
  },
  {
    id: "carrington-solar-storm",
    title: "The Carrington solar storm strikes Earth",
    year: 1859,
    category: "discovery",
    emoji: "🌞",
    color: "mint",
    fact: "Auroras glowed near the tropics and telegraph equipment sparked, sometimes sending messages with batteries disconnected.",
  },
  {
    id: "big-ben-clock-starts",
    title: "Big Ben's clock starts ticking",
    year: 1859,
    category: "culture",
    emoji: "🕰️",
    color: "lilac",
    fact: "The Westminster clock began keeping time in May; its enormous bell first rang in July and cracked in September.",
  },

  // 1860s
  {
    id: "pony-express-begins",
    title: "The Pony Express begins",
    year: 1860,
    category: "culture",
    emoji: "🐎",
    color: "lilac",
    fact: "Relay riders carried mail across the American West in about ten days, but the service lasted only 18 months.",
    bonusFacts: ["A completed transcontinental telegraph made the celebrated horse relay obsolete almost overnight."],
  },
  {
    id: "expedition-of-the-thousand",
    title: "Garibaldi's Thousand sail for Sicily",
    year: 1860,
    category: "world",
    emoji: "🔴",
    color: "coral",
    fact: "A small volunteer army in red shirts toppled the Kingdom of the Two Sicilies and accelerated Italian unification.",
    bonusFacts: ["The force grew dramatically as local volunteers joined during the campaign."],
  },
  {
    id: "russian-serfs-emancipated",
    title: "Russia emancipates its serfs",
    year: 1861,
    category: "world",
    emoji: "⛓️‍💥",
    color: "coral",
    fact: "Alexander II's reform freed more than 20 million privately owned serfs, although land debts kept many constrained.",
    bonusFacts: ["It was the largest single act of emancipation in history by number of people affected at the time."],
  },
  {
    id: "kingdom-of-italy-proclaimed",
    title: "The Kingdom of Italy is proclaimed",
    year: 1861,
    category: "world",
    emoji: "🇮🇹",
    color: "coral",
    fact: "Victor Emmanuel II became king of a newly unified state that still did not include Venice or Rome.",
    bonusFacts: ["Rome joined in 1870 and became the capital the following year."],
  },
  {
    id: "first-color-photograph",
    title: "The first color photograph is demonstrated",
    year: 1861,
    category: "tech",
    emoji: "🎞️",
    color: "sky",
    fact: "Three filtered photographs of a tartan ribbon were projected together to demonstrate additive color mixing.",
    bonusFacts: ["The experiment was directed by physicist James Clerk Maxwell and photographed by Thomas Sutton."],
  },
  {
    id: "american-civil-war-begins",
    title: "The American Civil War begins",
    year: 1861,
    category: "world",
    emoji: "🇺🇸",
    color: "coral",
    fact: "Confederate guns fired on Fort Sumter after 11 slaveholding states attempted to leave the United States.",
    bonusFacts: ["The war ultimately preserved the Union and destroyed legal slavery in the country."],
  },
  {
    id: "les-miserables-published",
    title: "Les Misérables is published",
    year: 1862,
    category: "culture",
    emoji: "🥖",
    color: "lilac",
    fact: "Victor Hugo's enormous novel turned an ex-convict, a relentless inspector and Parisian rebels into global icons.",
    bonusFacts: ["Booksellers reportedly queued overnight for later volumes after the first part became an immediate sensation."],
  },
  {
    id: "parkesine-plastic-unveiled",
    title: "The first manufactured plastic is unveiled",
    year: 1862,
    category: "tech",
    emoji: "🧪",
    color: "sky",
    fact: "Alexander Parkes displayed mouldable Parkesine at London's International Exhibition decades before plastic became ordinary.",
    bonusFacts: ["Made from cellulose, it could imitate horn, tortoiseshell and ivory."],
  },
  {
    id: "football-association-rules",
    title: "Association football gets its rules",
    year: 1863,
    category: "culture",
    emoji: "⚽",
    color: "lilac",
    fact: "London clubs formed the Football Association and separated their kicking game from rugby-style carrying and hacking.",
    bonusFacts: ["Early FA rules had no crossbar, penalty kicks or goalkeepers as a special protected role."],
  },
  {
    id: "red-cross-committee-founded",
    title: "The Red Cross committee is founded",
    year: 1863,
    category: "world",
    emoji: "➕",
    color: "coral",
    fact: "Five citizens in Geneva created the committee that became the International Committee of the Red Cross.",
    bonusFacts: ["Its emblem reversed Switzerland's flag colors: a red cross on white."],
  },
  {
    id: "first-geneva-convention",
    title: "The first Geneva Convention is signed",
    year: 1864,
    category: "world",
    emoji: "📜",
    color: "coral",
    fact: "Twelve states agreed that wounded soldiers and the people treating them should be protected in war.",
  },
  {
    id: "maxwell-electromagnetic-theory",
    title: "Maxwell links light and electromagnetism",
    year: 1864,
    category: "discovery",
    emoji: "🌈",
    color: "mint",
    fact: "His equations showed that electric and magnetic fields travel as waves—and that light is one of them.",
  },
  {
    id: "mendel-pea-lectures",
    title: "Mendel presents his pea experiments",
    year: 1865,
    category: "discovery",
    emoji: "🫛",
    color: "mint",
    fact: "A monk described predictable inheritance patterns to a Brno science society, but the work was largely ignored for decades.",
  },
  {
    id: "matterhorn-first-ascent",
    title: "Climbers first reach the Matterhorn summit",
    year: 1865,
    category: "culture",
    emoji: "🏔️",
    color: "lilac",
    fact: "Edward Whymper's seven-person party reached the top, but four climbers died when a rope broke during the descent.",
  },
  {
    id: "permanent-atlantic-cable",
    title: "A lasting Atlantic telegraph cable opens",
    year: 1866,
    category: "tech",
    emoji: "🌐",
    color: "sky",
    fact: "The Great Eastern laid a durable link that turned transatlantic communication from weeks into minutes.",
  },
  {
    id: "dynamite-patented",
    title: "Alfred Nobel patents dynamite",
    year: 1867,
    category: "tech",
    emoji: "🧨",
    color: "sky",
    fact: "Mixing volatile nitroglycerin with porous earth made the explosive much safer to handle and transport.",
  },
  {
    id: "das-kapital-volume-one",
    title: "The first volume of Das Kapital appears",
    year: 1867,
    category: "culture",
    emoji: "📕",
    color: "lilac",
    fact: "Karl Marx published only the first volume himself; Friedrich Engels edited later volumes after Marx's death.",
  },
  {
    id: "lister-antiseptic-surgery",
    title: "Lister publishes antiseptic surgery",
    year: 1867,
    category: "discovery",
    emoji: "🧼",
    color: "mint",
    fact: "Joseph Lister used carbolic acid to clean wounds and instruments, sharply reducing deadly surgical infections.",
  },
  {
    id: "meiji-restoration",
    title: "The Meiji Restoration transforms Japan",
    year: 1868,
    category: "world",
    emoji: "🌸",
    color: "coral",
    fact: "Imperial rule was formally restored as Japan began rapid political, military and industrial modernization.",
  },
  {
    id: "first-traffic-light",
    title: "The first traffic light is installed",
    year: 1868,
    category: "tech",
    emoji: "🚦",
    color: "sky",
    fact: "A gas-lit semaphore outside Britain's Parliament lasted only weeks before exploding and injuring its operator.",
  },
  {
    id: "helium-found-in-sun",
    title: "Helium is detected in the Sun",
    year: 1868,
    category: "discovery",
    emoji: "☀️",
    color: "mint",
    fact: "A mysterious yellow spectral line revealed an element in sunlight nearly three decades before it was isolated on Earth.",
  },
  {
    id: "suez-canal-opens",
    title: "The Suez Canal opens",
    year: 1869,
    category: "world",
    emoji: "🚢",
    color: "coral",
    fact: "The new waterway connected the Mediterranean and Red seas, letting ships avoid sailing around Africa.",
  },
  {
    id: "nature-first-issue",
    title: "Nature publishes its first issue",
    year: 1869,
    category: "culture",
    emoji: "🔬",
    color: "lilac",
    fact: "The weekly science journal launched with a mission to connect researchers' discoveries with the wider public.",
  },
  {
    id: "us-transcontinental-railroad",
    title: "The U.S. transcontinental railroad connects",
    year: 1869,
    category: "tech",
    emoji: "🛤️",
    color: "sky",
    fact: "A ceremonial golden spike joined eastern and western rail networks at Promontory Summit, Utah.",
  },
  {
    id: "qwerty-typewriter-patent",
    title: "The early modern typewriter is patented",
    year: 1868,
    category: "tech",
    emoji: "⌨️",
    color: "sky",
    fact: "Christopher Sholes, Carlos Glidden and Samuel Soulé patented a machine that evolved into the first commercially successful typewriter.",
  },

  // 1870s
  {
    id: "japan-first-railway",
    title: "Japan's first railway opens",
    year: 1872,
    category: "world",
    emoji: "🚂",
    color: "coral",
    fact: "A steam train linked Shimbashi in Tokyo with Yokohama, turning a day-long road journey into less than an hour.",
    bonusFacts: ["Emperor Meiji rode the inaugural train, a powerful symbol of Japan's rapid modernization."],
  },
  {
    id: "german-empire-proclaimed",
    title: "The German Empire is proclaimed",
    year: 1871,
    category: "world",
    emoji: "🏰",
    color: "coral",
    fact: "German princes declared the Prussian king emperor inside Versailles while France and Prussia were still at war.",
    bonusFacts: ["The ceremony took place in the Hall of Mirrors, a setting France would pointedly reuse in 1919."],
  },
  {
    id: "paris-commune",
    title: "The Paris Commune takes power",
    year: 1871,
    category: "world",
    emoji: "🚩",
    color: "coral",
    fact: "A radical elected government controlled Paris for just over two months before being violently suppressed.",
    bonusFacts: ["The Commune introduced measures including worker-run abandoned workshops and separation of church and state."],
  },
  {
    id: "first-rugby-international",
    title: "The first rugby international is played",
    year: 1871,
    category: "culture",
    emoji: "🏉",
    color: "lilac",
    fact: "Scotland beat England in Edinburgh with 20 players on each side and scoring rules unlike today's game.",
    bonusFacts: ["The match was proposed in a public challenge printed by Scottish captains in a London newspaper."],
  },
  {
    id: "descent-of-man-published",
    title: "Darwin publishes The Descent of Man",
    year: 1871,
    category: "discovery",
    emoji: "🦚",
    color: "mint",
    fact: "Darwin directly applied evolution to humans and gave sexual selection a starring role—peacock tails included.",
    bonusFacts: ["The book contains one of Darwin's earliest printed uses of the word evolution."],
  },
  {
    id: "yellowstone-national-park",
    title: "Yellowstone becomes a national park",
    year: 1872,
    category: "world",
    emoji: "♨️",
    color: "coral",
    fact: "The world's first widely recognized national park protected geysers and wildlife on lands long used by Indigenous peoples.",
    bonusFacts: ["With no park service yet, the U.S. Army later managed Yellowstone for more than 30 years."],
  },
  {
    id: "first-fa-cup-final",
    title: "The first FA Cup final is played",
    year: 1872,
    category: "culture",
    emoji: "🏆",
    color: "lilac",
    fact: "Wanderers beat Royal Engineers 1–0 before about 2,000 spectators at London's Kennington Oval.",
    bonusFacts: ["The Oval was primarily a cricket ground and hosted the match for all but one of the first 22 finals."],
  },
  {
    id: "around-world-serialization",
    title: "Around the World in Eighty Days begins",
    year: 1872,
    category: "culture",
    emoji: "🌍",
    color: "lilac",
    fact: "Jules Verne's race against the clock first appeared as a newspaper serial, with readers following dates in real time.",
    bonusFacts: ["The story's famous balloon trip appears in many adaptations—but not in Verne's novel."],
  },
  {
    id: "challenger-expedition",
    title: "The Challenger ocean expedition departs",
    year: 1872,
    category: "discovery",
    emoji: "🌊",
    color: "mint",
    fact: "A converted warship spent nearly four years measuring the deep sea and discovering thousands of marine species.",
    bonusFacts: ["Its crew took the first systematic soundings of the trench now known to contain Challenger Deep."],
  },
  {
    id: "blue-jeans-patent",
    title: "Blue jeans receive their rivet patent",
    year: 1873,
    category: "tech",
    emoji: "👖",
    color: "sky",
    fact: "Tailor Jacob Davis and merchant Levi Strauss patented metal rivets that stopped work trousers tearing at stress points.",
    bonusFacts: ["The original patent described waist overalls; the word jeans became standard much later."],
  },
  {
    id: "san-francisco-cable-car",
    title: "San Francisco's first cable car climbs",
    year: 1873,
    category: "tech",
    emoji: "🚋",
    color: "sky",
    fact: "A grip beneath the car clamped onto a continuously moving underground cable to conquer the city's steep hills.",
  },
  {
    id: "first-impressionist-exhibition",
    title: "The first Impressionist exhibition opens",
    year: 1874,
    category: "culture",
    emoji: "🎨",
    color: "lilac",
    fact: "Thirty artists bypassed Paris's official Salon; a mocking review of Monet's Impression, Sunrise gave the movement its name.",
  },
  {
    id: "barbed-wire-patent",
    title: "Practical barbed wire is patented",
    year: 1874,
    category: "tech",
    emoji: "🪢",
    color: "sky",
    fact: "Joseph Glidden's cheap fencing rapidly enclosed the open plains and transformed ranching and Indigenous lands.",
  },
  {
    id: "universal-postal-union",
    title: "The Universal Postal Union is created",
    year: 1874,
    category: "world",
    emoji: "✉️",
    color: "coral",
    fact: "The Treaty of Bern turned separate national mail systems into one network with shared rules for international post.",
  },
  {
    id: "carmen-premieres",
    title: "Carmen premieres",
    year: 1875,
    category: "culture",
    emoji: "🌹",
    color: "lilac",
    fact: "Bizet's opera shocked some Paris audiences with its defiant heroine and realism before becoming one of opera's biggest hits.",
  },
  {
    id: "metre-convention",
    title: "Nations sign the Metre Convention",
    year: 1875,
    category: "discovery",
    emoji: "📏",
    color: "mint",
    fact: "Seventeen countries created permanent international machinery to keep measurements consistent across borders.",
  },
  {
    id: "first-indoor-ice-hockey",
    title: "The first organized indoor hockey game",
    year: 1875,
    category: "culture",
    emoji: "🏒",
    color: "lilac",
    fact: "Two nine-player teams used a flat wooden puck inside Montreal's Victoria Skating Rink.",
  },
  {
    id: "dewey-decimal-system",
    title: "The Dewey Decimal system is published",
    year: 1876,
    category: "culture",
    emoji: "🔢",
    color: "lilac",
    fact: "Melvil Dewey's first anonymous classification guide was a slim 44-page pamphlet for organizing library shelves.",
  },
  {
    id: "otto-four-stroke-engine",
    title: "The four-stroke engine runs",
    year: 1876,
    category: "tech",
    emoji: "⚙️",
    color: "sky",
    fact: "Nikolaus Otto's efficient intake-compression-power-exhaust cycle became the pattern for countless car engines.",
  },
  {
    id: "first-wimbledon",
    title: "The first Wimbledon championship",
    year: 1877,
    category: "culture",
    emoji: "🎾",
    color: "lilac",
    fact: "Twenty-two men entered a single event at a croquet club; Spencer Gore won the final in straight sets.",
  },
  {
    id: "mars-moons-discovered",
    title: "The moons of Mars are discovered",
    year: 1877,
    category: "discovery",
    emoji: "🔴",
    color: "mint",
    fact: "Asaph Hall found tiny Deimos and Phobos only days apart after his wife urged him not to abandon the search.",
  },
  {
    id: "first-telephone-exchange",
    title: "The first commercial telephone exchange opens",
    year: 1878,
    category: "tech",
    emoji: "☎️",
    color: "sky",
    fact: "A switchboard in New Haven connected 21 subscribers who previously needed direct wires to one another.",
  },
  {
    id: "muybridge-running-horse",
    title: "A camera freezes a galloping horse",
    year: 1878,
    category: "tech",
    emoji: "🐎",
    color: "sky",
    fact: "Eadweard Muybridge's rapid sequence proved that all four hooves leave the ground together during a gallop.",
  },
  {
    id: "saccharin-discovered",
    title: "Saccharin is discovered",
    year: 1879,
    category: "discovery",
    emoji: "🍬",
    color: "mint",
    fact: "Chemist Constantin Fahlberg noticed an intensely sweet taste on his unwashed hand after working with coal-tar compounds.",
  },
  {
    id: "war-of-the-pacific-begins",
    title: "The War of the Pacific begins",
    year: 1879,
    category: "world",
    emoji: "🏜️",
    color: "coral",
    fact: "Chile fought Peru and Bolivia over a mineral-rich desert; the resulting borders left Bolivia landlocked.",
  },

  // 1880s
  {
    id: "frozen-meat-reaches-britain",
    title: "Frozen Australian meat reaches Britain",
    year: 1880,
    category: "tech",
    emoji: "🧊",
    color: "sky",
    fact: "The Strathleven's refrigerated cargo arrived edible after two months at sea, transforming the global food trade.",
    bonusFacts: ["The shipment included roughly 40 tons of beef and mutton from Australia."],
  },
  {
    id: "photophone-demonstrated",
    title: "A voice travels on a beam of light",
    year: 1880,
    category: "tech",
    emoji: "☀️",
    color: "sky",
    fact: "Bell and Tainter's photophone sent speech wirelessly by making reflected sunlight vibrate.",
    bonusFacts: ["Bell considered the photophone a greater achievement than his telephone, although clouds made it impractical."],
  },
  {
    id: "modern-seismograph-japan",
    title: "The modern seismograph takes shape",
    year: 1880,
    category: "discovery",
    emoji: "📈",
    color: "mint",
    fact: "Scientists working in earthquake-prone Japan developed instruments that recorded ground motion against an inert pendulum.",
    bonusFacts: ["John Milne, James Ewing and Thomas Gray formed the Seismological Society of Japan that same year."],
  },
  {
    id: "godalming-public-electricity",
    title: "A town gets public electric power",
    year: 1881,
    category: "tech",
    emoji: "💡",
    color: "sky",
    fact: "Godalming in England used a waterwheel-driven generator to power street lamps and some private lights.",
    bonusFacts: ["The pioneering system closed after a few years because its supplier found it unprofitable."],
  },
  {
    id: "tuskegee-institute-opens",
    title: "Tuskegee Institute opens",
    year: 1881,
    category: "culture",
    emoji: "🎓",
    color: "lilac",
    fact: "The school began in a rented church with Booker T. Washington as its first leader and 30 students.",
    bonusFacts: ["Students helped construct early campus buildings while learning trades and academic subjects."],
  },
  {
    id: "tuberculosis-bacterium-identified",
    title: "The tuberculosis bacterium is identified",
    year: 1882,
    category: "discovery",
    emoji: "🦠",
    color: "mint",
    fact: "Robert Koch stained and photographed the bacillus, proving that a specific microbe caused the deadly disease.",
    bonusFacts: ["His announcement date, 24 March, is now observed as World Tuberculosis Day."],
  },
  {
    id: "sagrada-familia-construction",
    title: "Construction begins on the Sagrada Família",
    year: 1882,
    category: "culture",
    emoji: "⛪",
    color: "lilac",
    fact: "Barcelona's colossal basilica began under one architect; Antoni Gaudí took over the project the following year.",
    bonusFacts: ["Gaudí knew he would not live to finish it and left models for future builders."],
  },
  {
    id: "electric-desk-fan",
    title: "The electric desk fan is invented",
    year: 1882,
    category: "tech",
    emoji: "🌀",
    color: "sky",
    fact: "Schuyler Wheeler attached a two-bladed propeller directly to a small electric motor—without a safety cage.",
    bonusFacts: ["Early electric fans were luxury office machines because few homes had electricity."],
  },
  {
    id: "krakatoa-erupts",
    title: "Krakatoa erupts",
    year: 1883,
    category: "world",
    emoji: "🌋",
    color: "coral",
    fact: "The Indonesian eruption generated devastating tsunamis and a blast heard thousands of kilometers away.",
    bonusFacts: ["Its pressure wave circled Earth several times, while volcanic haze colored sunsets worldwide."],
  },
  {
    id: "orient-express-first-journey",
    title: "The Orient Express makes its first journey",
    year: 1883,
    category: "culture",
    emoji: "🚆",
    color: "lilac",
    fact: "The luxury route linked Paris with Constantinople using trains, a Danube ferry and a final steamship connection.",
    bonusFacts: ["A continuous rail journey all the way to Constantinople only became possible in 1889."],
  },
  {
    id: "railroad-time-zones",
    title: "Railroads introduce standard time zones",
    year: 1883,
    category: "world",
    emoji: "🕓",
    color: "coral",
    fact: "North American railways replaced a chaos of local solar times with four coordinated continental zones.",
  },
  {
    id: "indian-national-congress-founded",
    title: "The Indian National Congress is founded",
    year: 1885,
    category: "world",
    emoji: "🇮🇳",
    color: "coral",
    fact: "Seventy-two delegates met in Bombay to create the political organization that later led India's independence movement.",
  },
  {
    id: "greenwich-prime-meridian",
    title: "Greenwich becomes the prime meridian",
    year: 1884,
    category: "world",
    emoji: "🌐",
    color: "coral",
    fact: "An international conference chose the Greenwich line as zero longitude, though France kept using Paris for years.",
  },
  {
    id: "switchback-roller-coaster",
    title: "America's first roller coaster opens",
    year: 1884,
    category: "culture",
    emoji: "🎢",
    color: "lilac",
    fact: "Coney Island's Switchback Railway charged five cents for a slow, sideways-seated ride over wooden hills.",
  },
  {
    id: "waterman-fountain-pen",
    title: "Waterman patents a reliable fountain pen",
    year: 1884,
    category: "tech",
    emoji: "🖋️",
    color: "sky",
    fact: "Its grooved feed balanced ink and air, reducing the blobs and leaks that plagued earlier pens.",
  },
  {
    id: "berlin-conference",
    title: "The Berlin Conference begins",
    year: 1884,
    category: "world",
    emoji: "🗺️",
    color: "coral",
    fact: "European powers set rules for colonizing Africa without inviting a single African representative.",
  },
  {
    id: "first-motorcycle",
    title: "The first gasoline motorcycle is built",
    year: 1885,
    category: "tech",
    emoji: "🏍️",
    color: "sky",
    fact: "Daimler and Maybach's wooden Reitwagen had an engine beneath the seat and two small stabilizing wheels.",
  },
  {
    id: "rabies-vaccine-success",
    title: "The rabies vaccine saves a child",
    year: 1885,
    category: "discovery",
    emoji: "💉",
    color: "mint",
    fact: "Louis Pasteur's experimental treatment protected nine-year-old Joseph Meister after a severely rabid dog bite.",
  },
  {
    id: "cochrane-dishwasher-patent",
    title: "The practical dishwasher is patented",
    year: 1886,
    category: "tech",
    emoji: "🍽️",
    color: "sky",
    fact: "Josephine Cochrane's machine blasted dishes with water pressure instead of scrubbing them with brushes.",
  },
  {
    id: "hall-heroult-aluminum",
    title: "Cheap aluminum production is invented",
    year: 1886,
    category: "discovery",
    emoji: "🥫",
    color: "mint",
    fact: "Charles Hall and Paul Héroult independently discovered the same electrolytic process in the United States and France.",
  },
  {
    id: "berliner-gramophone-patent",
    title: "The flat-disc gramophone is patented",
    year: 1887,
    category: "tech",
    emoji: "💿",
    color: "sky",
    fact: "Emile Berliner's flat records could be copied from a master more easily than the cylinders used by early phonographs.",
  },
  {
    id: "michelson-morley-experiment",
    title: "The Michelson–Morley experiment finds nothing",
    year: 1887,
    category: "discovery",
    emoji: "🔦",
    color: "mint",
    fact: "Its famous null result found no motion through the supposed luminiferous ether and unsettled classical physics.",
  },
  {
    id: "esperanto-published",
    title: "Esperanto is introduced",
    year: 1887,
    category: "culture",
    emoji: "🗣️",
    color: "lilac",
    fact: "L. L. Zamenhof published his planned international language under the pen name Doktoro Esperanto—Doctor Hopeful.",
  },
  {
    id: "brazil-abolishes-slavery",
    title: "Brazil abolishes slavery",
    year: 1888,
    category: "world",
    emoji: "⛓️‍💥",
    color: "coral",
    fact: "Princess Isabel signed the brief Golden Law, freeing roughly 700,000 people in the last country in the Americas to end legal slavery.",
  },
  {
    id: "first-jukebox",
    title: "The first jukebox starts playing",
    year: 1889,
    category: "culture",
    emoji: "🎶",
    color: "lilac",
    fact: "A coin-operated phonograph in a San Francisco saloon played through four listening tubes instead of a loudspeaker.",
  },

  // 1890s
  {
    id: "city-south-london-electric-railway",
    title: "The first deep electric railway opens",
    year: 1890,
    category: "tech",
    emoji: "🚇",
    color: "sky",
    fact: "London's City and South London Railway ran electric trains through narrow tunnels nicknamed the Tube.",
    bonusFacts: ["Its original carriages had tiny high windows and were quickly nicknamed padded cells."],
  },
  {
    id: "yosemite-national-park",
    title: "Yosemite becomes a national park",
    year: 1890,
    category: "world",
    emoji: "🌲",
    color: "coral",
    fact: "The new park protected high country around Yosemite Valley, which remained under California control until 1906.",
    bonusFacts: ["John Muir's campaigning helped persuade Congress to protect the surrounding forests and watersheds."],
  },
  {
    id: "basketball-invented",
    title: "Basketball is invented",
    year: 1891,
    category: "culture",
    emoji: "🏀",
    color: "lilac",
    fact: "James Naismith hung peach baskets in a Massachusetts gym to create an indoor winter game with 13 rules.",
    bonusFacts: ["The first game used a soccer ball, nine players per side and baskets whose bottoms stayed closed."],
  },
  {
    id: "escalator-patent",
    title: "The escalator is invented",
    year: 1891,
    category: "tech",
    emoji: "↗️",
    color: "sky",
    fact: "Jesse Reno filed a patent for his moving inclined elevator and later installed a ride version at Coney Island.",
    bonusFacts: ["The word escalator was coined years later by combining elevator with scala, Latin for steps."],
  },
  {
    id: "sherlock-holmes-short-stories",
    title: "Sherlock Holmes enters The Strand",
    year: 1891,
    category: "culture",
    emoji: "🔎",
    color: "lilac",
    fact: "A Scandal in Bohemia began the magazine stories that turned Conan Doyle's detective into a phenomenon.",
    bonusFacts: ["Illustrator Sidney Paget helped create Holmes's visual identity, including the deerstalker hat."],
  },
  {
    id: "ellis-island-opens",
    title: "Ellis Island begins processing immigrants",
    year: 1892,
    category: "world",
    emoji: "🗽",
    color: "coral",
    fact: "An Irish teenager named Annie Moore became the first arrival processed at the new federal station.",
    bonusFacts: ["Nearly 12 million immigrants passed through Ellis Island before it closed in 1954."],
  },
  {
    id: "nutcracker-premieres",
    title: "The Nutcracker premieres",
    year: 1892,
    category: "culture",
    emoji: "🩰",
    color: "lilac",
    fact: "Tchaikovsky's ballet received a mixed response in St Petersburg and became a holiday obsession much later.",
    bonusFacts: ["Its Dance of the Sugar Plum Fairy showcased the newly invented celesta."],
  },
  {
    id: "diesel-engine-patent",
    title: "Rudolf Diesel patents his engine idea",
    year: 1892,
    category: "tech",
    emoji: "🚛",
    color: "sky",
    fact: "Diesel proposed igniting fuel through highly compressed hot air rather than an electrical spark.",
    bonusFacts: ["A successful practical engine followed in 1897 and was dramatically more efficient than many steam engines."],
  },
  {
    id: "automatic-telephone-exchange",
    title: "The automatic telephone exchange arrives",
    year: 1892,
    category: "tech",
    emoji: "📞",
    color: "sky",
    fact: "Almon Strowger's switching system let callers connect without a human operator—reportedly because he mistrusted one.",
    bonusFacts: ["Early users tapped buttons for each digit; the rotary dial followed later."],
  },
  {
    id: "new-zealand-womens-suffrage",
    title: "New Zealand gives women the vote",
    year: 1893,
    category: "world",
    emoji: "🗳️",
    color: "coral",
    fact: "New Zealand became the first self-governing country where women could vote in national parliamentary elections.",
    bonusFacts: ["A suffrage petition led by Kate Sheppard stretched more than 270 meters when unrolled."],
  },
  {
    id: "ferris-wheel-debuts",
    title: "The Ferris wheel debuts",
    year: 1893,
    category: "culture",
    emoji: "🎡",
    color: "lilac",
    fact: "Built for Chicago's world's fair, the original wheel carried more than 2,000 passengers at once in railway-sized cars.",
  },
  {
    id: "first-sino-japanese-war",
    title: "The First Sino-Japanese War begins",
    year: 1894,
    category: "world",
    emoji: "⚓",
    color: "coral",
    fact: "China and Japan fought mainly over influence in Korea, revealing Japan's rapid military modernization.",
  },
  {
    id: "philippine-revolution-begins",
    title: "The Philippine Revolution begins",
    year: 1896,
    category: "world",
    emoji: "☀️",
    color: "coral",
    fact: "The secret Katipunan movement launched an uprising against more than three centuries of Spanish colonial rule.",
  },
  {
    id: "manchester-ship-canal",
    title: "The Manchester Ship Canal opens",
    year: 1894,
    category: "tech",
    emoji: "🚢",
    color: "sky",
    fact: "The 58-kilometer canal turned inland Manchester into a seaport and let factories bypass Liverpool's docks.",
  },
  {
    id: "volleyball-invented",
    title: "Volleyball is invented",
    year: 1895,
    category: "culture",
    emoji: "🏐",
    color: "lilac",
    fact: "William Morgan created a gentler indoor alternative to basketball and originally called it Mintonette.",
  },
  {
    id: "nobel-prize-will",
    title: "Nobel's will creates his prizes",
    year: 1895,
    category: "world",
    emoji: "🏅",
    color: "coral",
    fact: "Alfred Nobel left most of his fortune for annual prizes in science, literature and peace, startling his family.",
  },
  {
    id: "marconi-radio-signals",
    title: "Marconi sends radio signals outdoors",
    year: 1895,
    category: "tech",
    emoji: "📡",
    color: "sky",
    fact: "Experiments on his family's Italian estate sent wireless signals beyond visual range and over a hill.",
  },
  {
    id: "ethiopia-wins-at-adwa",
    title: "Ethiopia defeats Italy at Adwa",
    year: 1896,
    category: "world",
    emoji: "🇪🇹",
    color: "coral",
    fact: "Emperor Menelik II's army defeated an invading European power and secured Ethiopia's independence.",
  },
  {
    id: "dracula-published",
    title: "Dracula is published",
    year: 1897,
    category: "culture",
    emoji: "🧛",
    color: "lilac",
    fact: "Bram Stoker told the vampire story through diaries, letters, telegrams, newspaper clippings and ship logs.",
  },
  {
    id: "aspirin-synthesized",
    title: "Aspirin is synthesized in a stable form",
    year: 1897,
    category: "discovery",
    emoji: "💊",
    color: "mint",
    fact: "Bayer chemists produced pure acetylsalicylic acid in a stable form, building on a remedy related to willow bark.",
  },
  {
    id: "electron-discovered",
    title: "The electron is discovered",
    year: 1897,
    category: "discovery",
    emoji: "⚛️",
    color: "mint",
    fact: "J. J. Thomson showed cathode rays were tiny negatively charged particles, proving atoms were not indivisible.",
  },
  {
    id: "london-electric-taxis",
    title: "Electric taxis roll through London",
    year: 1897,
    category: "tech",
    emoji: "🚕",
    color: "sky",
    fact: "Battery-powered Bersey cabs were quiet and clean but heavy tires and unreliable batteries ended the fleet quickly.",
  },
  {
    id: "radium-polonium-discovered",
    title: "Radium and polonium are discovered",
    year: 1898,
    category: "discovery",
    emoji: "☢️",
    color: "mint",
    fact: "Marie and Pierre Curie found two new radioactive elements in pitchblende; polonium honored Marie's native Poland.",
  },
  {
    id: "first-hague-peace-conference",
    title: "The first Hague Peace Conference meets",
    year: 1899,
    category: "world",
    emoji: "🕊️",
    color: "coral",
    fact: "Twenty-six states created a permanent court for arbitration and agreed on rules intended to limit warfare.",
  },
  {
    id: "magnetic-sound-recording",
    title: "Sound is recorded magnetically",
    year: 1899,
    category: "tech",
    emoji: "🎙️",
    color: "sky",
    fact: "Valdemar Poulsen's Telegraphone stored voices as magnetic patterns on steel wire, anticipating tape recording.",
  },

  // 1900s
  {
    id: "michelin-guide-launches",
    title: "The Michelin Guide launches",
    year: 1900,
    category: "culture",
    emoji: "🍽️",
    color: "lilac",
    fact: "Michelin gave motorists a free red handbook of maps, mechanics, hotels and restaurants to encourage more driving—and tire use.",
    bonusFacts: ["Restaurant stars did not appear until 1926; the original edition told drivers how to change a tire."],
  },
  {
    id: "zeppelin-first-flight",
    title: "The first Zeppelin flies",
    year: 1900,
    category: "tech",
    emoji: "🎈",
    color: "sky",
    fact: "Count Zeppelin's enormous rigid airship lifted from a floating hangar over Lake Constance for an 18-minute flight.",
    bonusFacts: ["Its aluminum frame contained 17 separate hydrogen gas cells."],
  },
  {
    id: "kodak-brownie-camera",
    title: "The one-dollar Brownie camera goes on sale",
    year: 1900,
    category: "tech",
    emoji: "📷",
    color: "sky",
    fact: "Kodak's simple cardboard-box camera made casual snapshots affordable enough for children and ordinary families.",
    bonusFacts: ["A roll of film cost just 15 cents, while the camera itself sold for one dollar."],
  },
  {
    id: "paris-metro-opens",
    title: "The Paris Métro opens",
    year: 1900,
    category: "tech",
    emoji: "Ⓜ️",
    color: "sky",
    fact: "Line 1 began carrying world's-fair crowds across Paris beneath Hector Guimard's wildly organic station entrances.",
    bonusFacts: ["The first line ran from Porte de Vincennes to Porte Maillot in about half an hour."],
  },
  {
    id: "planck-quantum-theory",
    title: "Planck introduces energy quanta",
    year: 1900,
    category: "discovery",
    emoji: "✨",
    color: "mint",
    fact: "To explain the glow of hot objects, Max Planck proposed that energy came in discrete packets rather than any amount.",
    bonusFacts: ["The constant in his formula became Planck's constant, a foundation of quantum physics."],
  },
  {
    id: "first-nobel-prizes",
    title: "The first Nobel Prizes are awarded",
    year: 1901,
    category: "world",
    emoji: "🏅",
    color: "coral",
    fact: "Five prizes honored work in physics, chemistry, medicine, literature and peace five years after Alfred Nobel's death.",
    bonusFacts: ["The first Peace Prize was shared by Red Cross founder Henry Dunant and peace campaigner Frédéric Passy."],
  },
  {
    id: "australia-federates",
    title: "Australia becomes a federation",
    year: 1901,
    category: "world",
    emoji: "🇦🇺",
    color: "coral",
    fact: "Six self-governing British colonies united as the Commonwealth of Australia, with Edmund Barton as first prime minister.",
    bonusFacts: ["The temporary capital remained Melbourne until the new Parliament House opened in Canberra in 1927."],
  },
  {
    id: "booth-powered-vacuum",
    title: "The powered vacuum cleaner arrives",
    year: 1901,
    category: "tech",
    emoji: "🧹",
    color: "sky",
    fact: "Hubert Cecil Booth's giant petrol machine parked outside while long hoses snaked through a building's windows.",
    bonusFacts: ["Customers hired the horse-drawn machine and crew; portable home vacuums followed later."],
  },
  {
    id: "trip-to-the-moon-film",
    title: "A Trip to the Moon reaches cinemas",
    year: 1902,
    category: "culture",
    emoji: "🌙",
    color: "lilac",
    fact: "Georges Méliès packed sets, tricks and dancing aliens into the film whose rocket lands in the Moon's eye.",
    bonusFacts: ["Some prints were painstakingly colored frame by frame by teams of women."],
  },
  {
    id: "teddy-bear-named",
    title: "The teddy bear gets its name",
    year: 1902,
    category: "culture",
    emoji: "🧸",
    color: "lilac",
    fact: "A cartoon of Theodore Roosevelt refusing to shoot a tethered bear inspired toy bears carrying his nickname.",
    bonusFacts: ["American shopkeeper Morris Michtom and Germany's Steiff company developed early teddy bears independently."],
  },
  {
    id: "modern-air-conditioning",
    title: "Modern air conditioning is invented",
    year: 1902,
    category: "tech",
    emoji: "❄️",
    color: "sky",
    fact: "Willis Carrier designed his system to control humidity in a Brooklyn printing plant, not to keep people comfortable.",
  },
  {
    id: "mount-pelee-eruption",
    title: "Mount Pelée destroys Saint-Pierre",
    year: 1902,
    category: "world",
    emoji: "🌋",
    color: "coral",
    fact: "A fast, superheated cloud from the Martinique volcano devastated the city in minutes and killed nearly 30,000 people.",
  },
  {
    id: "first-tour-de-france",
    title: "The first Tour de France begins",
    year: 1903,
    category: "culture",
    emoji: "🚴",
    color: "lilac",
    fact: "A sports newspaper created the six-stage, 2,428-kilometer race to boost circulation—and succeeded spectacularly.",
  },
  {
    id: "electrocardiograph-invented",
    title: "The practical electrocardiograph debuts",
    year: 1903,
    category: "discovery",
    emoji: "🫀",
    color: "mint",
    fact: "Willem Einthoven's huge string galvanometer traced the heart's electrical signals while patients put limbs in salt water.",
  },
  {
    id: "panama-independence",
    title: "Panama declares independence",
    year: 1903,
    category: "world",
    emoji: "🇵🇦",
    color: "coral",
    fact: "Panama separated from Colombia with decisive U.S. backing, then granted the United States control of a canal zone.",
  },
  {
    id: "new-york-subway-opens",
    title: "The New York subway opens",
    year: 1904,
    category: "tech",
    emoji: "🚇",
    color: "sky",
    fact: "More than 100,000 people rode the first underground line on opening day for a five-cent fare.",
  },
  {
    id: "fifa-founded",
    title: "FIFA is founded",
    year: 1904,
    category: "culture",
    emoji: "⚽",
    color: "lilac",
    fact: "Seven European football associations met in Paris to create an international governing body; England joined later.",
  },
  {
    id: "peter-pan-premieres",
    title: "Peter Pan premieres on stage",
    year: 1904,
    category: "culture",
    emoji: "🧚",
    color: "lilac",
    fact: "J. M. Barrie's play introduced London audiences to Neverland, the Lost Boys and a hero who refused to grow up.",
  },
  {
    id: "all-india-muslim-league-founded",
    title: "The All-India Muslim League is founded",
    year: 1906,
    category: "world",
    emoji: "🌙",
    color: "coral",
    fact: "Political leaders meeting in Dhaka formed the party that decades later spearheaded the campaign for Pakistan.",
  },
  {
    id: "first-grand-prix",
    title: "The first Grand Prix motor race",
    year: 1906,
    category: "culture",
    emoji: "🏎️",
    color: "lilac",
    fact: "Cars raced more than 1,200 kilometers over two sweltering days on public roads near Le Mans; Renault won.",
  },
  {
    id: "young-turk-revolution",
    title: "The Young Turk Revolution succeeds",
    year: 1908,
    category: "world",
    emoji: "📜",
    color: "coral",
    fact: "A revolt forced the Ottoman sultan to restore the constitution and parliament he had suspended three decades earlier.",
  },
  {
    id: "autochrome-color-photography",
    title: "Autochrome brings color photography to market",
    year: 1907,
    category: "tech",
    emoji: "🌈",
    color: "sky",
    fact: "The Lumière brothers' glass plates filtered light through microscopic grains of potato starch dyed red, green and blue.",
  },
  {
    id: "bakelite-invented",
    title: "Bakelite is invented",
    year: 1907,
    category: "discovery",
    emoji: "📻",
    color: "mint",
    fact: "Leo Baekeland created the first fully synthetic plastic, a heat-resistant material perfect for electrical products.",
  },
  {
    id: "tunguska-explosion",
    title: "The Tunguska explosion flattens a forest",
    year: 1908,
    category: "discovery",
    emoji: "☄️",
    color: "mint",
    fact: "An asteroid or comet burst over Siberia with no impact crater, flattening trees across roughly 2,000 square kilometers.",
  },
  {
    id: "first-channel-airplane-crossing",
    title: "An airplane crosses the English Channel",
    year: 1909,
    category: "tech",
    emoji: "🛩️",
    color: "sky",
    fact: "Louis Blériot flew from France to England in 37 minutes and claimed a £1,000 newspaper prize.",
  },

  // 1910s
  {
    id: "opera-radio-broadcast",
    title: "Opera is broadcast live by radio",
    year: 1910,
    category: "tech",
    emoji: "📻",
    color: "sky",
    fact: "Enrico Caruso's voice traveled from New York's Metropolitan Opera to experimental receivers around the city.",
    bonusFacts: ["The signal was faint and crackly, but listeners on ships in New York Harbor reportedly heard it."],
  },
  {
    id: "first-licensed-woman-pilot",
    title: "The first woman earns a pilot's license",
    year: 1910,
    category: "world",
    emoji: "👩‍✈️",
    color: "coral",
    fact: "France's Raymonde de Laroche received pilot license number 36 from the Aéro-Club de France.",
    bonusFacts: ["She had been an actor before taking flying lessons and later set women's altitude records."],
  },
  {
    id: "neon-light-public-demo",
    title: "Neon lighting makes its public debut",
    year: 1910,
    category: "tech",
    emoji: "🔴",
    color: "sky",
    fact: "Georges Claude filled glass tubes with neon and displayed their intense red-orange glow at the Paris Motor Show.",
    bonusFacts: ["Other gases and colored glass later expanded signs far beyond neon's natural reddish color."],
  },
  {
    id: "union-of-south-africa",
    title: "The Union of South Africa is created",
    year: 1910,
    category: "world",
    emoji: "🇿🇦",
    color: "coral",
    fact: "Four British colonies united as a dominion whose political system entrenched white minority rule.",
    bonusFacts: ["The union divided its branches of government among Pretoria, Cape Town and Bloemfontein."],
  },
  {
    id: "mexican-revolution-begins",
    title: "The Mexican Revolution begins",
    year: 1910,
    category: "world",
    emoji: "🇲🇽",
    color: "coral",
    fact: "An uprising against Porfirio Díaz's long rule grew into a decade of upheaval that transformed Mexico.",
    bonusFacts: ["The revolution produced Mexico's 1917 constitution, which promised land reform and workers' rights."],
  },
  {
    id: "machu-picchu-world-attention",
    title: "Machu Picchu reaches world attention",
    year: 1911,
    category: "discovery",
    emoji: "⛰️",
    color: "mint",
    fact: "Local farmer Melchor Arteaga guided Hiram Bingham to the Inca site, which nearby families already knew well.",
    bonusFacts: ["Bingham initially believed he had found Vilcabamba, the last refuge of the Inca rulers."],
  },
  {
    id: "mona-lisa-stolen",
    title: "The Mona Lisa is stolen",
    year: 1911,
    category: "culture",
    emoji: "🖼️",
    color: "lilac",
    fact: "Louvre worker Vincenzo Peruggia hid the painting for more than two years, helping turn it into a global celebrity.",
    bonusFacts: ["Police questioned poet Guillaume Apollinaire, and Pablo Picasso was drawn into the investigation."],
  },
  {
    id: "atomic-nucleus-discovered",
    title: "The atomic nucleus is discovered",
    year: 1911,
    category: "discovery",
    emoji: "⚛️",
    color: "mint",
    fact: "Rutherford explained why a few particles bounced sharply off gold foil: atoms contain a tiny, dense positive core.",
    bonusFacts: ["The result also showed that most of an atom's volume is empty space."],
  },
  {
    id: "xinhai-revolution",
    title: "China's imperial rule collapses",
    year: 1911,
    category: "world",
    emoji: "🐉",
    color: "coral",
    fact: "The Xinhai Revolution began with an uprising in Wuchang and ended more than two thousand years of imperial government.",
    bonusFacts: ["The last emperor, Puyi, was only six years old when he abdicated in 1912."],
  },
  {
    id: "anc-founded",
    title: "The African National Congress is founded",
    year: 1912,
    category: "world",
    emoji: "✊",
    color: "coral",
    fact: "Black leaders meeting in Bloemfontein formed the organization that would become central to ending apartheid.",
    bonusFacts: ["It began as the South African Native National Congress and adopted the name ANC in 1923."],
  },
  {
    id: "continental-drift-proposed",
    title: "Continental drift is proposed",
    year: 1912,
    category: "discovery",
    emoji: "🌍",
    color: "mint",
    fact: "Alfred Wegener argued that continents had moved across Earth's surface, an idea most geologists initially rejected.",
  },
  {
    id: "vitamin-word-coined",
    title: "The word vitamin is coined",
    year: 1912,
    category: "discovery",
    emoji: "🍊",
    color: "mint",
    fact: "Casimir Funk named mysterious food factors vitamines, combining vital and amine; the final e was dropped later.",
  },
  {
    id: "moving-assembly-line",
    title: "The moving assembly line transforms carmaking",
    year: 1913,
    category: "tech",
    emoji: "🏭",
    color: "sky",
    fact: "Ford's moving chassis line cut Model T assembly time from more than 12 hours to about 90 minutes.",
  },
  {
    id: "stainless-steel-invented",
    title: "Modern stainless steel is developed",
    year: 1913,
    category: "discovery",
    emoji: "🥄",
    color: "mint",
    fact: "Harry Brearley noticed that chromium-rich steel resisted rust, leading from gun barrels to gleaming cutlery.",
  },
  {
    id: "raja-harishchandra-film",
    title: "India's first full-length feature film opens",
    year: 1913,
    category: "culture",
    emoji: "🎬",
    color: "lilac",
    fact: "Dadasaheb Phalke's silent Raja Harishchandra launched Indian feature cinema with men playing every role.",
  },
  {
    id: "panama-canal-opens",
    title: "The Panama Canal opens",
    year: 1914,
    category: "world",
    emoji: "🚢",
    color: "coral",
    fact: "Locks began lifting ships across Panama, shortening the New York–San Francisco sea route by thousands of kilometers.",
  },
  {
    id: "first-scheduled-airline",
    title: "The first scheduled airline takes off",
    year: 1914,
    category: "tech",
    emoji: "🛫",
    color: "sky",
    fact: "A flying boat carried one paying passenger between St Petersburg and Tampa, Florida, in 23 minutes.",
  },
  {
    id: "little-tramp-screen-debut",
    title: "Chaplin's Little Tramp reaches screens",
    year: 1914,
    category: "culture",
    emoji: "🎩",
    color: "lilac",
    fact: "The bowler hat, cane, tiny moustache and oversized shoes first reached audiences in Kid Auto Races at Venice.",
  },
  {
    id: "general-relativity-completed",
    title: "Einstein completes general relativity",
    year: 1915,
    category: "discovery",
    emoji: "🪐",
    color: "mint",
    fact: "The theory recast gravity as curved spacetime and correctly explained a puzzling wobble in Mercury's orbit.",
  },
  {
    id: "self-service-grocery",
    title: "The first self-service grocery store opens",
    year: 1916,
    category: "culture",
    emoji: "🛒",
    color: "lilac",
    fact: "Piggly Wiggly let Memphis shoppers carry baskets through aisles and choose goods instead of asking a clerk.",
  },
  {
    id: "daylight-saving-adopted",
    title: "Daylight saving time is adopted nationally",
    year: 1916,
    category: "world",
    emoji: "⏰",
    color: "coral",
    fact: "Germany and Austria-Hungary moved clocks forward to conserve coal during the First World War; others quickly followed.",
  },
  {
    id: "dada-begins-zurich",
    title: "Dada begins at Cabaret Voltaire",
    year: 1916,
    category: "culture",
    emoji: "🎭",
    color: "lilac",
    fact: "Artists in neutral Zurich answered wartime logic with nonsense poetry, strange costumes and deliberately absurd performances.",
  },
  {
    id: "russian-revolution-1917",
    title: "The Russian Revolution topples the tsar",
    year: 1917,
    category: "world",
    emoji: "🚩",
    color: "coral",
    fact: "Two revolutions in one year ended Romanov rule and eventually brought Lenin's Bolsheviks to power.",
  },
  {
    id: "influenza-pandemic-1918",
    title: "The great influenza pandemic spreads",
    year: 1918,
    category: "world",
    emoji: "😷",
    color: "coral",
    fact: "The virus infected roughly a third of humanity and killed tens of millions, often striking healthy young adults.",
  },
  {
    id: "korea-march-first-movement",
    title: "Korea's March First Movement begins",
    year: 1919,
    category: "world",
    emoji: "🇰🇷",
    color: "coral",
    fact: "A public independence declaration sparked nationwide nonviolent demonstrations against Japanese colonial rule.",
  },

  // 1920s
  {
    id: "league-of-nations-begins",
    title: "The League of Nations begins",
    year: 1920,
    category: "world",
    emoji: "🌐",
    color: "coral",
    fact: "The first worldwide organization devoted to collective security opened without the United States, whose president had championed it.",
    bonusFacts: ["Its headquarters moved to Geneva, where its grand Palace of Nations still houses the United Nations."],
  },
  {
    id: "band-aid-invented",
    title: "The Band-Aid is invented",
    year: 1920,
    category: "tech",
    emoji: "🩹",
    color: "sky",
    fact: "Earle Dickson put gauze down the middle of adhesive tape so his accident-prone wife could dress cuts by herself.",
    bonusFacts: ["The first handmade strips were about 45 centimetres long and had to be cut to size."],
  },
  {
    id: "robot-word-debuts",
    title: "The word robot reaches the stage",
    year: 1921,
    category: "culture",
    emoji: "🤖",
    color: "lilac",
    fact: "Karel Čapek's play R.U.R. introduced robot from a Czech word for forced labor; its robots were artificial workers, not metal machines.",
    bonusFacts: ["Čapek credited his brother Josef with suggesting the word."],
  },
  {
    id: "insulin-discovered",
    title: "Insulin is discovered",
    year: 1921,
    category: "discovery",
    emoji: "💉",
    color: "mint",
    fact: "A Toronto team isolated the hormone that soon transformed type 1 diabetes from a rapid death sentence into a treatable condition.",
    bonusFacts: ["The first patient received insulin in January 1922 after biochemist James Collip improved its purity."],
  },
  {
    id: "chanel-number-five",
    title: "Chanel No. 5 launches",
    year: 1921,
    category: "culture",
    emoji: "🧴",
    color: "lilac",
    fact: "Coco Chanel chose the fifth scent sample and launched it on the fifth day of the fifth month.",
    bonusFacts: ["Its unusual dose of aldehydes gave the perfume an abstract, sparkling quality rather than one obvious flower."],
  },
  {
    id: "bbc-radio-founded",
    title: "The BBC begins broadcasting",
    year: 1922,
    category: "tech",
    emoji: "📻",
    color: "sky",
    fact: "Radio manufacturers formed the British Broadcasting Company; it became a public corporation five years later.",
    bonusFacts: ["The first daily station, 2LO, broadcast news only after 7 p.m. to avoid hurting newspaper sales."],
  },
  {
    id: "first-3d-feature-film",
    title: "The first 3D feature film is screened",
    year: 1922,
    category: "culture",
    emoji: "🕶️",
    color: "lilac",
    fact: "The now-lost film The Power of Love used red-and-green glasses during a Los Angeles premiere.",
    bonusFacts: ["Both versions are now lost; viewers could reportedly choose a happy or tragic ending through different colored lenses."],
  },
  {
    id: "morgan-traffic-signal-patent",
    title: "A three-position traffic signal is patented",
    year: 1923,
    category: "tech",
    emoji: "🚦",
    color: "sky",
    fact: "Garrett Morgan added an all-directions stop between go and stop, giving an intersection time to clear.",
    bonusFacts: ["Morgan later sold the rights to General Electric for $40,000."],
  },
  {
    id: "time-magazine-launches",
    title: "Time magazine publishes its first issue",
    year: 1923,
    category: "culture",
    emoji: "📰",
    color: "lilac",
    fact: "The new weekly promised to summarize the news for busy readers; retired politician Joseph Cannon made its first cover.",
    bonusFacts: ["Founders Henry Luce and Briton Hadden were only 24 and 25 years old."],
  },
  {
    id: "buenos-aires-radio-opera",
    title: "Radio opera airs from Buenos Aires",
    year: 1920,
    category: "culture",
    emoji: "📻",
    color: "lilac",
    fact: "A rooftop transmitter broadcast Wagner's Parsifal from the Teatro Coliseo in one of the world's earliest scheduled radio programs.",
    bonusFacts: ["The pioneering group became known as Los Locos de la Azotea—the Madmen of the Rooftop."],
  },
  {
    id: "first-winter-olympics",
    title: "The first Winter Olympics are held",
    year: 1924,
    category: "culture",
    emoji: "⛷️",
    color: "lilac",
    fact: "Chamonix hosted 258 athletes from 16 nations at an event retroactively recognized as the first Olympic Winter Games.",
  },
  {
    id: "caesar-salad-created",
    title: "The Caesar salad is created",
    year: 1924,
    category: "culture",
    emoji: "🥗",
    color: "lilac",
    fact: "Restaurateur Caesar Cardini tossed the dramatic tableside dish in Tijuana, Mexico—not ancient Rome.",
  },
  {
    id: "macys-parade-begins",
    title: "Macy's first holiday parade",
    year: 1924,
    category: "culture",
    emoji: "🎈",
    color: "lilac",
    fact: "Store employees marched with bands and animals borrowed from the Central Park Zoo; giant balloons arrived in 1927.",
  },
  {
    id: "ibm-name-adopted",
    title: "IBM gets its name",
    year: 1924,
    category: "tech",
    emoji: "💼",
    color: "sky",
    fact: "The Computing-Tabulating-Recording Company renamed itself International Business Machines to match its growing ambitions.",
  },
  {
    id: "first-round-world-flight",
    title: "Airplanes circle the world",
    year: 1924,
    category: "tech",
    emoji: "🌏",
    color: "sky",
    fact: "A U.S. Army team took 175 days; four aircraft started from Seattle and two completed the globe-spanning relay.",
  },
  {
    id: "baird-television-face",
    title: "A moving face appears on television",
    year: 1925,
    category: "tech",
    emoji: "📺",
    color: "sky",
    fact: "John Logie Baird transmitted the recognizable grayscale face of a ventriloquist's dummy nicknamed Stooky Bill.",
  },
  {
    id: "first-motel-opens",
    title: "The first motel opens",
    year: 1925,
    category: "culture",
    emoji: "🛎️",
    color: "lilac",
    fact: "California's Milestone Mo-Tel combined motor and hotel, placing a private garage beside each guest room.",
  },
  {
    id: "republic-of-turkey-proclaimed",
    title: "The Republic of Turkey is proclaimed",
    year: 1923,
    category: "world",
    emoji: "🇹🇷",
    color: "coral",
    fact: "The new republic replaced the Ottoman state, with Ankara as its capital and Mustafa Kemal Atatürk as president.",
  },
  {
    id: "liquid-fuel-rocket",
    title: "The first liquid-fuel rocket launches",
    year: 1926,
    category: "tech",
    emoji: "🚀",
    color: "sky",
    fact: "Robert Goddard's gasoline-and-liquid-oxygen rocket flew for only 2.5 seconds but opened a path toward spaceflight.",
  },
  {
    id: "winnie-the-pooh-published",
    title: "Winnie-the-Pooh is published",
    year: 1926,
    category: "culture",
    emoji: "🍯",
    color: "lilac",
    fact: "A. A. Milne based Pooh and friends on his son's toys; Winnie borrowed her name from a bear at London Zoo.",
  },
  {
    id: "lindbergh-atlantic-flight",
    title: "Lindbergh flies solo across the Atlantic",
    year: 1927,
    category: "tech",
    emoji: "✈️",
    color: "sky",
    fact: "The Spirit of St. Louis flew nonstop from New York to Paris in about 33½ hours with no front windshield.",
  },
  {
    id: "expanding-universe-theory",
    title: "The expanding universe is proposed",
    year: 1927,
    category: "discovery",
    emoji: "🌌",
    color: "mint",
    fact: "Georges Lemaître used Einstein's equations to argue that space itself was expanding, two years before Hubble's famous paper.",
  },
  {
    id: "women-olympic-athletics",
    title: "Women enter Olympic track and field",
    year: 1928,
    category: "world",
    emoji: "🏃‍♀️",
    color: "coral",
    fact: "The Amsterdam Games added five athletics events for women, despite fierce resistance from sporting officials.",
  },
  {
    id: "first-academy-awards",
    title: "The first Academy Awards are held",
    year: 1929,
    category: "culture",
    emoji: "🏆",
    color: "lilac",
    fact: "The ceremony was a 15-minute hotel dinner for about 270 guests, and the winners had been announced months earlier.",
  },
  {
    id: "wall-street-crash",
    title: "The Wall Street Crash unfolds",
    year: 1929,
    category: "world",
    emoji: "📉",
    color: "coral",
    fact: "Panic selling on Black Monday and Black Tuesday erased fortunes and accelerated a worldwide economic crisis.",
  },

  // 1930s
  {
    id: "first-fifa-world-cup",
    title: "The first football World Cup",
    year: 1930,
    category: "culture",
    emoji: "🏆",
    color: "lilac",
    fact: "Thirteen teams traveled to Uruguay, where the hosts beat Argentina 4–2 in the final before a vast home crowd.",
    bonusFacts: ["Every match was staged in Montevideo, and there was no qualifying tournament."],
  },
  {
    id: "birdseye-frozen-foods",
    title: "Frozen foods reach supermarkets",
    year: 1930,
    category: "tech",
    emoji: "🫛",
    color: "sky",
    fact: "Birds Eye launched quick-frozen vegetables, fruit, fish and meat in a U.S. test market.",
    bonusFacts: ["Clarence Birdseye learned that extremely fast freezing preserved texture after observing Inuit food practices in Labrador."],
  },
  {
    id: "whittle-jet-engine-patent",
    title: "The jet engine is patented",
    year: 1930,
    category: "tech",
    emoji: "🛩️",
    color: "sky",
    fact: "Young RAF officer Frank Whittle patented a gas-turbine engine years before officials took the idea seriously.",
    bonusFacts: ["Germany's Hans von Ohain developed a different jet design independently later in the decade."],
  },
  {
    id: "first-airline-stewardess",
    title: "The first airline stewardess takes flight",
    year: 1930,
    category: "world",
    emoji: "👩‍⚕️",
    color: "coral",
    fact: "Registered nurse and pilot Ellen Church persuaded an airline that women nurses could reassure nervous passengers.",
    bonusFacts: ["Her first flight took about 20 hours and made 13 stops between Oakland and Chicago."],
  },
  {
    id: "gandhi-salt-march",
    title: "Gandhi begins the Salt March",
    year: 1930,
    category: "world",
    emoji: "🧂",
    color: "coral",
    fact: "A 24-day march to the Arabian Sea challenged Britain's salt monopoly with a symbolic handful of illegal salt.",
    bonusFacts: ["Gandhi set out with 78 chosen companions; thousands joined along the roughly 390-kilometer route."],
  },
  {
    id: "scotch-tape-introduced",
    title: "Transparent Scotch tape is introduced",
    year: 1930,
    category: "tech",
    emoji: "📦",
    color: "sky",
    fact: "Richard Drew's clear cellophane tape arrived during the Depression and found endless uses repairing household objects.",
    bonusFacts: ["Drew had already invented masking tape after watching auto painters struggle with two-tone paint jobs."],
  },
  {
    id: "electric-guitar-invented",
    title: "The Frying Pan electric guitar is built",
    year: 1931,
    category: "tech",
    emoji: "🎸",
    color: "sky",
    fact: "The circular Rickenbacker Frying Pan used an electromagnetic pickup to make a lap-steel guitar loud enough for bands.",
    bonusFacts: ["Its official model name was the Electro A-22; the kitchen nickname came from its shape."],
  },
  {
    id: "earhart-solo-atlantic",
    title: "Amelia Earhart flies solo across the Atlantic",
    year: 1932,
    category: "world",
    emoji: "🛩️",
    color: "coral",
    fact: "Earhart became the first woman to make the solo nonstop crossing after landing in a Northern Irish pasture.",
    bonusFacts: ["She had aimed for Paris but mechanical trouble and icy conditions forced an early landing."],
  },
  {
    id: "bbc-world-service-begins",
    title: "The BBC World Service begins",
    year: 1932,
    category: "tech",
    emoji: "🌍",
    color: "sky",
    fact: "Launched as the Empire Service, the shortwave station admitted its earliest programs might sometimes fade away entirely.",
    bonusFacts: ["King George V used the service for the first royal Christmas broadcast that same year."],
  },
  {
    id: "venice-film-festival",
    title: "The first Venice Film Festival opens",
    year: 1932,
    category: "culture",
    emoji: "🎞️",
    color: "lilac",
    fact: "The world's oldest film festival began on a hotel terrace at the Venice Lido without a jury or official prizes.",
    bonusFacts: ["The first film shown was Dr. Jekyll and Mr. Hyde, projected outdoors at night."],
  },
  {
    id: "neutron-discovered",
    title: "The neutron is discovered",
    year: 1932,
    category: "discovery",
    emoji: "⚛️",
    color: "mint",
    fact: "James Chadwick identified the chargeless particle in atomic nuclei, explaining mysterious extra nuclear mass.",
  },
  {
    id: "saudi-arabia-proclaimed",
    title: "Saudi Arabia is proclaimed",
    year: 1932,
    category: "world",
    emoji: "🇸🇦",
    color: "coral",
    fact: "Ibn Saud united the kingdoms of Hejaz and Nejd with other territories under the new name Saudi Arabia.",
  },
  {
    id: "first-everest-flyover",
    title: "Airplanes fly over Everest",
    year: 1933,
    category: "discovery",
    emoji: "🏔️",
    color: "mint",
    fact: "Two open-cockpit biplanes crossed above the summit and brought back the first aerial photographs of Everest.",
  },
  {
    id: "donald-duck-debut",
    title: "Donald Duck makes his debut",
    year: 1934,
    category: "culture",
    emoji: "🦆",
    color: "lilac",
    fact: "The irritable sailor appeared in The Wise Little Hen, already wearing his blue outfit and speaking in a furious quack.",
  },
  {
    id: "magnetophon-tape-recorder",
    title: "Magnetic tape recording is demonstrated",
    year: 1935,
    category: "tech",
    emoji: "🎙️",
    color: "sky",
    fact: "AEG's Magnetophon recorded onto plastic tape coated with iron oxide, far easier to edit and store than steel wire.",
  },
  {
    id: "first-parking-meter",
    title: "The first parking meter is installed",
    year: 1935,
    category: "tech",
    emoji: "🅿️",
    color: "sky",
    fact: "Oklahoma City's Park-O-Meter charged five cents an hour and immediately triggered complaints and a court challenge.",
  },
  {
    id: "radar-aircraft-detection",
    title: "Radar detects an airplane",
    year: 1935,
    category: "discovery",
    emoji: "📡",
    color: "mint",
    fact: "Robert Watson-Watt's team detected a bomber from reflected radio waves during Britain's secret Daventry experiment.",
  },
  {
    id: "nylon-invented",
    title: "Nylon is invented",
    year: 1935,
    category: "discovery",
    emoji: "🧦",
    color: "mint",
    fact: "Wallace Carothers's DuPont team created the strong synthetic fiber that soon appeared in toothbrushes, stockings and parachutes.",
  },
  {
    id: "penguin-paperbacks-launch",
    title: "Penguin paperbacks launch",
    year: 1935,
    category: "culture",
    emoji: "🐧",
    color: "lilac",
    fact: "Ten quality books went on sale for sixpence each, color-coded by genre and cheap enough to buy from vending machines.",
  },
  {
    id: "turing-universal-machine",
    title: "Turing imagines a universal computer",
    year: 1936,
    category: "discovery",
    emoji: "🧠",
    color: "mint",
    fact: "Alan Turing's paper described one abstract machine capable of carrying out any computable procedure.",
  },
  {
    id: "practical-helicopter-flight",
    title: "The first practical helicopter flies",
    year: 1936,
    category: "tech",
    emoji: "🚁",
    color: "sky",
    fact: "The Focke-Wulf Fw 61 used two large side rotors and could hover, turn and fly with unprecedented control.",
  },
  {
    id: "long-march-begins",
    title: "China's Long March begins",
    year: 1934,
    category: "world",
    emoji: "🥾",
    color: "coral",
    fact: "Chinese Communist forces broke out of encirclement and began a brutal year-long retreat across thousands of kilometers.",
  },
  {
    id: "chocolate-chip-cookie",
    title: "The chocolate-chip cookie is created",
    year: 1938,
    category: "culture",
    emoji: "🍪",
    color: "lilac",
    fact: "Ruth Wakefield chopped a Nestlé chocolate bar into cookie dough at Massachusetts's Toll House restaurant.",
  },
  {
    id: "coelacanth-rediscovered",
    title: "A living coelacanth is found",
    year: 1938,
    category: "discovery",
    emoji: "🐟",
    color: "mint",
    fact: "Museum curator Marjorie Courtenay-Latimer recognized a strange South African catch from a lineage thought extinct for 66 million years.",
  },
  {
    id: "first-jet-aircraft-flight",
    title: "The first jet aircraft flies",
    year: 1939,
    category: "tech",
    emoji: "✈️",
    color: "sky",
    fact: "Germany's experimental Heinkel He 178 made a secret flight without a propeller, powered entirely by a turbojet.",
  },

  // 1940s
  {
    id: "bugs-bunny-official-debut",
    title: "Bugs Bunny makes his official debut",
    year: 1940,
    category: "culture",
    emoji: "🥕",
    color: "lilac",
    fact: "A Wild Hare paired Bugs's familiar design and voice with Elmer Fudd—and the line What's up, Doc?",
    bonusFacts: ["Earlier cartoons featured prototype rabbits, but this short established the recognizable character."],
  },
  {
    id: "lascaux-cave-discovered",
    title: "The Lascaux cave paintings are found",
    year: 1940,
    category: "discovery",
    emoji: "🐂",
    color: "mint",
    fact: "Teenagers exploring a hole in southwest France found galleries covered with prehistoric horses, bulls and deer.",
    bonusFacts: ["The original cave closed to visitors in 1963 after human breath, heat and microbes began damaging the art."],
  },
  {
    id: "indonesia-proclaims-independence",
    title: "Indonesia proclaims independence",
    year: 1945,
    category: "world",
    emoji: "🇮🇩",
    color: "coral",
    fact: "Sukarno and Mohammad Hatta declared independence two days after Japan's surrender, beginning a struggle against returning Dutch rule.",
    bonusFacts: ["The Netherlands formally transferred sovereignty after four more years of diplomacy and fighting."],
  },
  {
    id: "pearl-harbor-attack",
    title: "Japan attacks Pearl Harbor",
    year: 1941,
    category: "world",
    emoji: "⚓",
    color: "coral",
    fact: "The surprise attack on the U.S. Pacific Fleet brought the United States directly into the Second World War.",
    bonusFacts: ["All eight battleships present were damaged, but key aircraft carriers were away from the harbor."],
  },
  {
    id: "z3-computer-runs",
    title: "The programmable Z3 computer runs",
    year: 1941,
    category: "tech",
    emoji: "🖥️",
    color: "sky",
    fact: "Konrad Zuse's electromechanical machine used binary arithmetic and instructions punched into discarded movie film.",
    bonusFacts: ["The original Z3 was destroyed in a 1943 bombing raid; a working reconstruction was built in the 1960s."],
  },
  {
    id: "duct-tape-created",
    title: "Duct tape is created for ammunition boxes",
    year: 1942,
    category: "tech",
    emoji: "🩶",
    color: "sky",
    fact: "The waterproof cloth tape helped soldiers quickly seal and open ammunition cases before becoming a universal repair tool.",
    bonusFacts: ["It was first commonly called duck tape, likely because of its cotton-duck backing and water resistance."],
  },
  {
    id: "casablanca-premieres",
    title: "Casablanca premieres",
    year: 1942,
    category: "culture",
    emoji: "🎹",
    color: "lilac",
    fact: "The romantic wartime drama opened while Allied troops were fighting in North Africa, making its setting startlingly current.",
    bonusFacts: ["The screenplay was repeatedly revised during filming, so the cast did not know the ending far in advance."],
  },
  {
    id: "anne-frank-diary-begins",
    title: "Anne Frank begins her diary",
    year: 1942,
    category: "world",
    emoji: "📔",
    color: "coral",
    fact: "Anne received the red-checkered diary for her 13th birthday, weeks before her family went into hiding.",
    bonusFacts: ["She rewrote much of it after hearing a radio appeal to preserve wartime diaries for future publication."],
  },
  {
    id: "lsd-effects-discovered",
    title: "The effects of LSD are discovered",
    year: 1943,
    category: "discovery",
    emoji: "🚲",
    color: "mint",
    fact: "Chemist Albert Hofmann deliberately tested the compound and experienced its effects while cycling home from his laboratory.",
    bonusFacts: ["He had first synthesized LSD in 1938, then revisited it five years later after a mysterious accidental exposure."],
  },
  {
    id: "dialysis-machine-used",
    title: "The first practical dialysis machine is used",
    year: 1943,
    category: "discovery",
    emoji: "🩺",
    color: "mint",
    fact: "Willem Kolff's rotating drum filtered blood through cellophane tubing, using technology improvised under wartime occupation.",
    bonusFacts: ["His first long-term survivor was treated in 1945; earlier patients were already too ill to recover."],
  },
  {
    id: "little-prince-published",
    title: "The Little Prince is published",
    year: 1943,
    category: "culture",
    emoji: "🌹",
    color: "lilac",
    fact: "Saint-Exupéry's fable first appeared in French and English in New York while its author was exiled from occupied France.",
  },
  {
    id: "ikea-founded",
    title: "IKEA is founded",
    year: 1943,
    category: "culture",
    emoji: "🪑",
    color: "lilac",
    fact: "Seventeen-year-old Ingvar Kamprad began by selling pens, wallets and picture frames; furniture came later.",
  },
  {
    id: "colossus-operational",
    title: "Colossus starts breaking codes",
    year: 1944,
    category: "tech",
    emoji: "🔐",
    color: "sky",
    fact: "The electronic machine at Bletchley Park rapidly analyzed encrypted German messages and remained secret for decades.",
  },
  {
    id: "united-nations-founded",
    title: "The United Nations is founded",
    year: 1945,
    category: "world",
    emoji: "🇺🇳",
    color: "coral",
    fact: "The UN Charter came into force with 51 founding members determined to prevent another world war.",
  },
  {
    id: "philippines-independence",
    title: "The Philippines gains independence",
    year: 1946,
    category: "world",
    emoji: "🇵🇭",
    color: "coral",
    fact: "The United States recognized the independent Philippine republic after nearly five decades of American colonial rule.",
  },
  {
    id: "unicef-founded",
    title: "UNICEF is founded",
    year: 1946,
    category: "world",
    emoji: "🧒",
    color: "coral",
    fact: "Created as an emergency fund for children after the war, it kept its familiar acronym after becoming permanent.",
  },
  {
    id: "earth-photo-from-space",
    title: "Earth is photographed from space",
    year: 1946,
    category: "discovery",
    emoji: "🌎",
    color: "mint",
    fact: "A camera aboard a captured V-2 rocket took grainy pictures from more than 100 kilometers above New Mexico.",
  },
  {
    id: "india-independence-partition",
    title: "India and Pakistan become independent",
    year: 1947,
    category: "world",
    emoji: "🇮🇳🇵🇰",
    color: "coral",
    fact: "Colonial rule ended as the subcontinent was partitioned into India and Pakistan, triggering enormous migration and violence.",
  },
  {
    id: "first-supersonic-flight",
    title: "A pilot breaks the sound barrier",
    year: 1947,
    category: "tech",
    emoji: "💥",
    color: "sky",
    fact: "Chuck Yeager flew the rocket-powered Bell X-1 faster than sound with two ribs broken from a horse-riding accident.",
  },
  {
    id: "dead-sea-scrolls-found",
    title: "The Dead Sea Scrolls are found",
    year: 1947,
    category: "discovery",
    emoji: "📜",
    color: "mint",
    fact: "Bedouin shepherds found ancient manuscripts near Qumran, including the oldest known copies of books from the Hebrew Bible.",
  },
  {
    id: "world-health-organization",
    title: "The World Health Organization begins",
    year: 1948,
    category: "world",
    emoji: "🌍",
    color: "coral",
    fact: "Its constitution defined health as complete physical, mental and social well-being—not merely the absence of disease.",
  },
  {
    id: "stoke-mandeville-games",
    title: "The first Stoke Mandeville Games",
    year: 1948,
    category: "culture",
    emoji: "🏹",
    color: "lilac",
    fact: "Sixteen wheelchair athletes competed in archery on the London Olympics' opening day, beginning the Paralympic movement.",
  },
  {
    id: "peoples-republic-china",
    title: "The People's Republic of China is proclaimed",
    year: 1949,
    category: "world",
    emoji: "🇨🇳",
    color: "coral",
    fact: "Mao Zedong announced the new state in Beijing as the defeated Nationalist government retreated to Taiwan.",
  },
  {
    id: "comet-jetliner-first-flight",
    title: "The first jet airliner takes flight",
    year: 1949,
    category: "tech",
    emoji: "✈️",
    color: "sky",
    fact: "The British de Havilland Comet prototype flew three years before jet passenger service began.",
  },
  {
    id: "costa-rica-abolishes-army",
    title: "Costa Rica abolishes its army",
    year: 1948,
    category: "world",
    emoji: "🕊️",
    color: "coral",
    fact: "José Figueres symbolically disbanded the military after civil war; permanent abolition entered the 1949 constitution.",
  },
] satisfies EventItem[];
