import type { EventItem } from "./types";

export const EXPANDED_1950_NOW = [
  {
    id: "india-becomes-republic",
    title: "India becomes a republic",
    year: 1950,
    category: "world",
    emoji: "🇮🇳",
    color: "coral",
    fact: "India's new constitution took effect on 26 January, replacing the British monarch with an elected head of state.",
    bonusFacts: [
      "The date honored the 1930 declaration of complete independence, rather than the August date of independence itself.",
      "India's original handwritten constitution was decorated by artists from across the country.",
    ],
  },
  {
    id: "diners-club-card",
    title: "The first multipurpose charge card",
    year: 1950,
    category: "tech",
    emoji: "💳",
    color: "sky",
    fact: "The Diners Club card began as cardboard accepted at 27 New York restaurants—not a piece of plastic.",
    bonusFacts: [
      "Its first members paid their restaurant bill in full each month, so it was a charge card rather than revolving credit.",
    ],
  },
  {
    id: "peanuts-comic-debuts",
    title: "Peanuts enters the funny pages",
    year: 1950,
    category: "culture",
    emoji: "🐶",
    color: "lilac",
    fact: "Charlie Brown appeared in the very first Peanuts strip, but Snoopy did not show up until two days later.",
    bonusFacts: [
      "Charles Schulz disliked the name Peanuts; the newspaper syndicate chose it over his preferred title, Li'l Folks.",
    ],
  },
  {
    id: "uruguay-maracana-world-cup",
    title: "Uruguay silences the Maracanã",
    year: 1950,
    category: "culture",
    emoji: "⚽",
    color: "lilac",
    fact: "Uruguay beat host Brazil 2–1 in the World Cup's deciding match before one of football's largest crowds.",
  },
  {
    id: "univac-first-delivery",
    title: "The first UNIVAC is delivered",
    year: 1951,
    category: "tech",
    emoji: "🧮",
    color: "sky",
    fact: "The room-sized UNIVAC I stored data on magnetic tape and was delivered to the U.S. Census Bureau.",
    bonusFacts: [
      "A UNIVAC famously forecast Eisenhower's 1952 election win after receiving only a small fraction of the returns.",
    ],
  },
  {
    id: "catcher-in-the-rye",
    title: "The Catcher in the Rye is published",
    year: 1951,
    category: "culture",
    emoji: "🧢",
    color: "lilac",
    fact: "J. D. Salinger's story unfolds over just a few winter days, narrated by expelled teenager Holden Caulfield.",
  },
  {
    id: "first-asian-games",
    title: "The first Asian Games begin",
    year: 1951,
    category: "culture",
    emoji: "🏟️",
    color: "lilac",
    fact: "Athletes from 11 nations gathered in New Delhi for the first Asian Games, competing in six sports.",
    bonusFacts: [
      "A bright sun with 16 rays became the Games' emblem, representing the warm spirit of Asian people.",
    ],
  },
  {
    id: "comet-jetliner-service",
    title: "Jetliner passenger service begins",
    year: 1952,
    category: "tech",
    emoji: "✈️",
    color: "sky",
    fact: "The de Havilland Comet carried fare-paying passengers from London to Johannesburg faster and higher than propeller airliners.",
    bonusFacts: [
      "Its square windows later helped engineers understand how repeated pressurization could concentrate metal fatigue.",
    ],
  },
  {
    id: "barcode-patent-granted",
    title: "The barcode is patented",
    year: 1952,
    category: "tech",
    emoji: "🏷️",
    color: "sky",
    fact: "The original patent showed circular, bull's-eye-like bars so a scanner could read them from any angle.",
  },
  {
    id: "elizabeth-ii-reign-begins",
    title: "Elizabeth II becomes queen",
    year: 1952,
    category: "world",
    emoji: "👑",
    color: "coral",
    fact: "Elizabeth learned she had become queen while staying in a treetop lodge in Kenya.",
    bonusFacts: [
      "Her reign began at age 25 and eventually lasted more than 70 years, the longest of any British monarch.",
    ],
  },
  {
    id: "everest-first-ascent",
    title: "Everest's first confirmed ascent",
    year: 1953,
    category: "discovery",
    emoji: "🏔️",
    color: "mint",
    fact: "Tenzing Norgay and Edmund Hillary reached the summit and spent only about 15 minutes there.",
    bonusFacts: [
      "News of the ascent reached London on the morning of Queen Elizabeth II's coronation.",
      "Hillary and Tenzing initially agreed not to name who stepped up first; Tenzing later wrote that Hillary did.",
    ],
  },
  {
    id: "ntsc-color-television",
    title: "Compatible color television arrives",
    year: 1953,
    category: "tech",
    emoji: "📺",
    color: "sky",
    fact: "The NTSC color standard let new color broadcasts remain watchable on the millions of black-and-white sets already in homes.",
  },
  {
    id: "swanson-tv-dinner",
    title: "The TV dinner goes on sale",
    year: 1954,
    category: "culture",
    emoji: "🍽️",
    color: "lilac",
    fact: "Swanson's first TV Brand Dinner put turkey, cornbread dressing, peas and sweet potatoes in an airplane-style tray.",
  },
  {
    id: "transistor-radio-sale",
    title: "The transistor radio goes on sale",
    year: 1954,
    category: "tech",
    emoji: "📻",
    color: "sky",
    fact: "The pocket-sized Regency TR-1 made music truly portable, though its small battery could cost nearly as much as a week's wages.",
    bonusFacts: [
      "Its four transistors replaced the fragile, power-hungry vacuum tubes used in earlier portable radios.",
    ],
  },
  {
    id: "obninsk-nuclear-grid",
    title: "Nuclear power reaches the grid",
    year: 1954,
    category: "discovery",
    emoji: "⚛️",
    color: "mint",
    fact: "The small Obninsk plant in the Soviet Union became the first nuclear reactor to supply electricity to a power grid.",
  },
  {
    id: "brown-board-ruling",
    title: "U.S. school segregation is struck down",
    year: 1954,
    category: "world",
    emoji: "🏫",
    color: "coral",
    fact: "Brown v. Board of Education unanimously ruled that racially separate public schools were inherently unequal.",
  },
  {
    id: "polio-vaccine-success",
    title: "The polio vaccine is declared effective",
    year: 1955,
    category: "discovery",
    emoji: "💉",
    color: "mint",
    fact: "The announcement came exactly ten years after Franklin Roosevelt's death and triggered celebrations across the United States.",
    bonusFacts: [
      "The enormous field trial involved about 1.8 million children known as Polio Pioneers.",
      "Jonas Salk chose not to patent the vaccine, saying it belonged to the people.",
    ],
  },
  {
    id: "rosa-parks-bus",
    title: "Rosa Parks refuses to give up her seat",
    year: 1955,
    category: "world",
    emoji: "🚌",
    color: "coral",
    fact: "Her arrest sparked the 381-day Montgomery bus boycott, organized through carpools and miles of walking.",
    bonusFacts: [
      "Parks was already an experienced civil-rights organizer and secretary of her local NAACP chapter.",
    ],
  },
  {
    id: "guinness-records-first-edition",
    title: "Guinness publishes its record book",
    year: 1955,
    category: "culture",
    emoji: "🏆",
    color: "lilac",
    fact: "The book began after a brewery executive argued over Europe's fastest game bird during a shooting party.",
  },
  {
    id: "bandung-conference",
    title: "The Bandung Conference",
    year: 1955,
    category: "world",
    emoji: "🌏",
    color: "coral",
    fact: "Twenty-nine newly independent and decolonizing countries met in Indonesia without their former colonial powers.",
    bonusFacts: [
      "The meeting helped lay the political groundwork for the later Non-Aligned Movement.",
    ],
  },
  {
    id: "ampex-videotape",
    title: "Television gets instant replay",
    year: 1956,
    category: "tech",
    emoji: "📼",
    color: "sky",
    fact: "Ampex demonstrated the first practical videotape recorder, letting broadcasters replay pictures without developing film.",
    bonusFacts: [
      "A taped surprise playback made the demonstration audience erupt because many had assumed live television could not be recorded.",
    ],
  },
  {
    id: "dartmouth-ai-workshop",
    title: "Artificial intelligence gets its name",
    year: 1956,
    category: "discovery",
    emoji: "🤖",
    color: "mint",
    fact: "A summer workshop at Dartmouth popularized the term artificial intelligence for machines that could reason and learn.",
    bonusFacts: [
      "Its proposal confidently suggested that major features of intelligence could be precisely described for a machine to simulate.",
    ],
  },
  {
    id: "first-eurovision",
    title: "The first Eurovision Song Contest",
    year: 1956,
    category: "culture",
    emoji: "🎤",
    color: "lilac",
    fact: "Seven countries competed in Switzerland, each entering two songs—the only contest ever to use that format.",
  },
  {
    id: "ibm-ramac-hard-drive",
    title: "The first hard disk stores data",
    year: 1956,
    category: "tech",
    emoji: "💾",
    color: "sky",
    fact: "IBM's RAMAC stored about five megabytes on 50 spinning disks in a cabinet the size of two refrigerators.",
    bonusFacts: [
      "Unlike tape, its moving arm could jump directly to a requested record instead of reading everything in sequence.",
    ],
  },
  {
    id: "frisbee-toy-launch",
    title: "The Frisbee takes flight",
    year: 1957,
    category: "culture",
    emoji: "🥏",
    color: "lilac",
    fact: "Wham-O renamed its flying disc after New England students who tossed empty Frisbie Pie Company tins.",
  },
  {
    id: "ghana-independence",
    title: "Ghana gains independence",
    year: 1957,
    category: "world",
    emoji: "🇬🇭",
    color: "coral",
    fact: "Ghana became the first sub-Saharan African colony to gain independence from European rule in the postwar era.",
    bonusFacts: [
      "Its new name honored a medieval West African empire located hundreds of kilometers to the northwest.",
    ],
  },
  {
    id: "integrated-circuit-demonstrated",
    title: "The integrated circuit works",
    year: 1958,
    category: "tech",
    emoji: "🧩",
    color: "sky",
    fact: "Jack Kilby demonstrated several electronic components built together on one tiny slice of semiconductor.",
    bonusFacts: [
      "Robert Noyce independently devised a more manufacturable silicon version soon afterward; both men share credit for the invention.",
    ],
  },
  {
    id: "hula-hoop-craze",
    title: "The Hula Hoop craze begins",
    year: 1958,
    category: "culture",
    emoji: "⭕",
    color: "lilac",
    fact: "Wham-O sold tens of millions of plastic hoops in months, although hoop games had existed for thousands of years.",
  },
  {
    id: "luna-2-moon-impact",
    title: "A spacecraft reaches the Moon",
    year: 1959,
    category: "discovery",
    emoji: "🌙",
    color: "mint",
    fact: "The Soviet probe Luna 2 deliberately crashed into the Moon, becoming the first human-made object to touch another world.",
    bonusFacts: [
      "It carried metal spheres covered in Soviet emblems that were designed to scatter on impact.",
    ],
  },
  {
    id: "barbie-debut",
    title: "Barbie makes her debut",
    year: 1959,
    category: "culture",
    emoji: "👗",
    color: "lilac",
    fact: "The first Barbie wore a black-and-white striped swimsuit and was marketed as a teenage fashion model.",
    bonusFacts: [
      "Her full name is Barbara Millicent Roberts, after creator Ruth Handler's daughter.",
    ],
  },
  {
    id: "birth-control-pill-approved",
    title: "The contraceptive pill is approved",
    year: 1960,
    category: "discovery",
    emoji: "💊",
    color: "mint",
    fact: "The first oral contraceptive approved in the United States gave women unprecedented control over pregnancy timing.",
    bonusFacts: [
      "The same medication had already been approved in 1957 to treat menstrual disorders before contraception was added to its label.",
    ],
  },
  {
    id: "tiros-weather-satellite",
    title: "The first weather satellite",
    year: 1960,
    category: "discovery",
    emoji: "🛰️",
    color: "mint",
    fact: "TIROS-1 operated for only 78 days but sent thousands of cloud-cover images back from orbit.",
  },
  {
    id: "trieste-challenger-deep",
    title: "Humans reach the ocean's deepest point",
    year: 1960,
    category: "discovery",
    emoji: "🌊",
    color: "mint",
    fact: "Jacques Piccard and Don Walsh descended nearly 11 kilometers in Trieste and saw the seafloor through a tiny window.",
    bonusFacts: [
      "A loud crack during the descent came from an outer window panel, but the pressure sphere remained safe.",
      "They spent roughly 20 minutes at the bottom before beginning the long return to the surface.",
    ],
  },
  {
    id: "first-televised-presidential-debate",
    title: "Presidential candidates debate on TV",
    year: 1960,
    category: "culture",
    emoji: "📺",
    color: "lilac",
    fact: "About 70 million Americans watched Kennedy and Nixon, turning appearance and studio lighting into campaign factors.",
  },
  {
    id: "berlin-wall-built",
    title: "The Berlin Wall goes up",
    year: 1961,
    category: "world",
    emoji: "🧱",
    color: "coral",
    fact: "East German forces first sealed streets with barbed wire before replacing it with a fortified concrete barrier.",
    bonusFacts: [
      "One subway system suddenly contained ghost stations where Western trains passed through dim, guarded East Berlin platforms.",
    ],
  },
  {
    id: "unimate-factory-robot",
    title: "The first factory robot starts work",
    year: 1961,
    category: "tech",
    emoji: "🦾",
    color: "sky",
    fact: "Unimate joined a General Motors assembly line to move dangerously hot die-cast metal parts.",
    bonusFacts: [
      "Its inventor got the name by combining universal and automation.",
    ],
  },
  {
    id: "non-aligned-first-summit",
    title: "The Non-Aligned Movement meets",
    year: 1961,
    category: "world",
    emoji: "🌍",
    color: "coral",
    fact: "Leaders in Belgrade sought an independent path for countries unwilling to become satellites of either Cold War bloc.",
  },
  {
    id: "telstar-live-television",
    title: "Live TV crosses the Atlantic",
    year: 1962,
    category: "tech",
    emoji: "📡",
    color: "sky",
    fact: "The beach-ball-sized satellite enabled the first live transatlantic television pictures, but only during brief orbital windows.",
    bonusFacts: [
      "The Tornados' instrumental Telstar became a chart hit inspired by the satellite.",
    ],
  },
  {
    id: "dr-no-premiere",
    title: "James Bond arrives in cinemas",
    year: 1962,
    category: "culture",
    emoji: "🍸",
    color: "lilac",
    fact: "Dr. No introduced Sean Connery's Bond, the gun-barrel opening and a theme that would survive for decades.",
  },
  {
    id: "silent-spring-published",
    title: "Silent Spring is published",
    year: 1962,
    category: "culture",
    emoji: "🐦",
    color: "lilac",
    fact: "Rachel Carson showed how pesticides such as DDT moved through ecosystems and accumulated in wildlife.",
    bonusFacts: [
      "The title imagines a spring morning made eerily silent because birds have disappeared.",
    ],
  },
  {
    id: "algeria-independence",
    title: "Algeria gains independence",
    year: 1962,
    category: "world",
    emoji: "🇩🇿",
    color: "coral",
    fact: "Algerian independence ended 132 years of French colonial rule after a brutal eight-year war.",
  },
  {
    id: "march-on-washington",
    title: "The March on Washington",
    year: 1963,
    category: "world",
    emoji: "🤝",
    color: "coral",
    fact: "About 250,000 people gathered at the Lincoln Memorial, where Martin Luther King Jr. delivered his most famous speech.",
    bonusFacts: [
      "The full event name called for both jobs and freedom, joining economic demands to civil rights.",
    ],
  },
  {
    id: "tereshkova-spaceflight",
    title: "The first woman flies in space",
    year: 1963,
    category: "discovery",
    emoji: "👩‍🚀",
    color: "mint",
    fact: "Valentina Tereshkova orbited Earth 48 times—more than all American astronauts combined had managed by then.",
    bonusFacts: [
      "She was selected partly for her parachuting experience because Soviet cosmonauts ejected before landing.",
    ],
  },
  {
    id: "doctor-who-premiere",
    title: "Doctor Who premieres",
    year: 1963,
    category: "culture",
    emoji: "🟦",
    color: "lilac",
    fact: "The first episode aired one day after John F. Kennedy's assassination and was repeated the following week for viewers who missed it.",
  },
  {
    id: "zip-codes-begin",
    title: "ZIP Codes begin sorting mail",
    year: 1963,
    category: "tech",
    emoji: "✉️",
    color: "sky",
    fact: "The five-digit U.S. system was promoted by Mr. ZIP, a cartoon mail carrier designed to make automated sorting feel friendly.",
  },
  {
    id: "moog-synthesizer-introduced",
    title: "The Moog synthesizer is introduced",
    year: 1964,
    category: "tech",
    emoji: "🎹",
    color: "sky",
    fact: "Robert Moog's voltage-controlled modules let musicians sculpt electronic sounds with knobs, cables and keyboards.",
    bonusFacts: [
      "The instrument was initially modular and monophonic, producing only one note at a time.",
    ],
  },
  {
    id: "civil-rights-act",
    title: "The U.S. Civil Rights Act becomes law",
    year: 1964,
    category: "world",
    emoji: "⚖️",
    color: "coral",
    fact: "The landmark law prohibited segregation in public places and employment discrimination across the United States.",
  },
  {
    id: "basic-language-runs",
    title: "BASIC runs its first program",
    year: 1964,
    category: "tech",
    emoji: "⌨️",
    color: "sky",
    fact: "BASIC was designed at Dartmouth so students outside science and engineering could write computer programs.",
  },
  {
    id: "tanzania-union",
    title: "Tanganyika and Zanzibar form Tanzania",
    year: 1964,
    category: "world",
    emoji: "🇹🇿",
    color: "coral",
    fact: "The country's name blends Tanganyika and Zanzibar, the two independent states that united.",
  },
  {
    id: "early-bird-satellite",
    title: "Commercial satellite service begins",
    year: 1965,
    category: "tech",
    emoji: "🛰️",
    color: "sky",
    fact: "Intelsat I, nicknamed Early Bird, could relay 240 telephone calls or one television channel across the Atlantic.",
  },
  {
    id: "first-spacewalk-leonov",
    title: "The first spacewalk",
    year: 1965,
    category: "discovery",
    emoji: "👨‍🚀",
    color: "mint",
    fact: "Alexei Leonov floated outside for 12 minutes, then had to bleed pressure from his swollen suit to fit back through the hatch.",
    bonusFacts: [
      "His capsule later landed far off course in a snowy forest, leaving the crew to spend a freezing night among wolves.",
    ],
  },
  {
    id: "singapore-independence",
    title: "Singapore becomes independent",
    year: 1965,
    category: "world",
    emoji: "🇸🇬",
    color: "coral",
    fact: "Singapore became independent after an unexpected separation from Malaysia rather than through a planned declaration.",
  },
  {
    id: "gatorade-created",
    title: "Gatorade is mixed for the first time",
    year: 1965,
    category: "culture",
    emoji: "🥤",
    color: "lilac",
    fact: "University of Florida researchers made the drink to replace fluid and salts lost by the school's Gators football players.",
  },
  {
    id: "luna-9-soft-landing",
    title: "The first soft landing on the Moon",
    year: 1966,
    category: "discovery",
    emoji: "🌘",
    color: "mint",
    fact: "Luna 9 bounced inside an airbag-like shell, then opened its petals and transmitted the first pictures from the lunar surface.",
    bonusFacts: [
      "A British observatory decoded and published the probe's images before the Soviet Union officially released them.",
    ],
  },
  {
    id: "botswana-independence",
    title: "Botswana gains independence",
    year: 1966,
    category: "world",
    emoji: "🇧🇼",
    color: "coral",
    fact: "The former Bechuanaland began independence as one of the world's poorest countries and later built a stable democracy.",
  },
  {
    id: "cultural-revolution-begins",
    title: "China's Cultural Revolution begins",
    year: 1966,
    category: "world",
    emoji: "📕",
    color: "coral",
    fact: "Mao Zedong mobilized student Red Guards in a decade-long upheaval that attacked institutions, heritage and perceived rivals.",
  },
  {
    id: "first-atm",
    title: "The first cash machine opens",
    year: 1967,
    category: "tech",
    emoji: "🏧",
    color: "sky",
    fact: "Barclays installed the first operational cash dispenser in London; customers used special paper vouchers instead of plastic cards.",
    bonusFacts: [
      "Actor Reg Varney was recruited to make the machine's first ceremonial withdrawal.",
    ],
  },
  {
    id: "sgt-pepper-album",
    title: "Sgt. Pepper is released",
    year: 1967,
    category: "culture",
    emoji: "🎺",
    color: "lilac",
    fact: "The Beatles used four-track tape, studio effects and an imaginary band to make an album they did not intend to perform live.",
    bonusFacts: [
      "Its crowded cover assembled life-size cutouts of famous figures around the band in brightly colored uniforms.",
    ],
  },
  {
    id: "pulsars-discovered",
    title: "Pulsars are discovered",
    year: 1967,
    category: "discovery",
    emoji: "✨",
    color: "mint",
    fact: "Jocelyn Bell Burnell noticed radio pulses so regular that the team briefly labeled the signal LGM for little green men.",
    bonusFacts: [
      "The pulses come from rapidly spinning neutron stars, objects packed denser than an atomic nucleus.",
    ],
  },
  {
    id: "apollo-8-moon-orbit",
    title: "Humans orbit the Moon",
    year: 1968,
    category: "discovery",
    emoji: "🌍",
    color: "mint",
    fact: "Apollo 8's crew became the first people to leave Earth orbit and photographed the blue planet rising above the Moon.",
    bonusFacts: [
      "The famous Earthrise photograph was improvised; the crew scrambled to find color film as Earth appeared over the horizon.",
    ],
  },
  {
    id: "mother-of-all-demos",
    title: "The computer mouse gets a grand demo",
    year: 1968,
    category: "tech",
    emoji: "🖱️",
    color: "sky",
    fact: "Douglas Engelbart publicly demonstrated a mouse, windows, links, shared editing and video calls in one astonishing presentation.",
    bonusFacts: [
      "The wooden mouse had two perpendicular wheels underneath rather than a rolling ball or optical sensor.",
    ],
  },
  {
    id: "fosbury-flop-olympics",
    title: "The Fosbury Flop wins Olympic gold",
    year: 1968,
    category: "culture",
    emoji: "🥇",
    color: "lilac",
    fact: "Dick Fosbury cleared the high-jump bar backward, turning an odd personal technique into the sport's standard style.",
  },
  {
    id: "concorde-first-flight",
    title: "Concorde makes its first flight",
    year: 1969,
    category: "tech",
    emoji: "🛫",
    color: "sky",
    fact: "The Anglo-French airliner first flew subsonically; it would not break the sound barrier until later that year.",
  },
  {
    id: "sesame-street-premiere",
    title: "Sesame Street premieres",
    year: 1969,
    category: "culture",
    emoji: "🧸",
    color: "lilac",
    fact: "The show borrowed television advertising's quick pacing and repetition to teach letters and numbers to preschoolers.",
    bonusFacts: [
      "Big Bird and Oscar appeared in the first season, while Elmo did not become a major character until years later.",
    ],
  },
  {
    id: "stonewall-uprising",
    title: "The Stonewall uprising",
    year: 1969,
    category: "world",
    emoji: "🏳️‍🌈",
    color: "coral",
    fact: "Resistance to a police raid at New York's Stonewall Inn became a turning point for the modern LGBTQ+ rights movement.",
  },
  {
    id: "first-earth-day",
    title: "The first Earth Day",
    year: 1970,
    category: "world",
    emoji: "🌱",
    color: "coral",
    fact: "About 20 million Americans joined teach-ins, rallies and cleanups in what became a new kind of mass environmental protest.",
    bonusFacts: [
      "Organizers deliberately chose a Wednesday between spring break and final exams to maximize student participation.",
    ],
  },
  {
    id: "boeing-747-passenger-service",
    title: "The jumbo jet enters passenger service",
    year: 1970,
    category: "tech",
    emoji: "🛩️",
    color: "sky",
    fact: "Pan Am's first Boeing 747 service flew New York to London, carrying far more passengers than earlier airliners.",
    bonusFacts: [
      "Its distinctive upper-deck hump existed because designers expected future cargo versions to load through a hinged nose.",
    ],
  },
  {
    id: "pocket-calculators-arrive",
    title: "Pocket calculators reach consumers",
    year: 1970,
    category: "tech",
    emoji: "🧮",
    color: "sky",
    fact: "Early handheld calculators could perform four basic operations but cost about as much as a good typewriter.",
  },
  {
    id: "first-new-york-marathon",
    title: "The first New York City Marathon",
    year: 1970,
    category: "culture",
    emoji: "🏃",
    color: "lilac",
    fact: "The race consisted of repeated loops around Central Park; only 55 of its 127 starters finished.",
  },
  {
    id: "salyut-first-space-station",
    title: "The first space station reaches orbit",
    year: 1971,
    category: "discovery",
    emoji: "🛰️",
    color: "mint",
    fact: "Salyut 1 was a single Soviet module with room for a crew to live and work beyond a short capsule mission.",
    bonusFacts: [
      "The first crew could not enter after a docking failure; the next crew lived aboard for 23 days.",
    ],
  },
  {
    id: "starbucks-first-store",
    title: "The first Starbucks opens",
    year: 1971,
    category: "culture",
    emoji: "☕",
    color: "lilac",
    fact: "The original Seattle shop sold roasted coffee beans, tea and equipment—not cups of café latte.",
    bonusFacts: [
      "Its name came from Starbuck, the first mate in Moby-Dick, after the founders rejected the less inviting name Pequod.",
    ],
  },
  {
    id: "project-gutenberg-begins",
    title: "The first e-book is typed",
    year: 1971,
    category: "tech",
    emoji: "📖",
    color: "sky",
    fact: "Michael Hart typed the U.S. Declaration of Independence into a computer and launched what became Project Gutenberg.",
  },
  {
    id: "uae-founded",
    title: "The United Arab Emirates is founded",
    year: 1971,
    category: "world",
    emoji: "🇦🇪",
    color: "coral",
    fact: "Six emirates formed the federation in December; Ras Al Khaimah joined as the seventh the following year.",
  },
  {
    id: "hp35-scientific-calculator",
    title: "The scientific calculator fits a pocket",
    year: 1972,
    category: "tech",
    emoji: "🔢",
    color: "sky",
    fact: "HP's pocket-sized HP-35 could calculate logarithms and trigonometry, threatening the engineer's slide rule almost overnight.",
    bonusFacts: [
      "The 35 in its name referred to the number of keys, not a model sequence.",
    ],
  },
  {
    id: "godfather-premiere",
    title: "The Godfather premieres",
    year: 1972,
    category: "culture",
    emoji: "🐴",
    color: "lilac",
    fact: "The cat in Don Corleone's opening scene was a stray that director Francis Ford Coppola found around the studio.",
    bonusFacts: [
      "The studio initially resisted casting both Marlon Brando and the then little-known Al Pacino.",
    ],
  },
  {
    id: "stockholm-environment-conference",
    title: "The first UN environment summit",
    year: 1972,
    category: "world",
    emoji: "🌍",
    color: "coral",
    fact: "The Stockholm Conference made the human environment an international issue and led to the creation of the UN Environment Programme.",
  },
  {
    id: "apollo-17-last-moonwalk",
    title: "Apollo's final Moonwalk",
    year: 1972,
    category: "discovery",
    emoji: "👣",
    color: "mint",
    fact: "Apollo 17's Harrison Schmitt became the only professional geologist to walk on the Moon.",
    bonusFacts: [
      "Gene Cernan's final footprint remained humanity's newest mark on the lunar surface for decades.",
    ],
  },
  {
    id: "hip-hop-birth-party",
    title: "Hip-hop's founding party",
    year: 1973,
    category: "culture",
    emoji: "🎧",
    color: "lilac",
    fact: "DJ Kool Herc extended percussion breaks at a Bronx apartment party, a night widely celebrated as hip-hop's birth.",
    bonusFacts: [
      "The party was organized by his sister Cindy Campbell to raise money for back-to-school clothes.",
    ],
  },
  {
    id: "first-mri-paper",
    title: "The first MRI paper is published",
    year: 1973,
    category: "discovery",
    emoji: "🧲",
    color: "mint",
    fact: "Paul Lauterbur's landmark paper showed crude images of test tubes made by encoding their positions with magnetic-field gradients.",
    bonusFacts: [
      "The method was first called zeugmatography before magnetic resonance imaging became the standard name.",
    ],
  },
  {
    id: "skylab-launch",
    title: "Skylab launches",
    year: 1973,
    category: "discovery",
    emoji: "🔭",
    color: "mint",
    fact: "America's first space station lost a heat shield and solar panel during launch, forcing its first crew to make orbital repairs.",
  },
  {
    id: "oil-embargo-crisis",
    title: "The oil embargo shocks the world",
    year: 1973,
    category: "world",
    emoji: "⛽",
    color: "coral",
    fact: "An Arab oil embargo sent prices soaring and produced fuel queues, car-free Sundays and new pressure to conserve energy.",
  },
  {
    id: "first-upc-scan",
    title: "A barcode is scanned at checkout",
    year: 1974,
    category: "tech",
    emoji: "🛒",
    color: "sky",
    fact: "A pack of Wrigley's chewing gum became the first retail item scanned with a UPC barcode.",
    bonusFacts: [
      "The historic gum was bought at a supermarket in Troy, Ohio, and later entered the Smithsonian collection.",
    ],
  },
  {
    id: "terracotta-army-discovered",
    title: "The Terracotta Army is discovered",
    year: 1974,
    category: "discovery",
    emoji: "🏺",
    color: "mint",
    fact: "Farmers digging a well near Xi'an uncovered fragments from thousands of life-size warriors guarding China's first emperor.",
    bonusFacts: [
      "The emperor's central burial chamber remains unopened, while excavations continue around it.",
    ],
  },
  {
    id: "dungeons-dragons-published",
    title: "Dungeons & Dragons is published",
    year: 1974,
    category: "culture",
    emoji: "🐉",
    color: "lilac",
    fact: "The original game arrived as three slim rulebooks and asked players to supply imagination, pencils and unusual dice.",
    bonusFacts: [
      "Its tiny first printing of roughly 1,000 copies was assembled by hand in a basement.",
    ],
  },
  {
    id: "lucy-fossil-discovered",
    title: "Lucy the hominin is discovered",
    year: 1974,
    category: "discovery",
    emoji: "🦴",
    color: "mint",
    fact: "The 3.2-million-year-old skeleton showed that early hominins walked upright long before large brains evolved.",
    bonusFacts: [
      "The team nicknamed her Lucy after repeatedly playing the Beatles song Lucy in the Sky with Diamonds at camp.",
    ],
  },
  {
    id: "kodak-digital-camera-prototype",
    title: "The first digital camera is built",
    year: 1975,
    category: "tech",
    emoji: "📷",
    color: "sky",
    fact: "Kodak engineer Steven Sasson's prototype weighed nearly four kilograms and saved black-and-white images to cassette tape.",
    bonusFacts: [
      "Each 0.01-megapixel picture took 23 seconds to record and could only be viewed on a television.",
    ],
  },
  {
    id: "betamax-home-video",
    title: "Home video recording arrives",
    year: 1975,
    category: "tech",
    emoji: "📼",
    color: "sky",
    fact: "Sony's Betamax let ordinary viewers record television at home before VHS won the later format war.",
  },
  {
    id: "vietnam-war-ends",
    title: "The Vietnam War ends",
    year: 1975,
    category: "world",
    emoji: "🕊️",
    color: "coral",
    fact: "The fall of Saigon ended decades of conflict and reunified Vietnam under the government in Hanoi.",
  },
  {
    id: "rocky-horror-film",
    title: "The Rocky Horror Picture Show opens",
    year: 1975,
    category: "culture",
    emoji: "👄",
    color: "lilac",
    fact: "The movie flopped in its first release, then became a midnight-screening ritual with costumes, callbacks and thrown props.",
  },
  {
    id: "concorde-passenger-service",
    title: "Concorde carries paying passengers",
    year: 1976,
    category: "tech",
    emoji: "✈️",
    color: "sky",
    fact: "British and French Concordes began scheduled supersonic service on the same day, flying to Bahrain and Rio de Janeiro.",
  },
  {
    id: "viking-1-mars-landing",
    title: "Viking 1 lands on Mars",
    year: 1976,
    category: "discovery",
    emoji: "🔴",
    color: "mint",
    fact: "Viking 1 sent the first successful close-up photographs from the Martian surface and operated for more than six years.",
    bonusFacts: [
      "Its landing was delayed so orbiters could photograph safer terrain than the originally chosen site.",
    ],
  },
  {
    id: "first-ebola-outbreaks",
    title: "Ebola is identified",
    year: 1976,
    category: "discovery",
    emoji: "🧫",
    color: "mint",
    fact: "Separate outbreaks in what are now South Sudan and the Democratic Republic of the Congo revealed a deadly new virus.",
    bonusFacts: [
      "Researchers named it after the Ebola River to avoid permanently associating the disease with the affected village of Yambuku.",
    ],
  },
  {
    id: "nadia-perfect-ten",
    title: "Gymnastics gets its first perfect 10",
    year: 1976,
    category: "culture",
    emoji: "🤸",
    color: "lilac",
    fact: "Nadia Comăneci's Montreal routine scored the first Olympic 10.0, but the scoreboard could only display 1.00.",
    bonusFacts: [
      "She was 14 and earned seven perfect scores during those Games.",
    ],
  },
  {
    id: "apple-ii-launch",
    title: "The Apple II goes on sale",
    year: 1977,
    category: "tech",
    emoji: "🖥️",
    color: "sky",
    fact: "Its color graphics and ready-made case helped turn personal computers from hobbyist kits into home appliances.",
  },
  {
    id: "atari-2600-launch",
    title: "The Atari 2600 reaches living rooms",
    year: 1977,
    category: "culture",
    emoji: "🕹️",
    color: "lilac",
    fact: "Swappable cartridges let one console play many games, turning software into the star instead of built-in hardware.",
    bonusFacts: [
      "It originally launched as the Atari Video Computer System; the number 2600 became its official name years later.",
    ],
  },
  {
    id: "saturday-night-fever",
    title: "Saturday Night Fever ignites disco",
    year: 1977,
    category: "culture",
    emoji: "🕺",
    color: "lilac",
    fact: "The film's Bee Gees-heavy soundtrack became one of the best-selling albums ever, although the group did not appear in the movie.",
  },
  {
    id: "first-gps-satellite",
    title: "The first GPS satellite launches",
    year: 1978,
    category: "tech",
    emoji: "📍",
    color: "sky",
    fact: "Navstar 1 began the orbital constellation that would eventually let phones pinpoint a location almost anywhere on Earth.",
    bonusFacts: [
      "The first experimental satellites carried extremely precise atomic clocks to measure travel time from orbit.",
    ],
  },
  {
    id: "space-invaders-arcade",
    title: "Space Invaders enters arcades",
    year: 1978,
    category: "culture",
    emoji: "👾",
    color: "lilac",
    fact: "Its aliens speed up as their numbers shrink because the arcade hardware had fewer sprites left to draw.",
  },
  {
    id: "tokyo-cellular-network",
    title: "The first cellular network opens",
    year: 1979,
    category: "tech",
    emoji: "📶",
    color: "sky",
    fact: "Japan's NTT launched the first automated commercial cellular network, initially covering metropolitan Tokyo with car phones.",
    bonusFacts: [
      "The service's first handset weighed several kilograms and was mounted inside a vehicle rather than carried in a pocket.",
    ],
  },
  {
    id: "iranian-revolution",
    title: "The Iranian Revolution",
    year: 1979,
    category: "world",
    emoji: "🇮🇷",
    color: "coral",
    fact: "A broad uprising overthrew the shah; a referendum then transformed Iran from a monarchy into an Islamic republic.",
  },
  {
    id: "cnn-launch",
    title: "CNN begins 24-hour news",
    year: 1980,
    category: "culture",
    emoji: "📺",
    color: "lilac",
    fact: "CNN launched a round-the-clock television news service when the major American networks still scheduled short daily bulletins.",
  },
  {
    id: "post-it-notes-launch",
    title: "Post-it Notes stick around",
    year: 1980,
    category: "tech",
    emoji: "🟨",
    color: "sky",
    fact: "A weak adhesive became useful when Art Fry used it to keep bookmarks from slipping out of his church hymnbook.",
    bonusFacts: [
      "Their familiar pale yellow was reportedly chosen because the neighboring laboratory happened to have scrap yellow paper.",
    ],
  },
  {
    id: "smallpox-eradicated",
    title: "Smallpox is declared eradicated",
    year: 1980,
    category: "discovery",
    emoji: "✅",
    color: "mint",
    fact: "The World Health Assembly declared smallpox gone, making it the first human disease eradicated by deliberate action.",
    bonusFacts: [
      "The last naturally occurring case was diagnosed in Somalia in 1977.",
      "Surveillance and ring vaccination—immunizing contacts around each case—were as important as mass vaccination.",
    ],
  },
  {
    id: "zimbabwe-independence",
    title: "Zimbabwe gains independence",
    year: 1980,
    category: "world",
    emoji: "🇿🇼",
    color: "coral",
    fact: "Independence ended white-minority rule in Rhodesia, with Robert Mugabe becoming the new nation's first prime minister.",
  },
  {
    id: "space-shuttle-first-flight",
    title: "The Space Shuttle first flies",
    year: 1981,
    category: "discovery",
    emoji: "🚀",
    color: "mint",
    fact: "Columbia launched like a rocket and returned to Earth on a runway, the first orbital spacecraft designed for reuse.",
    bonusFacts: [
      "It lifted off exactly 20 years after Yuri Gagarin's first human spaceflight.",
    ],
  },
  {
    id: "ibm-pc-launch",
    title: "The IBM PC launches",
    year: 1981,
    category: "tech",
    emoji: "🖥️",
    color: "sky",
    fact: "IBM built its personal computer largely from off-the-shelf parts, allowing compatible clones to reshape the market.",
    bonusFacts: [
      "Its keyboard and monitor were optional extras, while the cheapest version used a household cassette recorder for storage.",
    ],
  },
  {
    id: "first-aids-report",
    title: "The first AIDS cases are reported",
    year: 1981,
    category: "world",
    emoji: "🎗️",
    color: "coral",
    fact: "A U.S. public-health bulletin described a rare pneumonia in five young men, the first official report of the emerging epidemic.",
    bonusFacts: [
      "The condition did not receive the name AIDS until the following year, and HIV was identified later still.",
    ],
  },
  {
    id: "donkey-kong-arcade",
    title: "Donkey Kong enters arcades",
    year: 1981,
    category: "culture",
    emoji: "🦍",
    color: "lilac",
    fact: "The game introduced a carpenter called Jumpman, who would later become Nintendo's Mario.",
    bonusFacts: [
      "It was created to convert cabinets left over from Nintendo's unsuccessful arcade game Radar Scope.",
    ],
  },
  {
    id: "et-premiere",
    title: "E.T. phones home",
    year: 1982,
    category: "culture",
    emoji: "👽",
    color: "lilac",
    fact: "Steven Spielberg shot much of E.T. from a child's eye level, keeping adult faces out of frame until late in the story.",
  },
  {
    id: "smiley-emoticon-proposed",
    title: "The sideways smiley is proposed",
    year: 1982,
    category: "tech",
    emoji: "🙂",
    color: "sky",
    fact: "Computer scientist Scott Fahlman suggested :-) and :-( to mark jokes and serious posts on an online university bulletin board.",
    bonusFacts: [
      "The original message was recovered from a decades-old backup tape after a determined digital search.",
    ],
  },
  {
    id: "jarvik-artificial-heart",
    title: "The first permanent artificial heart",
    year: 1982,
    category: "discovery",
    emoji: "🫀",
    color: "mint",
    fact: "Dentist Barney Clark lived for 112 days with the air-powered Jarvik-7 replacing his diseased heart.",
  },
  {
    id: "falklands-war",
    title: "The Falklands War",
    year: 1982,
    category: "world",
    emoji: "⚓",
    color: "coral",
    fact: "Argentina and the United Kingdom fought a 74-day war over the remote South Atlantic islands.",
  },
  {
    id: "dynatac-phone-sale",
    title: "A handheld mobile phone goes on sale",
    year: 1983,
    category: "tech",
    emoji: "📱",
    color: "sky",
    fact: "Motorola's DynaTAC offered about 30 minutes of talk time, needed roughly ten hours to recharge and cost $3,995.",
    bonusFacts: [
      "Its long antenna and blocky shape later earned models like it the nickname brick phone.",
    ],
  },
  {
    id: "famicom-launch",
    title: "Nintendo launches the Famicom",
    year: 1983,
    category: "culture",
    emoji: "🎮",
    color: "lilac",
    fact: "Nintendo's red-and-white Japanese console was redesigned as the Nintendo Entertainment System for overseas markets.",
  },
  {
    id: "sally-ride-spaceflight",
    title: "Sally Ride flies in space",
    year: 1983,
    category: "discovery",
    emoji: "👩‍🚀",
    color: "mint",
    fact: "Ride became the first American woman in space—almost exactly 20 years after Valentina Tereshkova.",
  },
  {
    id: "stereolithography-invented",
    title: "3D printing is invented",
    year: 1983,
    category: "tech",
    emoji: "🖨️",
    color: "sky",
    fact: "Chuck Hull devised stereolithography, using ultraviolet light to harden liquid resin one thin layer at a time.",
    bonusFacts: [
      "He also created the widely used STL file format for describing a model's triangular surfaces.",
    ],
  },
  {
    id: "dna-fingerprinting-invented",
    title: "DNA fingerprinting is discovered",
    year: 1984,
    category: "discovery",
    emoji: "🧬",
    color: "mint",
    fact: "Alec Jeffreys noticed repeating DNA patterns varied between people, creating a powerful new form of identification.",
    bonusFacts: [
      "The technique's first legal use helped resolve an immigration dispute before it was used in a criminal investigation.",
    ],
  },
  {
    id: "first-ted-conference",
    title: "The first TED conference",
    year: 1984,
    category: "culture",
    emoji: "🎙️",
    color: "lilac",
    fact: "The original gathering connected technology, entertainment and design, including demonstrations of the compact disc and Macintosh.",
  },
  {
    id: "band-aid-single",
    title: "Band Aid records its charity single",
    year: 1984,
    category: "culture",
    emoji: "🎤",
    color: "lilac",
    fact: "Dozens of British and Irish pop stars recorded Do They Know It's Christmas? in a single day to raise famine relief funds.",
  },
  {
    id: "untethered-spacewalk",
    title: "The first untethered spacewalk",
    year: 1984,
    category: "discovery",
    emoji: "🧑‍🚀",
    color: "mint",
    fact: "Bruce McCandless flew freely from the shuttle using a nitrogen-powered backpack with no safety line attached.",
    bonusFacts: [
      "At his farthest point he was about 100 meters from Challenger, alone against the blackness of space.",
    ],
  },
  {
    id: "first-dot-com-domain",
    title: "The first .com domain is registered",
    year: 1985,
    category: "tech",
    emoji: "🌐",
    color: "sky",
    fact: "Computer manufacturer Symbolics registered symbolics.com when the commercial internet still consisted of just a handful of domains.",
    bonusFacts: [
      "Only five other .com names were registered during the rest of that year.",
    ],
  },
  {
    id: "live-aid-concert",
    title: "Live Aid fills two stadiums",
    year: 1985,
    category: "culture",
    emoji: "🎸",
    color: "lilac",
    fact: "Musicians performed in London and Philadelphia during a live global broadcast raising money for Ethiopian famine relief.",
  },
  {
    id: "ozone-hole-announced",
    title: "The Antarctic ozone hole is revealed",
    year: 1985,
    category: "discovery",
    emoji: "🕳️",
    color: "mint",
    fact: "British Antarctic Survey scientists reported a dramatic springtime loss of protective ozone over Antarctica.",
    bonusFacts: [
      "Satellite software had initially discarded similarly low ozone readings because they seemed like measurement errors.",
    ],
  },
  {
    id: "schengen-agreement-signed",
    title: "The Schengen Agreement is signed",
    year: 1985,
    category: "world",
    emoji: "🛂",
    color: "coral",
    fact: "Five European countries agreed to phase out internal border checks, signing near the tiny Luxembourg village of Schengen.",
  },
  {
    id: "people-power-philippines",
    title: "People Power fills Manila's streets",
    year: 1986,
    category: "world",
    emoji: "🇵🇭",
    color: "coral",
    fact: "Millions joined largely peaceful demonstrations that ended Ferdinand Marcos's long authoritarian rule in the Philippines.",
    bonusFacts: [
      "Civilians offered soldiers flowers and food while gathering along Epifanio de los Santos Avenue, known as EDSA.",
    ],
  },
  {
    id: "voyager-uranus-encounter",
    title: "Voyager 2 visits Uranus",
    year: 1986,
    category: "discovery",
    emoji: "🪐",
    color: "mint",
    fact: "Voyager 2 revealed new moons and dark rings during the only spacecraft encounter with Uranus to date.",
  },
  {
    id: "oprah-national-show",
    title: "The Oprah Winfrey Show goes national",
    year: 1986,
    category: "culture",
    emoji: "🎤",
    color: "lilac",
    fact: "The Chicago talk show entered national syndication and overtook long-established rivals within months.",
  },
  {
    id: "gif-format-introduced",
    title: "The GIF format is introduced",
    year: 1987,
    category: "tech",
    emoji: "💃",
    color: "sky",
    fact: "CompuServe created GIF to send compressed color images efficiently over slow dial-up connections.",
    bonusFacts: [
      "Its creator pronounced the name with a soft G, but the pronunciation argument has never stopped looping.",
    ],
  },
  {
    id: "montreal-protocol-signed",
    title: "The world protects the ozone layer",
    year: 1987,
    category: "world",
    emoji: "🌤️",
    color: "coral",
    fact: "The Montreal Protocol committed countries to phase out chemicals that were destroying stratospheric ozone.",
    bonusFacts: [
      "It later became the first UN treaty to achieve universal ratification.",
    ],
  },
  {
    id: "first-rugby-world-cup",
    title: "The first Rugby World Cup",
    year: 1987,
    category: "culture",
    emoji: "🏉",
    color: "lilac",
    fact: "New Zealand and Australia hosted the inaugural tournament, with the All Blacks winning the final in Auckland.",
  },
  {
    id: "tat8-fiber-cable",
    title: "Fiber optics cross the Atlantic",
    year: 1988,
    category: "tech",
    emoji: "〰️",
    color: "sky",
    fact: "TAT-8 became the first transatlantic fiber-optic telephone cable, multiplying call capacity and carrying early internet traffic.",
  },
  {
    id: "morris-internet-worm",
    title: "The Morris worm jolts the internet",
    year: 1988,
    category: "tech",
    emoji: "🪱",
    color: "sky",
    fact: "A self-replicating program accidentally clogged thousands of connected computers on what was still a small research network.",
    bonusFacts: [
      "Its author became the first person convicted under the U.S. Computer Fraud and Abuse Act.",
    ],
  },
  {
    id: "ipcc-established",
    title: "The global climate science panel forms",
    year: 1988,
    category: "world",
    emoji: "🌡️",
    color: "coral",
    fact: "The UN Environment Programme and World Meteorological Organization created the IPCC to assess climate research for governments.",
  },
  {
    id: "game-boy-launch",
    title: "The Game Boy launches",
    year: 1989,
    category: "culture",
    emoji: "🎮",
    color: "lilac",
    fact: "Nintendo chose long battery life and a tough monochrome screen over the color displays offered by some rivals.",
    bonusFacts: [
      "Bundling Tetris outside Japan helped the handheld reach adults who might never have bought a game console.",
    ],
  },
  {
    id: "tiananmen-protests",
    title: "The Tiananmen Square protests",
    year: 1989,
    category: "world",
    emoji: "🕯️",
    color: "coral",
    fact: "Weeks of student-led demonstrations in Beijing ended in a military crackdown whose death toll remains unknown.",
    bonusFacts: [
      "The unidentified Tank Man faced a line of armored vehicles the following day, creating one of the era's defining images.",
    ],
  },
  {
    id: "mandela-released",
    title: "Nelson Mandela walks free",
    year: 1990,
    category: "world",
    emoji: "✊",
    color: "coral",
    fact: "Mandela left prison after 27 years and immediately resumed negotiations to dismantle apartheid.",
    bonusFacts: [
      "He had spent most of his imprisonment on Robben Island, where his cell measured only a few square meters.",
    ],
  },
  {
    id: "archie-search-engine",
    title: "The first internet search engine",
    year: 1990,
    category: "tech",
    emoji: "🔎",
    color: "sky",
    fact: "Archie indexed file names on public FTP servers before the World Wide Web existed for it to search.",
    bonusFacts: [
      "Its name came from archive with the letter v removed, inspiring later tools named Veronica and Jughead.",
    ],
  },
  {
    id: "photoshop-one-release",
    title: "Photoshop 1.0 is released",
    year: 1990,
    category: "tech",
    emoji: "🖼️",
    color: "sky",
    fact: "Adobe's first Photoshop release ran only on Macintosh and shipped on a single floppy disk.",
    bonusFacts: [
      "Brothers Thomas and John Knoll developed it after Thomas wrote a program to display grayscale images on a black-and-white monitor.",
    ],
  },
  {
    id: "german-reunification",
    title: "Germany reunifies",
    year: 1990,
    category: "world",
    emoji: "🇩🇪",
    color: "coral",
    fact: "East Germany joined the Federal Republic less than eleven months after the Berlin Wall opened.",
  },
  {
    id: "linux-announced",
    title: "Linux is announced",
    year: 1991,
    category: "tech",
    emoji: "🐧",
    color: "sky",
    fact: "Student Linus Torvalds announced a free hobby operating-system kernel in an online newsgroup, expecting modest interest.",
    bonusFacts: [
      "The penguin mascot Tux arrived years later after Torvalds described his fondness for the birds.",
    ],
  },
  {
    id: "soviet-union-dissolves",
    title: "The Soviet Union dissolves",
    year: 1991,
    category: "world",
    emoji: "🗺️",
    color: "coral",
    fact: "The USSR formally ceased to exist in December, leaving 15 independent republics in its place.",
    bonusFacts: [
      "Mikhail Gorbachev resigned as president the previous evening and the Soviet flag was lowered over the Kremlin.",
    ],
  },
  {
    id: "trojan-room-webcam",
    title: "The first webcam watches a coffee pot",
    year: 1991,
    category: "tech",
    emoji: "☕",
    color: "sky",
    fact: "Cambridge researchers aimed a camera at their shared coffee pot so they could check whether it was empty from another room.",
    bonusFacts: [
      "The camera first used an internal network; it became a public web attraction in 1993.",
    ],
  },
  {
    id: "terminator-2-liquid-metal",
    title: "Terminator 2 bends movie reality",
    year: 1991,
    category: "culture",
    emoji: "🤖",
    color: "lilac",
    fact: "The T-1000's liquid-metal transformations used groundbreaking digital morphing for only a few minutes of finished screen time.",
  },
  {
    id: "first-confirmed-exoplanets",
    title: "The first exoplanets are confirmed",
    year: 1992,
    category: "discovery",
    emoji: "🪐",
    color: "mint",
    fact: "The first confirmed worlds beyond our Solar System were found orbiting a pulsar—the dense remnant of an exploded star.",
    bonusFacts: [
      "Their existence was inferred from tiny changes in the arrival time of the pulsar's clocklike radio signals.",
    ],
  },
  {
    id: "cartoon-network-launch",
    title: "Cartoon Network launches",
    year: 1992,
    category: "culture",
    emoji: "📺",
    color: "lilac",
    fact: "The channel began with a huge library of classic MGM, Warner Bros. and Hanna-Barbera animation.",
  },
  {
    id: "maastricht-treaty-signed",
    title: "The Maastricht Treaty is signed",
    year: 1992,
    category: "world",
    emoji: "🇪🇺",
    color: "coral",
    fact: "Twelve countries signed the treaty that created European Union citizenship and laid a path toward a shared currency.",
  },
  {
    id: "doom-release",
    title: "Doom is unleashed",
    year: 1993,
    category: "culture",
    emoji: "👹",
    color: "lilac",
    fact: "Doom's first episode spread as shareware, letting players copy it freely while charging for the rest.",
    bonusFacts: [
      "Its fast network battles helped popularize the term deathmatch.",
    ],
  },
  {
    id: "web-public-domain",
    title: "CERN makes the Web free",
    year: 1993,
    category: "tech",
    emoji: "🕸️",
    color: "sky",
    fact: "CERN placed World Wide Web software in the public domain, allowing anyone to build on it without paying royalties.",
    bonusFacts: [
      "The legal release arrived on 30 April, a date now celebrated by CERN as a turning point in the Web's spread.",
    ],
  },
  {
    id: "european-union-established",
    title: "The European Union begins",
    year: 1993,
    category: "world",
    emoji: "🇪🇺",
    color: "coral",
    fact: "The Maastricht Treaty took effect, formally creating the European Union from earlier economic communities.",
  },
  {
    id: "amazon-founded",
    title: "Amazon is founded",
    year: 1994,
    category: "tech",
    emoji: "📦",
    color: "sky",
    fact: "Jeff Bezos initially called the online bookstore Cadabra before choosing a name suggesting vast scale.",
    bonusFacts: [
      "Its first sale the following year was a book about fluid concepts and creative analogies, not a bestseller.",
    ],
  },
  {
    id: "friends-premiere",
    title: "Friends premieres",
    year: 1994,
    category: "culture",
    emoji: "🛋️",
    color: "lilac",
    fact: "The now-famous orange Central Perk couch was reportedly found in storage at the Warner Bros. studio.",
  },
  {
    id: "qr-code-invented",
    title: "The QR code is invented",
    year: 1994,
    category: "tech",
    emoji: "🔳",
    color: "sky",
    fact: "A Denso Wave team created the square code to track automotive parts quickly from any scanning angle.",
    bonusFacts: [
      "Its three large corner squares help a reader recognize the code's position and orientation almost instantly.",
    ],
  },
  {
    id: "channel-tunnel-opens",
    title: "The Channel Tunnel opens",
    year: 1994,
    category: "tech",
    emoji: "🚆",
    color: "sky",
    fact: "The rail tunnel restored a fixed land connection between Britain and continental Europe for the first time since the Ice Age.",
    bonusFacts: [
      "Its undersea section runs for nearly 38 kilometers, longer than that of any other tunnel when it opened.",
    ],
  },
  {
    id: "south-africa-democratic-election",
    title: "South Africa's first all-race election",
    year: 1994,
    category: "world",
    emoji: "🗳️",
    color: "coral",
    fact: "Millions voted for the first time in lines that stretched for kilometers, electing Nelson Mandela president.",
    bonusFacts: [
      "The election ran across three days so officials could accommodate the enormous number of new voters.",
    ],
  },
  {
    id: "ebay-founded",
    title: "eBay begins as AuctionWeb",
    year: 1995,
    category: "tech",
    emoji: "🔨",
    color: "sky",
    fact: "The site's first sale was a broken laser pointer bought for $14.83 by someone who collected broken pointers.",
    bonusFacts: [
      "The charming story that it was built for the founder's fiancée to trade Pez dispensers was later revealed as publicity lore.",
    ],
  },
  {
    id: "javascript-created",
    title: "JavaScript is created",
    year: 1995,
    category: "tech",
    emoji: "📜",
    color: "sky",
    fact: "Brendan Eich built the first version at Netscape in about ten days so web pages could respond to users.",
    bonusFacts: [
      "It was briefly named Mocha and then LiveScript before marketing tied its name to the unrelated Java language.",
    ],
  },
  {
    id: "51-pegasi-b-discovered",
    title: "A planet is found around a Sun-like star",
    year: 1995,
    category: "discovery",
    emoji: "🌌",
    color: "mint",
    fact: "51 Pegasi b shocked astronomers by being a Jupiter-sized world that circles its star in only four days.",
    bonusFacts: [
      "The discovery created the category hot Jupiter and showed that planetary systems could look nothing like ours.",
    ],
  },
  {
    id: "windows-95-launch",
    title: "Windows 95 introduces Start",
    year: 1995,
    category: "tech",
    emoji: "🪟",
    color: "sky",
    fact: "Midnight store openings greeted an operating system that introduced the Start button and taskbar to millions.",
  },
  {
    id: "dvd-standard-agreed",
    title: "The DVD format is agreed",
    year: 1995,
    category: "tech",
    emoji: "💿",
    color: "sky",
    fact: "Rival electronics groups unified their competing high-density disc proposals, avoiding another VHS-versus-Betamax battle.",
  },
  {
    id: "pokemon-red-green",
    title: "Pokémon begins",
    year: 1996,
    category: "culture",
    emoji: "⚡",
    color: "lilac",
    fact: "Pokémon Red and Green debuted in Japan, built around trading creatures through the Game Boy's Link Cable.",
    bonusFacts: [
      "Creator Satoshi Tajiri drew on his childhood hobby of collecting insects in suburban Tokyo.",
    ],
  },
  {
    id: "hotmail-launch",
    title: "Hotmail launches",
    year: 1996,
    category: "tech",
    emoji: "📧",
    color: "sky",
    fact: "Web-based inboxes freed users from email tied to a workplace or internet provider's computer.",
    bonusFacts: [
      "The original stylized name HoTMaiL hid the letters HTML, the language of web pages.",
    ],
  },
  {
    id: "tamagotchi-launch",
    title: "Tamagotchi hatches",
    year: 1996,
    category: "culture",
    emoji: "🥚",
    color: "lilac",
    fact: "Bandai's pocket pet demanded feeding, cleaning and attention—and could die if its owner neglected it.",
    bonusFacts: [
      "Its name blends the Japanese word for egg with the English word watch.",
    ],
  },
  {
    id: "deep-blue-kasparov-match",
    title: "A computer defeats the chess champion",
    year: 1997,
    category: "tech",
    emoji: "♟️",
    color: "sky",
    fact: "IBM's Deep Blue beat Garry Kasparov in a six-game match, the first machine to defeat a reigning world champion under standard conditions.",
    bonusFacts: [
      "Deep Blue could evaluate roughly 200 million chess positions every second.",
    ],
  },
  {
    id: "wifi-standard-published",
    title: "The first Wi-Fi standard appears",
    year: 1997,
    category: "tech",
    emoji: "📶",
    color: "sky",
    fact: "The original IEEE 802.11 wireless-network standard topped out at just two megabits per second.",
    bonusFacts: [
      "The consumer-friendly name Wi-Fi was introduced two years later; it was branding, not short for wireless fidelity.",
    ],
  },
  {
    id: "mars-pathfinder-landing",
    title: "The first Mars rover rolls",
    year: 1997,
    category: "discovery",
    emoji: "🛞",
    color: "mint",
    fact: "The microwave-oven-sized Sojourner rover explored Mars after Pathfinder's lander bounced to safety inside giant airbags.",
    bonusFacts: [
      "Its name honored Sojourner Truth and was selected through a student essay contest.",
    ],
  },
  {
    id: "iss-assembly-begins",
    title: "Space-station assembly begins",
    year: 1998,
    category: "discovery",
    emoji: "🧩",
    color: "mint",
    fact: "The Russian-built Zarya module launched first, followed weeks later by the American Unity module.",
    bonusFacts: [
      "The station eventually became one of the largest international engineering projects ever attempted.",
    ],
  },
  {
    id: "good-friday-agreement",
    title: "The Good Friday Agreement",
    year: 1998,
    category: "world",
    emoji: "🕊️",
    color: "coral",
    fact: "The accord created power-sharing institutions and helped bring Northern Ireland's three-decade Troubles largely to an end.",
    bonusFacts: [
      "Voters approved it in separate referendums held on both sides of the Irish border.",
    ],
  },
  {
    id: "viagra-approved",
    title: "Viagra is approved",
    year: 1998,
    category: "discovery",
    emoji: "💊",
    color: "mint",
    fact: "Sildenafil was studied for chest pain before trial participants reported a very different and commercially useful effect.",
  },
  {
    id: "bluetooth-specification",
    title: "Bluetooth gets its first specification",
    year: 1999,
    category: "tech",
    emoji: "🅱️",
    color: "sky",
    fact: "The short-range wireless standard was named for Harald Bluetooth, a Viking king associated with uniting Denmark.",
    bonusFacts: [
      "Its angular logo combines the runic letters for Harald's initials.",
    ],
  },
  {
    id: "napster-launch",
    title: "Napster launches",
    year: 1999,
    category: "culture",
    emoji: "🎵",
    color: "lilac",
    fact: "The service made finding and sharing MP3 files startlingly easy, then collided with musicians and record labels in court.",
    bonusFacts: [
      "Metallica sued after an unfinished song leaked onto the network before its official release.",
    ],
  },
  {
    id: "jphone-camera-phone",
    title: "A mass-market camera phone goes on sale",
    year: 2000,
    category: "tech",
    emoji: "📸",
    color: "sky",
    fact: "Sharp's J-SH04 brought network photo messaging to mass-market phones in Japan after earlier camera-equipped models.",
    bonusFacts: [
      "Its camera captured roughly 0.1 megapixels and faced backward, years before the selfie camera.",
    ],
  },
  {
    id: "gps-selective-availability-off",
    title: "Civilian GPS suddenly gets sharper",
    year: 2000,
    category: "tech",
    emoji: "📍",
    color: "sky",
    fact: "The U.S. switched off intentional signal degradation, improving everyday GPS accuracy overnight from roughly 100 meters to about 20.",
    bonusFacts: [
      "The change helped make turn-by-turn navigation and precise location services practical for ordinary users.",
    ],
  },
  {
    id: "playstation-2-launch",
    title: "The PlayStation 2 launches",
    year: 2000,
    category: "culture",
    emoji: "🎮",
    color: "lilac",
    fact: "Its ability to play DVD movies gave many households a game console and their first DVD player in one box.",
    bonusFacts: [
      "It became the best-selling video-game console ever, remaining in production for more than a decade.",
    ],
  },
  {
    id: "cathy-freeman-sydney-gold",
    title: "Cathy Freeman wins in Sydney",
    year: 2000,
    category: "culture",
    emoji: "🔥",
    color: "lilac",
    fact: "After lighting the Olympic cauldron, Freeman won the 400 meters before a roaring home crowd in her silver hooded suit.",
  },
  {
    id: "segway-unveiled",
    title: "The Segway is unveiled",
    year: 2001,
    category: "tech",
    emoji: "🛴",
    color: "sky",
    fact: "The self-balancing scooter used gyroscopes to stay upright and was introduced amid predictions it would redesign cities.",
    bonusFacts: [
      "Its name evokes segue—a smooth transition—rather than being an acronym.",
    ],
  },
  {
    id: "shrek-premiere",
    title: "Shrek premieres",
    year: 2001,
    category: "culture",
    emoji: "🧅",
    color: "lilac",
    fact: "The fairy-tale parody became the first winner of the Academy Award for Best Animated Feature.",
  },
  {
    id: "first-space-tourist",
    title: "The first space tourist reaches orbit",
    year: 2001,
    category: "discovery",
    emoji: "🧳",
    color: "mint",
    fact: "Engineer Dennis Tito paid for a Russian Soyuz flight and spent nearly eight days aboard the International Space Station.",
    bonusFacts: [
      "NASA initially objected to the visit, so Tito trained extensively in Russia before the mission.",
    ],
  },
  {
    id: "september-11-attacks",
    title: "The September 11 attacks",
    year: 2001,
    category: "world",
    emoji: "🕯️",
    color: "coral",
    fact: "Al-Qaeda hijackers used four passenger planes in attacks that killed nearly 3,000 people and reshaped global security.",
  },
  {
    id: "euro-cash-circulation",
    title: "Euro cash enters circulation",
    year: 2002,
    category: "world",
    emoji: "💶",
    color: "coral",
    fact: "Notes and coins arrived simultaneously in 12 countries, replacing currencies such as the franc, lira and deutsche mark.",
    bonusFacts: [
      "The euro had already existed for three years as an electronic accounting currency before people could hold it.",
    ],
  },
  {
    id: "american-idol-premiere",
    title: "American Idol premieres",
    year: 2002,
    category: "culture",
    emoji: "🎤",
    color: "lilac",
    fact: "Kelly Clarkson won the first season of the singing competition, adapted from Britain's Pop Idol.",
  },
  {
    id: "sars-outbreak-begins",
    title: "The SARS outbreak begins",
    year: 2002,
    category: "world",
    emoji: "😷",
    color: "coral",
    fact: "The first known cases appeared in Guangdong before international air travel carried the new coronavirus across borders.",
    bonusFacts: [
      "Unprecedented international laboratory cooperation identified the virus within weeks in 2003.",
    ],
  },
  {
    id: "roomba-launch",
    title: "The Roomba starts vacuuming",
    year: 2002,
    category: "tech",
    emoji: "🤖",
    color: "sky",
    fact: "The disc-shaped robot cleaned by repeatedly changing direction, using simple behaviors instead of mapping the whole room.",
    bonusFacts: [
      "Infrared cliff sensors kept it from driving down stairs, while a bumper told it when to turn around.",
    ],
  },
  {
    id: "skype-launch",
    title: "Skype launches",
    year: 2003,
    category: "tech",
    emoji: "📞",
    color: "sky",
    fact: "Built largely by Estonian developers, Skype made free computer-to-computer voice calls feel ordinary across long distances.",
    bonusFacts: [
      "Its working name Sky peer-to-peer was shortened to Skyper and then Skype when the matching domain was unavailable.",
    ],
  },
  {
    id: "finding-nemo-premiere",
    title: "Finding Nemo premieres",
    year: 2003,
    category: "culture",
    emoji: "🐠",
    color: "lilac",
    fact: "Pixar animators took scuba lessons to study light and movement underwater before building the Great Barrier Reef digitally.",
    bonusFacts: [
      "Real clownfish can change sex; after losing the dominant female, the largest male typically becomes female.",
    ],
  },
  {
    id: "spirit-opportunity-land",
    title: "Twin rovers land on Mars",
    year: 2004,
    category: "discovery",
    emoji: "🤖",
    color: "mint",
    fact: "Spirit and Opportunity arrived three weeks apart to search Martian rocks for evidence of past water.",
    bonusFacts: [
      "Opportunity was designed for 90 days but kept exploring for almost 15 years.",
    ],
  },
  {
    id: "spaceshipone-crewed-flight",
    title: "A private craft reaches space",
    year: 2004,
    category: "discovery",
    emoji: "🚀",
    color: "mint",
    fact: "SpaceShipOne became the first privately funded crewed vehicle to cross the recognized boundary of space.",
    bonusFacts: [
      "It later won the Ansari X Prize by repeating the feat twice within two weeks using the same vehicle.",
    ],
  },
  {
    id: "gmail-launch",
    title: "Gmail launches",
    year: 2004,
    category: "tech",
    emoji: "📬",
    color: "sky",
    fact: "Its one-gigabyte inbox was so much larger than rivals that the April Fools' Day announcement looked like a joke.",
  },
  {
    id: "indian-ocean-tsunami",
    title: "The Indian Ocean tsunami",
    year: 2004,
    category: "world",
    emoji: "🌊",
    color: "coral",
    fact: "A magnitude 9.1 undersea earthquake sent devastating waves across coastlines from Indonesia to East Africa.",
    bonusFacts: [
      "The disaster accelerated construction of an Indian Ocean tsunami-warning system that had not previously existed.",
    ],
  },
  {
    id: "nintendo-ds-launch",
    title: "The Nintendo DS launches",
    year: 2004,
    category: "culture",
    emoji: "🖊️",
    color: "lilac",
    fact: "Its two screens, stylus and microphone encouraged games built around drawing, speaking and closing the device itself.",
  },
  {
    id: "first-partial-face-transplant",
    title: "The first partial face transplant",
    year: 2005,
    category: "discovery",
    emoji: "🏥",
    color: "mint",
    fact: "A French surgical team transplanted a donor's nose, lips and chin to patient Isabelle Dinoire.",
  },
  {
    id: "kyoto-protocol-force",
    title: "The Kyoto climate treaty takes effect",
    year: 2005,
    category: "world",
    emoji: "🌡️",
    color: "coral",
    fact: "The agreement created binding greenhouse-gas targets for participating industrialized countries after Russia's ratification crossed the threshold.",
  },
  {
    id: "google-maps-launch",
    title: "Google Maps launches",
    year: 2005,
    category: "tech",
    emoji: "🗺️",
    color: "sky",
    fact: "Its draggable browser map felt remarkably fluid because users could move around without reloading an entire page.",
  },
  {
    id: "wii-launch",
    title: "The Wii launches",
    year: 2006,
    category: "culture",
    emoji: "🎳",
    color: "lilac",
    fact: "Nintendo's motion-sensing remote turned living rooms into bowling alleys and brought non-gamers into console play.",
    bonusFacts: [
      "The name Wii was chosen to sound like we, emphasizing people playing together.",
    ],
  },
  {
    id: "montenegro-independence",
    title: "Montenegro becomes independent",
    year: 2006,
    category: "world",
    emoji: "🇲🇪",
    color: "coral",
    fact: "A referendum passed with 55.5% support—just above the 55% threshold agreed for independence from Serbia.",
  },
  {
    id: "pluto-dwarf-planet",
    title: "Pluto becomes a dwarf planet",
    year: 2006,
    category: "discovery",
    emoji: "🪐",
    color: "mint",
    fact: "Astronomers adopted a new planet definition requiring an object to clear its orbital neighborhood, which Pluto does not.",
    bonusFacts: [
      "New Horizons was already flying toward Pluto when the vote changed its official category.",
    ],
  },
  {
    id: "portal-game-release",
    title: "Portal opens a new kind of puzzle",
    year: 2007,
    category: "culture",
    emoji: "🌀",
    color: "lilac",
    fact: "Valve hired students behind a small game called Narbacular Drop and turned its linked-doorway idea into Portal.",
    bonusFacts: [
      "The end-credit song Still Alive was performed in character by the game's politely murderous computer, GLaDOS.",
    ],
  },
  {
    id: "spotify-launch",
    title: "Spotify starts streaming",
    year: 2008,
    category: "culture",
    emoji: "🎧",
    color: "lilac",
    fact: "The Swedish service offered instant licensed music as a convenient alternative to piracy and downloading files.",
  },
  {
    id: "android-first-phone",
    title: "The first Android phone goes on sale",
    year: 2008,
    category: "tech",
    emoji: "📱",
    color: "sky",
    fact: "The HTC Dream, sold as the T-Mobile G1, had a slide-out keyboard, trackball and an early app marketplace.",
  },
  {
    id: "kepler-telescope-launch",
    title: "Kepler begins hunting planets",
    year: 2009,
    category: "discovery",
    emoji: "🔭",
    color: "mint",
    fact: "The space telescope watched about 150,000 stars for tiny repeated dimmings caused by planets crossing in front.",
    bonusFacts: [
      "Its discoveries showed that planets are common in our galaxy rather than rare exceptions.",
    ],
  },
  {
    id: "whatsapp-founded",
    title: "WhatsApp is founded",
    year: 2009,
    category: "tech",
    emoji: "💬",
    color: "sky",
    fact: "It began as an app for posting status updates; phone notifications soon transformed it into a messaging service.",
  },
  {
    id: "bitcoin-pizza-purchase",
    title: "Bitcoin buys two pizzas",
    year: 2010,
    category: "tech",
    emoji: "🍕",
    color: "sky",
    fact: "A programmer paid 10,000 bitcoin for two pizzas in the first widely documented purchase of physical goods with the currency.",
    bonusFacts: [
      "He did not pay the restaurant directly; another forum user accepted the bitcoin and ordered the pizzas for him.",
    ],
  },
  {
    id: "burj-khalifa-opens",
    title: "The Burj Khalifa opens",
    year: 2010,
    category: "culture",
    emoji: "🏙️",
    color: "lilac",
    fact: "Dubai's 828-meter tower opened as the tallest structure humans had ever built.",
    bonusFacts: [
      "Its Y-shaped floor plan, inspired partly by a desert flower, helps brace the building against twisting winds.",
    ],
  },
  {
    id: "synthetic-genome-cell",
    title: "A synthetic genome runs a cell",
    year: 2010,
    category: "discovery",
    emoji: "🧫",
    color: "mint",
    fact: "Researchers installed laboratory-built DNA into a cell whose own genome had been removed, and the synthetic instructions took control.",
    bonusFacts: [
      "The team embedded coded watermarks, including names and quotations, inside the manufactured genome.",
    ],
  },
  {
    id: "arab-spring-begins",
    title: "The Arab Spring begins",
    year: 2010,
    category: "world",
    emoji: "🌍",
    color: "coral",
    fact: "Protests erupted in Tunisia after street vendor Mohamed Bouazizi's self-immolation and soon spread across the Arab world.",
  },
  {
    id: "twitch-launch",
    title: "Twitch starts streaming games",
    year: 2011,
    category: "tech",
    emoji: "🟣",
    color: "sky",
    fact: "The gaming section of general livestreaming site Justin.tv became popular enough to spin out as Twitch.",
    bonusFacts: [
      "Amazon bought the service three years later for nearly a billion dollars.",
    ],
  },
  {
    id: "game-of-thrones-premiere",
    title: "Game of Thrones premieres",
    year: 2011,
    category: "culture",
    emoji: "🐉",
    color: "lilac",
    fact: "HBO reshot most of an unseen pilot and recast major roles before the fantasy series finally reached television.",
  },
  {
    id: "south-sudan-independence",
    title: "South Sudan becomes independent",
    year: 2011,
    category: "world",
    emoji: "🇸🇸",
    color: "coral",
    fact: "After decades of civil war, nearly 99% of referendum voters chose separation from Sudan, creating the world's newest country.",
  },
  {
    id: "fukushima-disaster",
    title: "The Fukushima nuclear disaster",
    year: 2011,
    category: "world",
    emoji: "☢️",
    color: "coral",
    fact: "A massive earthquake and tsunami disabled cooling systems, leading to meltdowns in three reactor cores.",
    bonusFacts: [
      "The earthquake automatically shut the reactors, but flooding overwhelmed backup generators needed to remove lingering heat.",
    ],
  },
  {
    id: "raspberry-pi-sale",
    title: "The Raspberry Pi goes on sale",
    year: 2012,
    category: "tech",
    emoji: "🥧",
    color: "sky",
    fact: "The credit-card-sized $35 computer was built to make programming and hardware experiments affordable to students.",
    bonusFacts: [
      "Launch-day demand overwhelmed its distributors before most buyers could complete an order.",
    ],
  },
  {
    id: "red-bull-stratos-jump",
    title: "A jump from the stratosphere",
    year: 2012,
    category: "culture",
    emoji: "🪂",
    color: "lilac",
    fact: "He stepped from a balloon capsule about 39 kilometers up and became the first person to break the sound barrier in freefall.",
    bonusFacts: [
      "Millions watched live online as his freefall lasted a little over four minutes.",
    ],
  },
  {
    id: "curiosity-mars-landing",
    title: "Curiosity's sky crane lands on Mars",
    year: 2012,
    category: "discovery",
    emoji: "🔴",
    color: "mint",
    fact: "A rocket-powered sky crane hovered above Mars and lowered the one-ton rover to the ground on cables.",
    bonusFacts: [
      "NASA called the complex autonomous descent seven minutes of terror because radio signals could not arrive in time to help.",
    ],
  },
  {
    id: "vine-launch",
    title: "Vine starts six-second looping",
    year: 2013,
    category: "tech",
    emoji: "🎞️",
    color: "sky",
    fact: "The app's strict six-second loops produced a new language of rapid jokes, edits and internet catchphrases.",
    bonusFacts: [
      "Twitter acquired Vine before the public had even downloaded it.",
    ],
  },
  {
    id: "crispr-human-cell-editing",
    title: "CRISPR edits human cells",
    year: 2013,
    category: "discovery",
    emoji: "✂️",
    color: "mint",
    fact: "Separate research teams showed that the bacterial CRISPR-Cas9 system could be programmed to alter DNA inside human cells.",
    bonusFacts: [
      "The core tool had been demonstrated in a test tube only the previous year.",
    ],
  },
  {
    id: "lab-grown-burger",
    title: "The first lab-grown burger is tasted",
    year: 2013,
    category: "discovery",
    emoji: "🍔",
    color: "mint",
    fact: "A London tasting served a burger assembled from thousands of strands of beef muscle grown from cow cells.",
    bonusFacts: [
      "The prototype cost roughly €250,000 and needed beetroot juice and saffron for color.",
    ],
  },
  {
    id: "snowden-surveillance-disclosures",
    title: "The Snowden surveillance disclosures",
    year: 2013,
    category: "world",
    emoji: "👁️",
    color: "coral",
    fact: "Leaked documents revealed the enormous scale of secret digital surveillance programs run by the United States and partners.",
  },
  {
    id: "apple-pay-launch",
    title: "Apple Pay launches",
    year: 2014,
    category: "tech",
    emoji: "📲",
    color: "sky",
    fact: "The system let phone owners pay at a terminal while substituting a device-specific token for their actual card number.",
  },
  {
    id: "ice-bucket-challenge",
    title: "The Ice Bucket Challenge goes viral",
    year: 2014,
    category: "culture",
    emoji: "🧊",
    color: "lilac",
    fact: "People poured icy water over themselves, nominated friends and raised more than $100 million for ALS research in weeks.",
    bonusFacts: [
      "The campaign generated millions of videos and helped fund research that identified new genetic leads for the disease.",
    ],
  },
  {
    id: "malala-nobel-prize",
    title: "Malala wins the Nobel Peace Prize",
    year: 2014,
    category: "culture",
    emoji: "📚",
    color: "lilac",
    fact: "At 17, education activist Malala Yousafzai became the youngest Nobel laureate in history.",
    bonusFacts: [
      "She shared the prize with Indian children's-rights campaigner Kailash Satyarthi.",
    ],
  },
  {
    id: "falcon-9-first-landing",
    title: "An orbital rocket booster lands upright",
    year: 2015,
    category: "tech",
    emoji: "🚀",
    color: "sky",
    fact: "A Falcon 9 first stage returned to Cape Canaveral and landed vertically after launching 11 satellites toward orbit.",
    bonusFacts: [
      "A suborbital New Shepard booster had landed weeks earlier; Falcon 9 returned from a much faster orbital-class mission.",
    ],
  },
  {
    id: "emoji-skin-tones",
    title: "Emoji gain skin-tone options",
    year: 2015,
    category: "culture",
    emoji: "👋🏽",
    color: "lilac",
    fact: "Unicode added human emoji modifiers based on the Fitzpatrick skin-type scale, greatly expanding digital self-representation.",
  },
  {
    id: "new-horizons-pluto-flyby",
    title: "Pluto gets its first close-up",
    year: 2015,
    category: "discovery",
    emoji: "🤍",
    color: "mint",
    fact: "New Horizons revealed icy mountains and a giant heart-shaped plain during humanity's first Pluto flyby.",
    bonusFacts: [
      "The probe collected data faster than it could transmit it; sending everything home took about 15 months.",
    ],
  },
  {
    id: "paris-climate-agreement",
    title: "The Paris climate agreement",
    year: 2015,
    category: "world",
    emoji: "🌍",
    color: "coral",
    fact: "Nearly every country agreed to submit and strengthen plans for limiting global warming, aiming well below 2°C.",
  },
  {
    id: "alphago-lee-sedol",
    title: "AlphaGo defeats Lee Sedol",
    year: 2016,
    category: "tech",
    emoji: "⚫",
    color: "sky",
    fact: "DeepMind's program beat one of the world's strongest Go players 4–1 in a game once thought too intuitive for machines.",
    bonusFacts: [
      "AlphaGo's unexpected Move 37 in game two was first called a mistake, then recognized as a brilliant strategic idea.",
    ],
  },
  {
    id: "solar-impulse-circumnavigation",
    title: "A solar plane circles the world",
    year: 2016,
    category: "discovery",
    emoji: "☀️",
    color: "mint",
    fact: "Solar Impulse 2 completed a 17-leg circumnavigation without using a drop of fuel.",
    bonusFacts: [
      "Its wingspan exceeded a Boeing 747's, yet the ultralight plane carried only one pilot at a time.",
    ],
  },
  {
    id: "tiktok-international-launch",
    title: "TikTok launches internationally",
    year: 2017,
    category: "tech",
    emoji: "🎶",
    color: "sky",
    fact: "ByteDance released TikTok outside China, then folded lip-sync app Musical.ly into it the following year.",
    bonusFacts: [
      "A sister app called Douyin had launched inside China in 2016 and remains a separate service.",
    ],
  },
  {
    id: "nintendo-switch-launch",
    title: "The Nintendo Switch launches",
    year: 2017,
    category: "culture",
    emoji: "🎮",
    color: "lilac",
    fact: "The console could move from a television dock to handheld play without stopping the game.",
  },
  {
    id: "metoo-goes-global",
    title: "#MeToo goes global",
    year: 2017,
    category: "culture",
    emoji: "#️⃣",
    color: "lilac",
    fact: "Millions used the hashtag to share experiences of sexual harassment and abuse after reports about powerful entertainment figures.",
    bonusFacts: [
      "Activist Tarana Burke had begun using the phrase Me Too for survivor solidarity more than a decade earlier.",
    ],
  },
  {
    id: "bts-billboard-number-one",
    title: "BTS tops the U.S. album chart",
    year: 2018,
    category: "culture",
    emoji: "💜",
    color: "lilac",
    fact: "Love Yourself: Tear made BTS the first Korean act to reach number one on the Billboard 200.",
  },
  {
    id: "thai-cave-rescue",
    title: "The Thai cave rescue",
    year: 2018,
    category: "world",
    emoji: "🧗",
    color: "coral",
    fact: "An international team brought 12 young footballers and their coach out after 18 days trapped by floodwater.",
    bonusFacts: [
      "For the dangerous underwater journey, each child was sedated and guided through narrow flooded passages by expert divers.",
    ],
  },
  {
    id: "parasite-palme-dor",
    title: "Parasite wins the Palme d'Or",
    year: 2019,
    category: "culture",
    emoji: "🏆",
    color: "lilac",
    fact: "Bong Joon Ho's class satire became the first Korean film to win the Cannes Film Festival's top prize.",
    bonusFacts: [
      "The following year it became the first non-English-language film to win the Academy Award for Best Picture.",
    ],
  },
  {
    id: "alphafold2-breakthrough",
    title: "AlphaFold solves a protein-folding test",
    year: 2020,
    category: "tech",
    emoji: "🧬",
    color: "sky",
    fact: "AlphaFold 2 predicted many protein shapes with accuracy close to laboratory methods in a landmark blind competition.",
    bonusFacts: [
      "The structure of a protein helps determine what it does, but experimentally finding one can take months or years.",
      "DeepMind later helped release predictions for hundreds of millions of proteins in a free database.",
    ],
  },
  {
    id: "covid-pandemic-declared",
    title: "COVID-19 is declared a pandemic",
    year: 2020,
    category: "world",
    emoji: "🌐",
    color: "coral",
    fact: "The World Health Organization used the pandemic label on 11 March as the new coronavirus spread across continents.",
    bonusFacts: [
      "WHO stressed that the term described the disease's global spread, not a change in the danger posed by the virus that day.",
    ],
  },
  {
    id: "wordle-released",
    title: "Wordle is released",
    year: 2021,
    category: "culture",
    emoji: "🟩",
    color: "lilac",
    fact: "Josh Wardle made the one-puzzle-a-day word game for his partner, then opened it to the public after family members became hooked.",
    bonusFacts: [
      "Its name is a pun on Wardle's surname, and the original game contained no ads or push notifications.",
    ],
  },
  {
    id: "beeple-nft-auction",
    title: "A digital collage sells for $69 million",
    year: 2021,
    category: "culture",
    emoji: "🖼️",
    color: "lilac",
    fact: "Christie's sold Beeple's Everydays collage with an NFT for $69.3 million, jolting digital art into auction headlines.",
    bonusFacts: [
      "The artwork combines one image made on each of 5,000 consecutive days.",
    ],
  },
  {
    id: "ingenuity-mars-flight",
    title: "A helicopter flies on Mars",
    year: 2021,
    category: "discovery",
    emoji: "🚁",
    color: "mint",
    fact: "Ingenuity made the first controlled powered flight on another world, rising three meters in the thin Martian air.",
    bonusFacts: [
      "Designed for five test flights, the tiny helicopter eventually completed 72.",
      "Its rotors spun far faster than an Earth helicopter's because Mars has less than 1% of Earth's sea-level air density.",
    ],
  },
  {
    id: "ever-given-suez-blockage",
    title: "The Ever Given blocks the Suez Canal",
    year: 2021,
    category: "world",
    emoji: "🚢",
    color: "coral",
    fact: "The skyscraper-long container ship wedged sideways for six days, holding up hundreds of vessels on a major trade route.",
    bonusFacts: [
      "A photo of one small excavator digging beside the enormous bow became an instant symbol of the rescue effort's scale.",
    ],
  },
  {
    id: "dalle2-unveiled",
    title: "DALL·E 2 turns words into images",
    year: 2022,
    category: "tech",
    emoji: "🎨",
    color: "sky",
    fact: "The AI system generated detailed original pictures from written prompts and could edit objects into existing scenes.",
    bonusFacts: [
      "Its name combines surrealist artist Salvador Dalí with Pixar's robot WALL-E.",
    ],
  },
  {
    id: "russia-invades-ukraine",
    title: "Russia's full-scale invasion of Ukraine",
    year: 2022,
    category: "world",
    emoji: "🇺🇦",
    color: "coral",
    fact: "Russian forces attacked from several directions on 24 February, sharply escalating a war that had begun in 2014.",
  },
  {
    id: "qatar-world-cup",
    title: "The World Cup comes to the Arab world",
    year: 2022,
    category: "culture",
    emoji: "⚽",
    color: "lilac",
    fact: "Qatar hosted the first men's football World Cup in the Middle East, moving the tournament to November and December to avoid summer heat.",
    bonusFacts: [
      "Argentina won a dramatic final on penalties, giving Lionel Messi his first World Cup title.",
    ],
  },
  {
    id: "chandrayaan3-moon-landing",
    title: "India lands near the Moon's south pole",
    year: 2023,
    category: "discovery",
    emoji: "🇮🇳",
    color: "mint",
    fact: "Chandrayaan-3 made India the fourth nation to soft-land on the Moon and the first to do so in the southern polar region.",
    bonusFacts: [
      "The landing point was named Shiv Shakti Point, and the small Pragyan rover explored nearby soil.",
    ],
  },
  {
    id: "first-crispr-therapy-approved",
    title: "The first CRISPR treatment is approved",
    year: 2023,
    category: "discovery",
    emoji: "🧬",
    color: "mint",
    fact: "UK regulators approved Casgevy, the first medicine to treat patients using the CRISPR gene-editing tool.",
    bonusFacts: [
      "The therapy edits a patient's own blood stem cells to restart production of fetal hemoglobin.",
      "It was approved for sickle cell disease and beta thalassemia; U.S. approval followed weeks later for sickle cell disease.",
    ],
  },
  {
    id: "barbenheimer-weekend",
    title: "Barbenheimer takes over cinemas",
    year: 2023,
    category: "culture",
    emoji: "🎬",
    color: "lilac",
    fact: "Fans turned the same-day U.S. release of Barbie and Oppenheimer into an unlikely pink-and-black double-feature event.",
    bonusFacts: [
      "The Barbenheimer name and most of its marketing came from audiences, memes and cinemas rather than either studio.",
    ],
  },
  {
    id: "covid-emergency-ends",
    title: "The COVID global emergency ends",
    year: 2023,
    category: "world",
    emoji: "🏥",
    color: "coral",
    fact: "WHO ended COVID-19's Public Health Emergency of International Concern while warning the virus remained an ongoing threat.",
  },
  {
    id: "starship-booster-catch",
    title: "A launch tower catches a rocket",
    year: 2024,
    category: "tech",
    emoji: "🥢",
    color: "sky",
    fact: "SpaceX's enormous Super Heavy booster returned from flight and settled between mechanical arms nicknamed chopsticks.",
    bonusFacts: [
      "The catch happened about seven minutes after launch and avoided both landing legs and a separate landing pad.",
    ],
  },
  {
    id: "change6-farside-samples",
    title: "Moon rocks return from the far side",
    year: 2024,
    category: "discovery",
    emoji: "🌑",
    color: "mint",
    fact: "China's Chang'e 6 brought back the first samples ever collected from the Moon's far side.",
    bonusFacts: [
      "Because the far side never faces Earth, the mission needed a relay satellite to communicate with its lander.",
      "The capsule returned nearly two kilograms of lunar material from the vast South Pole–Aitken basin.",
    ],
  },
  {
    id: "paris-olympics-opening",
    title: "The Paris Olympics open on the Seine",
    year: 2024,
    category: "culture",
    emoji: "🛶",
    color: "lilac",
    fact: "Athletes traveled by boat through central Paris in the first Summer Olympics opening ceremony held outside a stadium.",
    bonusFacts: [
      "The cauldron appeared beneath a balloon in the Tuileries Garden, echoing the city's pioneering hydrogen-balloon flights.",
    ],
  },
  {
    id: "eu-ai-act-force",
    title: "The EU AI Act takes effect",
    year: 2024,
    category: "world",
    emoji: "🤖",
    color: "coral",
    fact: "The European Union's risk-based AI law became the world's first comprehensive legal framework dedicated to artificial intelligence.",
    bonusFacts: [
      "Its rules phase in over several years, with the strictest obligations aimed at uses considered high-risk.",
    ],
  },
  {
    id: "moon-gnss-navigation-fix",
    title: "GPS signals work on the Moon",
    year: 2025,
    category: "tech",
    emoji: "🛰️",
    color: "sky",
    fact: "The LuGRE receiver aboard Blue Ghost achieved the first navigation fix on the lunar surface using GPS and Galileo signals from Earth.",
    bonusFacts: [
      "It picked up the faint side lobes of navigation signals roughly 360,000 kilometers beyond their everyday users.",
    ],
  },
  {
    id: "expo-osaka-opens",
    title: "Expo 2025 Osaka opens",
    year: 2025,
    category: "culture",
    emoji: "🎌",
    color: "lilac",
    fact: "Countries gathered on Osaka's Yumeshima island beneath the Grand Ring, a circular timber structure two kilometers around.",
    bonusFacts: [
      "The ring was recognized as the world's largest wooden architectural structure.",
    ],
  },
  {
    id: "pope-leo-xiv-elected",
    title: "Pope Leo XIV is elected",
    year: 2025,
    category: "world",
    emoji: "⛪",
    color: "coral",
    fact: "Chicago-born Robert Prevost became the first pope from the United States and the first from the Augustinian order.",
    bonusFacts: [
      "He also held Peruvian citizenship after spending much of his ministry in Peru.",
    ],
  },
] satisfies EventItem[];
