import type { EventItem } from "./types";

export const EXPANDED_PRE_1850 = [
  // 001
  {
    id: "uruk-cuneiform-tablets",
    title: "Cuneiform writing appears in Uruk",
    year: -3200,
    category: "tech",
    emoji: "🧾",
    color: "sky",
    fact: "Uruk's earliest tablets used tiny pictograms to track grain, livestock, and labor before writing told stories.",
    bonusFacts: ["The marks were pressed into damp clay with a cut reed, then dried into records that could survive millennia."],
  },
  // 002
  {
    id: "narmer-unites-egypt",
    title: "Upper and Lower Egypt unite",
    year: -3100,
    circa: true,
    category: "world",
    emoji: "👑",
    color: "coral",
    fact: "King Narmer is traditionally credited with joining Egypt's two lands into one remarkably durable kingdom.",
    bonusFacts: ["The Narmer Palette shows him wearing the different crowns of Upper and Lower Egypt."],
  },
  // 003
  {
    id: "royal-game-of-ur",
    title: "The Royal Game of Ur is played",
    year: -2600,
    circa: true,
    category: "culture",
    emoji: "🎲",
    color: "lilac",
    fact: "A glittering board game buried at Ur proves people were racing pieces across boards 4,600 years ago.",
    bonusFacts: ["A later Babylonian tablet preserved enough rules for modern players to reconstruct the game."],
  },
  // 004
  {
    id: "great-pyramid-completed",
    title: "The Great Pyramid is completed",
    year: -2560,
    circa: true,
    category: "tech",
    emoji: "🔺",
    color: "sky",
    fact: "Khufu's pyramid remained the world's tallest human-made structure for roughly 3,800 years.",
    bonusFacts: ["Its builders positioned the monument astonishingly close to true north without modern instruments."],
  },
  // 005
  {
    id: "mohenjo-daro-planned-city",
    title: "Mohenjo-daro becomes a planned city",
    year: -2500,
    circa: true,
    category: "tech",
    emoji: "🏙️",
    color: "sky",
    fact: "Homes in this Indus city connected to an organized network of brick-lined drains and covered sewers.",
    bonusFacts: ["Many houses had private wells and bathing rooms when most cities had neither."],
  },
  // 006
  {
    id: "sargon-founds-akkadian-empire",
    title: "Sargon founds the Akkadian Empire",
    year: -2334,
    circa: true,
    category: "world",
    emoji: "🌍",
    color: "coral",
    fact: "Sargon joined competing Mesopotamian cities under a realm often described as history's first territorial empire.",
    bonusFacts: ["His Akkadian language became a diplomatic language across the Near East for centuries."],
  },
  // 007
  {
    id: "enheduanna-named-author",
    title: "Poetry is attributed to Enheduanna",
    year: -2300,
    circa: true,
    category: "culture",
    emoji: "✍️",
    color: "lilac",
    fact: "Enheduanna is the earliest named literary author in the surviving tradition, although the poems' authorship remains debated.",
    bonusFacts: ["Her hymns were copied in scribal schools hundreds of years after her death."],
  },
  // 008
  {
    id: "ur-nammu-law-code",
    title: "The Code of Ur-Nammu is written",
    year: -2100,
    circa: true,
    category: "world",
    emoji: "⚖️",
    color: "coral",
    fact: "This Sumerian law collection predates Hammurabi's code by more than three centuries.",
    bonusFacts: ["Several offenses were punished with measured silver fines rather than the better-known eye-for-an-eye formula."],
  },
  // 009
  {
    id: "gilgamesh-tablets",
    title: "Gilgamesh stories reach clay tablets",
    year: -2100,
    circa: true,
    category: "culture",
    emoji: "🦁",
    color: "lilac",
    fact: "The earliest surviving Gilgamesh poems already wrestled with friendship, grief, fame, and the impossibility of immortality.",
    bonusFacts: ["A later version includes a giant flood story that survived on tablets in Ashurbanipal's library."],
  },
  // 010
  {
    id: "hammurabi-stele",
    title: "Hammurabi's laws are carved in stone",
    year: -1754,
    category: "world",
    emoji: "🪨",
    color: "coral",
    fact: "The towering stele displayed nearly 300 legal rulings, from wages and loans to medical malpractice.",
    bonusFacts: ["Its rules changed by social rank, so equal justice was not the point."],
  },
  // 011
  {
    id: "rhind-mathematical-papyrus",
    title: "The Rhind math papyrus is copied",
    year: -1650,
    category: "discovery",
    emoji: "➗",
    color: "mint",
    fact: "An Egyptian scribe named Ahmes copied 84 worked problems involving fractions, geometry, bread, and beer.",
    bonusFacts: ["One problem uses a value for pi close enough to make a circle's area practical to calculate."],
  },
  // 012
  {
    id: "hatshepsut-becomes-pharaoh",
    title: "Hatshepsut becomes pharaoh",
    year: -1473,
    category: "world",
    emoji: "👑",
    color: "coral",
    fact: "Hatshepsut ruled Egypt as king, adopting the full royal titles and imagery normally reserved for men.",
    bonusFacts: ["Her reign emphasized trade and monumental building, including an elegant terraced temple at Deir el-Bahri."],
  },
  // 013
  {
    id: "tutankhamun-crowned",
    title: "Tutankhamun becomes pharaoh",
    year: -1332,
    category: "world",
    emoji: "🎭",
    color: "coral",
    fact: "Tutankhamun took the throne as a child and reversed his predecessor's radical religious changes.",
    bonusFacts: ["His short reign mattered less in antiquity than the unusually intact tomb that made him famous 3,200 years later."],
  },
  // 014
  {
    id: "battle-of-kadesh",
    title: "Egypt and the Hittites clash at Kadesh",
    year: -1274,
    category: "world",
    emoji: "🐎",
    color: "coral",
    fact: "Thousands of chariots made Kadesh one of antiquity's largest chariot battles, yet neither side won decisively.",
    bonusFacts: ["Ramesses II covered temples with heroic accounts even though the strategic result was a stalemate."],
  },
  // 015
  {
    id: "egypt-hittite-peace-treaty",
    title: "Egypt and the Hittites sign for peace",
    year: -1259,
    category: "world",
    emoji: "🤝",
    color: "coral",
    fact: "Their treaty is the earliest surviving international peace agreement whose text is known from both sides.",
    bonusFacts: ["A copy of its wording is displayed at United Nations headquarters."],
  },
  // 016
  {
    id: "olmec-san-lorenzo-flourishes",
    title: "San Lorenzo becomes an Olmec center",
    year: -1200,
    category: "culture",
    emoji: "🗿",
    color: "lilac",
    fact: "Olmec artists hauled enormous basalt blocks across Mexico to carve rulers' faces into colossal heads.",
    bonusFacts: ["Some finished heads weigh more than twenty tonnes and wear distinctive helmet-like headgear."],
  },
  // 017
  {
    id: "zhou-defeats-shang",
    title: "The Zhou dynasty defeats the Shang",
    year: -1046,
    category: "world",
    emoji: "🐉",
    color: "coral",
    fact: "The Zhou justified conquest with the Mandate of Heaven: rulers could lose divine approval through bad government.",
    bonusFacts: ["That political idea outlasted the dynasty and shaped Chinese rulership for two millennia."],
  },
  // 018
  {
    id: "phoenician-alphabet-spreads",
    title: "The Phoenician alphabet takes shape",
    year: -1000,
    circa: true,
    category: "tech",
    emoji: "🔤",
    color: "sky",
    fact: "Just 22 consonant signs made Phoenician writing far leaner than systems using hundreds of symbols.",
    bonusFacts: ["Greek writers adapted it and added vowel letters, helping create the ancestor of today's Latin alphabet."],
  },
  // 019
  {
    id: "lapita-settle-tonga",
    title: "Lapita voyagers settle Tonga",
    year: -900,
    category: "discovery",
    emoji: "🛶",
    color: "mint",
    fact: "Ocean-going Lapita communities carried families, crops, pottery, and animals far into the Pacific.",
    bonusFacts: ["Their stamped pottery helps archaeologists trace one of humanity's boldest settlement journeys."],
  },
  // 020
  {
    id: "first-recorded-olympics",
    title: "The first recorded Olympic Games",
    year: -776,
    category: "culture",
    emoji: "🏃",
    color: "lilac",
    fact: "The earliest recorded champion won a single footrace; later Games added wrestling, boxing, and chariots.",
    bonusFacts: ["Greek city-states dated events by the four-year Olympiad cycle."],
  },
  // 021
  {
    id: "bur-sagale-eclipse",
    title: "Assyria records a solar eclipse",
    year: -763,
    category: "discovery",
    emoji: "🌑",
    color: "mint",
    fact: "A terse Assyrian note about darkness in June anchors decades of ancient Near Eastern chronology.",
    bonusFacts: ["Modern calculations confirm a total eclipse crossed Assyria on 15 June 763 BCE."],
  },
  // 022
  {
    id: "ashurbanipal-library",
    title: "Ashurbanipal builds his great library",
    year: -668,
    category: "culture",
    emoji: "📚",
    color: "lilac",
    fact: "The Assyrian king collected tens of thousands of clay tablets on medicine, omens, literature, and administration.",
    bonusFacts: ["Its ruins preserved the fullest surviving version of the Epic of Gilgamesh."],
  },
  // 023
  {
    id: "nineveh-falls",
    title: "Nineveh falls",
    year: -612,
    category: "world",
    emoji: "🏚️",
    color: "coral",
    fact: "A coalition sacked the enormous Assyrian capital, ending an empire that had seemed terrifyingly permanent.",
    bonusFacts: ["The buried remains of its tablet libraries became an accidental time capsule for modern archaeologists."],
  },
  // 024
  {
    id: "babylonian-world-map",
    title: "A Babylonian draws the known world",
    year: -600,
    category: "discovery",
    emoji: "🗺️",
    color: "mint",
    fact: "The oldest surviving map of the world places Babylon beside the Euphrates inside a circular ocean.",
    bonusFacts: ["Mysterious triangular regions beyond the ocean mixed geography with mythology."],
  },
  // 025
  {
    id: "solon-reforms-athens",
    title: "Solon rewrites Athens' laws",
    year: -594,
    category: "world",
    emoji: "⚖️",
    color: "coral",
    fact: "Solon cancelled debt slavery for Athenians and widened political participation without creating full democracy.",
    bonusFacts: ["He reportedly left Athens for years so citizens could not pressure him to rewrite the settlement."],
  },
  // 026
  {
    id: "cyrus-enters-babylon",
    title: "Cyrus the Great enters Babylon",
    year: -539,
    category: "world",
    emoji: "🚪",
    color: "coral",
    fact: "Babylon fell to Persia with remarkably little fighting, giving Cyrus control of a vast imperial crossroads.",
    bonusFacts: ["His cylinder presents the takeover in traditional Babylonian language, as a restoration blessed by their god Marduk."],
  },
  // 027
  {
    id: "persia-conquers-egypt",
    title: "Persia conquers Egypt",
    year: -525,
    category: "world",
    emoji: "🏺",
    color: "coral",
    fact: "Cambyses II added Egypt to an Achaemenid realm stretching from the Nile toward Central Asia.",
    bonusFacts: ["Persian kings then appeared in Egypt with pharaonic titles and imagery."],
  },
  // 028
  {
    id: "roman-republic-begins",
    title: "The Roman Republic begins",
    year: -509,
    category: "world",
    emoji: "🏛️",
    color: "coral",
    fact: "Roman tradition dated the expulsion of its last king to 509 BCE and replaced monarchy with elected magistrates.",
    bonusFacts: ["The new republic was not a democracy for everyone: elite families dominated its early offices."],
  },
  // 029
  {
    id: "cleisthenes-athenian-reforms",
    title: "Athens reorganizes around its citizens",
    year: -508,
    category: "world",
    emoji: "🗳️",
    color: "coral",
    fact: "Cleisthenes broke up old power blocs and created the civic structure behind Athenian democracy.",
    bonusFacts: ["Participation still excluded women, enslaved people, and resident foreigners."],
  },
  // 030
  {
    id: "darius-royal-road",
    title: "Persia's Royal Road links an empire",
    year: -500,
    category: "tech",
    emoji: "🐎",
    color: "sky",
    fact: "A relay network of roads and stations let royal messages cross thousands of kilometers with exceptional speed.",
    bonusFacts: ["Herodotus admired couriers who kept going through snow, rain, heat, and darkness."],
  },
  // 031
  {
    id: "battle-of-marathon",
    title: "Athens wins at Marathon",
    year: -490,
    category: "world",
    emoji: "🏃",
    color: "coral",
    fact: "The famous modern race took its name from this battle, not from an event in the ancient Olympics.",
    bonusFacts: ["The familiar tale of one runner collapsing after announcing victory appeared centuries after the battle."],
  },
  // 032
  {
    id: "aeschylus-persians-premiere",
    title: "The Persians premieres in Athens",
    year: -472,
    category: "culture",
    emoji: "🎭",
    color: "lilac",
    fact: "Aeschylus dramatized a recent war from the defeated Persian court's perspective rather than celebrating onstage in Athens.",
    bonusFacts: ["It is the oldest complete play to survive from ancient Greece."],
  },
  // 033
  {
    id: "parthenon-completed",
    title: "The Parthenon is completed",
    year: -432,
    category: "tech",
    emoji: "🏛️",
    color: "sky",
    fact: "Its builders subtly curved supposedly straight lines so the marble temple would look perfectly balanced to human eyes.",
    bonusFacts: ["Inside stood a colossal gold-and-ivory statue of Athena, now lost."],
  },
  // 034
  {
    id: "peloponnesian-war-begins",
    title: "The Peloponnesian War begins",
    year: -431,
    category: "world",
    emoji: "⚔️",
    color: "coral",
    fact: "Athens and Sparta dragged much of the Greek world into a grinding 27-year struggle.",
    bonusFacts: ["Thucydides turned the conflict into one of history's earliest deeply analytical war accounts."],
  },
  // 035
  {
    id: "socrates-trial",
    title: "Socrates is put on trial",
    year: -399,
    category: "culture",
    emoji: "🗣️",
    color: "lilac",
    fact: "Athens condemned Socrates for impiety and corrupting the young; he accepted execution by drinking hemlock.",
    bonusFacts: ["He wrote no books, so his ideas survive through students and critics."],
  },
  // 036
  {
    id: "plato-founds-academy",
    title: "Plato founds the Academy",
    year: -387,
    category: "culture",
    emoji: "🎓",
    color: "lilac",
    fact: "Plato's school became so influential that its name still means a community of learning.",
    bonusFacts: ["Aristotle studied there for roughly twenty years before founding his own school."],
  },
  // 037
  {
    id: "alexander-becomes-king",
    title: "Alexander becomes king of Macedon",
    year: -336,
    category: "world",
    emoji: "👑",
    color: "coral",
    fact: "At twenty, Alexander inherited a formidable army and soon launched a campaign reaching Egypt and India.",
    bonusFacts: ["His empire fractured almost immediately after his death because he left no clear adult successor."],
  },
  // 038
  {
    id: "aristotle-founds-lyceum",
    title: "Aristotle opens the Lyceum",
    year: -335,
    category: "culture",
    emoji: "📖",
    color: "lilac",
    fact: "Aristotle's school investigated everything from constitutions and poetry to animal anatomy and the weather.",
    bonusFacts: ["Its scholars assembled one of the ancient world's earliest organized research collections."],
  },
  // 039
  {
    id: "alexandria-founded",
    title: "Alexandria is founded",
    year: -331,
    category: "world",
    emoji: "🌊",
    color: "coral",
    fact: "Alexander's Egyptian port grew into a multilingual metropolis linking Mediterranean, African, and Asian trade.",
    bonusFacts: ["It later housed both the famous Pharos lighthouse and the Mouseion associated with its great library."],
  },
  // 040
  {
    id: "mauryan-empire-founded",
    title: "Chandragupta founds the Mauryan Empire",
    year: -322,
    category: "world",
    emoji: "🦚",
    color: "coral",
    fact: "Chandragupta built the first empire to unite most of the Indian subcontinent under one administration.",
    bonusFacts: ["Its capital Pataliputra impressed a Greek visitor with timber walls, towers, and hundreds of watch posts."],
  },
  // 041
  {
    id: "seleucid-era-begins",
    title: "The Seleucid calendar begins",
    year: -312,
    category: "discovery",
    emoji: "📅",
    color: "mint",
    fact: "A continuous year count introduced under Seleucus became one of the ancient world's most widely used dating systems.",
    bonusFacts: ["Unlike regnal calendars, it did not restart whenever a new king took power."],
  },
  // 042
  {
    id: "euclid-elements",
    title: "Euclid assembles the Elements",
    year: -300,
    category: "discovery",
    emoji: "📐",
    color: "mint",
    fact: "Euclid built geometry from definitions and proofs in a textbook used for more than two thousand years.",
    bonusFacts: ["Its elegant proof that prime numbers never run out still appears in mathematics classes."],
  },
  // 043
  {
    id: "ashoka-crowned",
    title: "Ashoka is crowned",
    year: -268,
    category: "world",
    emoji: "🦁",
    color: "coral",
    fact: "Ashoka inherited the Mauryan Empire before turning royal proclamations into messages carved across South Asia.",
    bonusFacts: ["India's national emblem adapts the four-lion capital erected during his reign."],
  },
  // 044
  {
    id: "first-punic-war-begins",
    title: "Rome and Carthage go to war",
    year: -264,
    category: "world",
    emoji: "⛵",
    color: "coral",
    fact: "A dispute in Sicily began a 23-year war that forced land-focused Rome to become a naval power.",
    bonusFacts: ["Romans fitted ships with boarding bridges so infantry tactics could work at sea."],
  },
  // 045
  {
    id: "ashoka-kalinga-war",
    title: "Ashoka conquers Kalinga",
    year: -261,
    category: "world",
    emoji: "🕊️",
    color: "coral",
    fact: "Ashoka's own inscription says the suffering at Kalinga filled him with remorse and changed his rule.",
    bonusFacts: ["He promoted moral conduct and welfare afterward, though he did not dissolve his empire or army."],
  },
  // 046
  {
    id: "ashoka-rock-edicts",
    title: "Ashoka's edicts speak from stone",
    year: -250,
    category: "culture",
    emoji: "🪨",
    color: "lilac",
    fact: "Messages carved in local languages urged religious tolerance, compassion, and humane treatment of people and animals.",
    bonusFacts: ["They are among India's earliest extensive written records that can be read today."],
  },
  // 047
  {
    id: "archimedes-pi-bounds",
    title: "Archimedes traps pi between fractions",
    year: -250,
    category: "discovery",
    emoji: "⭕",
    color: "mint",
    fact: "By squeezing circles between 96-sided polygons, Archimedes calculated remarkably tight bounds for pi.",
    bonusFacts: ["His upper bound, 22/7, remains a familiar quick approximation."],
  },
  // 048
  {
    id: "eratosthenes-earth-circumference",
    title: "Eratosthenes measures Earth",
    year: -240,
    category: "discovery",
    emoji: "🌍",
    color: "mint",
    fact: "Comparing noon shadows in two Egyptian cities gave Eratosthenes a strikingly good estimate of Earth's circumference.",
    bonusFacts: ["He needed no satellite—just geometry, distance, sunlight, and the knowledge that Earth is curved."],
  },
  // 049
  {
    id: "halleys-comet-china-record",
    title: "Chinese astronomers record Halley's Comet",
    year: -240,
    category: "discovery",
    emoji: "☄️",
    color: "mint",
    fact: "A Chinese chronicle preserved the earliest unambiguous sighting linked to the comet now called Halley's.",
    bonusFacts: ["The comet returns roughly every 76 years, but its orbit was not recognized until Edmond Halley studied later records."],
  },
  // 050
  {
    id: "qin-unifies-china",
    title: "Qin unifies China",
    year: -221,
    category: "world",
    emoji: "🐲",
    color: "coral",
    fact: "The First Emperor standardized weights, measures, coinage, and writing across newly conquered kingdoms.",
    bonusFacts: ["The modern name China is often linked to Qin, though the linguistic path is debated."],
  },
  // 051
  {
    id: "first-emperor-terracotta-burial",
    title: "The First Emperor is buried with an army",
    year: -210,
    category: "culture",
    emoji: "🗿",
    color: "lilac",
    fact: "Thousands of life-sized terracotta soldiers guarded Qin Shi Huang's underground tomb complex.",
    bonusFacts: ["Their faces vary, but workshop molds and interchangeable features helped artisans produce the enormous force."],
  },
  // 052
  {
    id: "han-dynasty-founded",
    title: "The Han dynasty begins",
    year: -202,
    category: "world",
    emoji: "🏯",
    color: "coral",
    fact: "Liu Bang rose from peasant origins to found a dynasty that gave its name to China's largest ethnic group.",
    bonusFacts: ["Han government blended Qin institutions with a less punishing public image."],
  },
  // 053
  {
    id: "rosetta-stone-inscribed",
    title: "The Rosetta Stone is inscribed",
    year: -196,
    category: "culture",
    emoji: "🔡",
    color: "lilac",
    fact: "One royal decree appeared in hieroglyphs, Demotic, and Greek, eventually unlocking ancient Egyptian writing.",
    bonusFacts: ["The stone is only part of a larger slab; matching copies of the decree survive elsewhere."],
  },
  // 054
  {
    id: "zhang-qian-returns",
    title: "Zhang Qian returns from Central Asia",
    year: -126,
    category: "discovery",
    emoji: "🐫",
    color: "mint",
    fact: "After capture, escape, and years abroad, Zhang Qian brought China detailed knowledge of distant western kingdoms.",
    bonusFacts: ["His reports encouraged routes later grouped under the modern name Silk Roads."],
  },
  // 055
  {
    id: "antikythera-mechanism-built",
    title: "The Antikythera mechanism is built",
    year: -100,
    category: "tech",
    emoji: "⚙️",
    color: "sky",
    fact: "Dozens of bronze gears modeled astronomical cycles in a hand-cranked device unlike anything else surviving from antiquity.",
    bonusFacts: ["It could predict eclipse patterns and track the four-year cycle of major athletic games."],
  },
  // 056
  {
    id: "sima-qian-records-grand-historian",
    title: "Sima Qian completes China's great history",
    year: -91,
    category: "culture",
    emoji: "📜",
    color: "lilac",
    fact: "His Records of the Grand Historian shaped how Chinese history would be organized and written for centuries.",
    bonusFacts: ["It ranged from legendary rulers to Sima Qian's own era and included vivid biographies beyond the imperial court."],
  },
  // 057
  {
    id: "caesar-crosses-rubicon",
    title: "Caesar crosses the Rubicon",
    year: -49,
    category: "world",
    emoji: "🌉",
    color: "coral",
    fact: "Leading an army across Rome's boundary made Julius Caesar's rebellion unmistakable and triggered civil war.",
    bonusFacts: ["The phrase crossing the Rubicon still means taking an irreversible step."],
  },
  // 058
  {
    id: "julian-calendar-begins",
    title: "The Julian calendar begins",
    year: -45,
    category: "discovery",
    emoji: "📅",
    color: "mint",
    fact: "Caesar's reform created a 365-day year with leap days, replacing Rome's badly misaligned calendar.",
    bonusFacts: ["The previous year was stretched to 445 days to drag the months back into place."],
  },
  // 059
  {
    id: "cleopatra-dies",
    title: "Cleopatra dies",
    year: -30,
    category: "world",
    emoji: "🐍",
    color: "coral",
    fact: "Cleopatra VII's death ended Ptolemaic rule and left Egypt under the control of Octavian's Rome.",
    bonusFacts: ["She lived closer in time to the Moon landing than to the construction of the Great Pyramid."],
  },
  // 060
  {
    id: "augustus-first-roman-emperor",
    title: "Augustus becomes Rome's first emperor",
    year: -27,
    category: "world",
    emoji: "🏛️",
    color: "coral",
    fact: "Octavian accepted the name Augustus while carefully preserving the outward forms of a republic he controlled.",
    bonusFacts: ["His title princeps meant first citizen, a deliberately modest label for extraordinary power."],
  },
  // 061
  {
    id: "amanirenas-rome-peace",
    title: "Kush makes peace with Rome",
    year: -21,
    category: "world",
    emoji: "🏹",
    color: "coral",
    fact: "Kandake Amanirenas secured favorable terms after the kingdom of Kush fought Rome along Egypt's southern frontier.",
    bonusFacts: ["A bronze head of Augustus found beneath a temple stair may have been war booty deliberately stepped on."],
  },
  // 062
  {
    id: "strabo-geography-completed",
    title: "Strabo completes his Geography",
    year: 23,
    category: "discovery",
    emoji: "🗺️",
    color: "mint",
    fact: "Seventeen volumes described peoples and places from the Atlantic to India using travel, scholarship, and hearsay.",
    bonusFacts: ["It is the only large geographical work from its era to survive nearly complete."],
  },
  // 063
  {
    id: "vesuvius-buries-pompeii",
    title: "Vesuvius buries Pompeii",
    year: 79,
    category: "world",
    emoji: "🌋",
    color: "coral",
    fact: "Volcanic ash preserved streets, graffiti, food, shops, and homes with extraordinary everyday detail.",
    bonusFacts: ["The eruption's deadly surges reached Pompeii after many people had survived the first hours of falling debris."],
  },
  // 064
  {
    id: "colosseum-opens",
    title: "The Colosseum opens",
    year: 80,
    category: "culture",
    emoji: "🏟️",
    color: "lilac",
    fact: "Rome's giant amphitheater managed tens of thousands of spectators with numbered entrances and layered corridors.",
    bonusFacts: ["A retractable fabric awning shaded much of the crowd, operated by sailors from the imperial fleet."],
  },
  // 065
  {
    id: "cai-lun-paper-process",
    title: "Cai Lun reports a papermaking process",
    year: 105,
    category: "tech",
    emoji: "📄",
    color: "sky",
    fact: "The Han court official described sheets made from materials such as bark, hemp waste, rags, and fishing nets.",
    bonusFacts: ["Paper already existed in China, but Cai Lun's report became the traditional milestone for improving and promoting it."],
  },
  // 066
  {
    id: "ban-zhao-book-of-han",
    title: "Ban Zhao completes the Book of Han",
    year: 111,
    category: "culture",
    emoji: "📚",
    color: "lilac",
    fact: "Ban Zhao finished the monumental dynastic history begun by her father and brother.",
    bonusFacts: ["She also taught women of the imperial family and became one of early China's most influential female scholars."],
  },
  // 067
  {
    id: "roman-empire-maximum-extent",
    title: "Rome reaches its greatest extent",
    year: 117,
    category: "world",
    emoji: "🦅",
    color: "coral",
    fact: "At Trajan's death, Roman territory stretched from northern Britain to Mesopotamia and surrounded the Mediterranean.",
    bonusFacts: ["His successor Hadrian quickly abandoned some eastern conquests as too difficult to hold."],
  },
  // 068
  {
    id: "pantheon-rebuilt",
    title: "The Pantheon is rebuilt",
    year: 126,
    category: "tech",
    emoji: "🏛️",
    color: "sky",
    fact: "Its unreinforced concrete dome remains the world's largest of its kind nearly nineteen centuries later.",
    bonusFacts: ["The open oculus lights the interior and also lets rain fall onto a subtly drained floor."],
  },
  // 069
  {
    id: "zhang-heng-seismoscope",
    title: "Zhang Heng builds a seismoscope",
    year: 132,
    category: "tech",
    emoji: "🐉",
    color: "sky",
    fact: "The bronze device reportedly dropped a ball from a dragon's mouth to indicate an earthquake's direction.",
    bonusFacts: ["It detected distant shaking that observers at the capital had not felt."],
  },
  // 070
  {
    id: "ptolemy-almagest",
    title: "Ptolemy assembles the Almagest",
    year: 150,
    category: "discovery",
    emoji: "🌌",
    color: "mint",
    fact: "Its mathematical model predicted planetary positions well enough to dominate astronomy for more than a millennium.",
    bonusFacts: ["The model put Earth at the center and used circles upon circles to match wandering planets."],
  },
  // 071
  {
    id: "guest-star-185",
    title: "Chinese astronomers see a guest star",
    year: 185,
    category: "discovery",
    emoji: "💥",
    color: "mint",
    fact: "Court astronomers recorded a brilliant new light that remained visible for months, likely a supernova.",
    bonusFacts: ["Modern astronomers have identified a possible expanding remnant near the recorded position."],
  },
  // 072
  {
    id: "red-cliffs-battle",
    title: "The Battle of Red Cliffs",
    year: 208,
    category: "world",
    emoji: "🔥",
    color: "coral",
    fact: "A smaller southern alliance used fire against Cao Cao's fleet, blocking his attempt to reunify China.",
    bonusFacts: ["The clash became one of East Asia's most retold historical episodes through the Romance of the Three Kingdoms."],
  },
  // 073
  {
    id: "caracalla-citizenship-edict",
    title: "Rome extends citizenship across the empire",
    year: 212,
    category: "world",
    emoji: "📜",
    color: "coral",
    fact: "Caracalla granted Roman citizenship to nearly all free inhabitants of the empire in a single decree.",
    bonusFacts: ["The change broadened legal identity—and probably the pool of people liable for certain Roman taxes."],
  },
  // 074
  {
    id: "three-kingdoms-era-begins",
    title: "China's Three Kingdoms era begins",
    year: 220,
    category: "world",
    emoji: "⚔️",
    color: "coral",
    fact: "The Han dynasty's collapse divided China among Wei, Shu, and Wu, inspiring centuries of stories and strategy games.",
    bonusFacts: ["The famous novel dramatizing the era was written more than a thousand years later."],
  },
  // 075
  {
    id: "sasanian-empire-founded",
    title: "The Sasanian Empire begins",
    year: 224,
    category: "world",
    emoji: "🔥",
    color: "coral",
    fact: "Ardashir I replaced Parthian rule with a Persian empire that became Rome's great eastern rival.",
    bonusFacts: ["Sasanian art, court culture, and administration influenced later Islamic empires."],
  },
  // 076
  {
    id: "zenobia-palmyrene-empire",
    title: "Zenobia breaks Palmyra from Rome",
    year: 270,
    category: "world",
    emoji: "🐪",
    color: "coral",
    fact: "Queen Zenobia's forces seized Egypt and much of Rome's east before Emperor Aurelian reconquered them.",
    bonusFacts: ["Her desert capital Palmyra had grown rich connecting caravan routes with the Mediterranean."],
  },
  // 077
  {
    id: "tikal-stela-29",
    title: "Tikal raises its earliest dated monument",
    year: 292,
    category: "culture",
    emoji: "🗿",
    color: "lilac",
    fact: "Stela 29 bears the earliest surviving Maya Long Count date from the great city of Tikal.",
    bonusFacts: ["The Long Count tracked days across spans far longer than a human reign."],
  },
  // 078
  {
    id: "diocletian-tetrarchy",
    title: "Rome is divided among four rulers",
    year: 293,
    category: "world",
    emoji: "👥",
    color: "coral",
    fact: "Diocletian's Tetrarchy gave two senior and two junior emperors responsibility for different regions.",
    bonusFacts: ["The system improved response times but unravelled into civil war after its architect retired."],
  },
  // 079
  {
    id: "armenia-adopts-christianity",
    title: "Armenia adopts Christianity",
    year: 301,
    category: "world",
    emoji: "⛪",
    color: "coral",
    fact: "Armenian tradition dates the kingdom's conversion to 301, making it the first Christian state.",
    bonusFacts: ["Its distinctive national church developed long before most of northern Europe converted."],
  },
  // 080
  {
    id: "gupta-empire-begins",
    title: "The Gupta Empire begins",
    year: 320,
    category: "world",
    emoji: "🪷",
    color: "coral",
    fact: "A new imperial era began in northern India, later associated with major advances in art, literature, and mathematics.",
    bonusFacts: ["Gupta rulers issued exquisitely detailed gold coins showing kings as archers, horsemen, and musicians."],
  },
  // 081
  {
    id: "council-of-nicaea",
    title: "The Council of Nicaea meets",
    year: 325,
    category: "culture",
    emoji: "⛪",
    color: "lilac",
    fact: "Bishops summoned by Constantine debated Christian doctrine and produced the foundation of the Nicene Creed.",
    bonusFacts: ["Contrary to a popular myth, the council did not choose which books belong in the Bible."],
  },
  // 082
  {
    id: "constantinople-dedicated",
    title: "Constantinople becomes an imperial capital",
    year: 330,
    category: "world",
    emoji: "🏙️",
    color: "coral",
    fact: "Constantine rebuilt Byzantium at a strategic crossing where Europe, Asia, and major sea routes met.",
    bonusFacts: ["The city remained an imperial capital under different empires until the twentieth century."],
  },
  // 083
  {
    id: "ezana-converts-aksum",
    title: "King Ezana makes Aksum Christian",
    year: 330,
    category: "world",
    emoji: "🪙",
    color: "coral",
    fact: "Ezana's conversion made the powerful Red Sea kingdom of Aksum one of the world's earliest Christian states.",
    bonusFacts: ["Crosses replaced older symbols on Aksumite coins, broadcasting the change through trade."],
  },
  // 084
  {
    id: "christianity-roman-state-religion",
    title: "Christianity becomes Rome's state religion",
    year: 380,
    category: "world",
    emoji: "📜",
    color: "coral",
    fact: "The Edict of Thessalonica backed Nicene Christianity as the official faith of the Roman imperial government.",
    bonusFacts: ["This came only 67 years after Constantine and Licinius had legalized Christian worship."],
  },
  // 085
  {
    id: "battle-of-fei-river",
    title: "A smaller Jin army wins at Fei River",
    year: 383,
    category: "world",
    emoji: "🌊",
    color: "coral",
    fact: "A retreat meant only to make room for battle turned into panic and shattered Former Qin's huge force.",
    bonusFacts: ["The result preserved southern Chinese rule and delayed reunification for two centuries."],
  },
  // 086
  {
    id: "faxian-pilgrimage-begins",
    title: "Faxian walks from China toward India",
    year: 399,
    category: "discovery",
    emoji: "🥾",
    color: "mint",
    fact: "The Buddhist monk crossed deserts and mountains searching for sacred texts and accurate monastic rules.",
    bonusFacts: ["He returned by sea and left a rare eyewitness account of South and Southeast Asia."],
  },
  // 087
  {
    id: "kumarajiva-changan-translations",
    title: "Kumarajiva begins translating in Chang'an",
    year: 401,
    category: "culture",
    emoji: "📖",
    color: "lilac",
    fact: "His lucid Chinese translations made major Buddhist texts understandable and influential across East Asia.",
    bonusFacts: ["Teams debated meaning aloud while scribes refined the final phrasing, making translation a collaborative event."],
  },
  // 088
  {
    id: "visigoths-sack-rome",
    title: "The Visigoths sack Rome",
    year: 410,
    category: "world",
    emoji: "🏛️",
    color: "coral",
    fact: "Alaric's troops entered a city that had not fallen to a foreign enemy for nearly eight centuries.",
    bonusFacts: ["The western empire continued for decades, but the psychological shock traveled across the Roman world."],
  },
  // 089
  {
    id: "western-roman-empire-ends",
    title: "The Western Roman Empire ends",
    year: 476,
    category: "world",
    emoji: "🦅",
    color: "coral",
    fact: "The soldier Odoacer removed the teenage emperor Romulus Augustulus and sent the imperial insignia east.",
    bonusFacts: ["People living through 476 did not suddenly declare antiquity over; that neat boundary came from later historians."],
  },
  // 090
  {
    id: "longmen-grottoes-begin",
    title: "Carving begins at the Longmen Grottoes",
    year: 493,
    category: "culture",
    emoji: "🪷",
    color: "lilac",
    fact: "Generations of patrons cut more than 100,000 Buddhist figures into cliffs beside China's Yi River.",
    bonusFacts: ["The smallest are only a few centimeters tall; the largest Buddha rises over seventeen meters."],
  },
  // 091
  {
    id: "clovis-baptized",
    title: "Clovis is baptized",
    year: 496,
    category: "world",
    emoji: "💧",
    color: "coral",
    fact: "The Frankish king's conversion to Catholic Christianity strengthened ties with Gallo-Roman elites and bishops.",
    bonusFacts: ["Most neighboring Germanic rulers then followed a different form of Christianity called Arianism."],
  },
  // 092
  {
    id: "aryabhata-writes-aryabhatiya",
    title: "Aryabhata writes the Aryabhatiya",
    year: 499,
    category: "discovery",
    emoji: "🧮",
    color: "mint",
    fact: "In compact Sanskrit verse, Aryabhata explained algorithms, sines, eclipses, and Earth's rotation.",
    bonusFacts: ["He correctly argued that stars seem to move west because Earth turns east."],
  },
  // 093
  {
    id: "justinian-code-published",
    title: "Justinian publishes a new Roman law code",
    year: 529,
    category: "world",
    emoji: "⚖️",
    color: "coral",
    fact: "The emperor's scholars organized centuries of sprawling Roman law into a more usable collection.",
    bonusFacts: ["Rediscovered in western Europe, it became foundational to many modern civil-law systems."],
  },
  // 094
  {
    id: "hagia-sophia-completed",
    title: "Hagia Sophia is completed",
    year: 537,
    category: "tech",
    emoji: "🕌",
    color: "sky",
    fact: "Its vast dome seemed to float above a ring of windows and was finished in under six years.",
    bonusFacts: ["The building has served as cathedral, mosque, museum, and mosque again."],
  },
  // 095
  {
    id: "plague-of-justinian",
    title: "Plague reaches Constantinople",
    year: 541,
    category: "world",
    emoji: "🦠",
    color: "coral",
    fact: "The first recorded plague pandemic disrupted cities, armies, and trade across the Mediterranean and beyond.",
    bonusFacts: ["Ancient DNA confirms the disease involved Yersinia pestis, the same bacterium behind the later Black Death."],
  },
  // 096
  {
    id: "seventeen-article-constitution",
    title: "Japan issues its Seventeen-Article Constitution",
    year: 604,
    category: "world",
    emoji: "📜",
    color: "coral",
    fact: "Rather than individual rights, the document offered Buddhist and Confucian principles for officials serving the court.",
    bonusFacts: ["Its opening call for harmony remains one of the best-known lines in early Japanese political thought."],
  },
  // 097
  {
    id: "sui-grand-canal-completed",
    title: "China's Grand Canal links north and south",
    year: 611,
    category: "tech",
    emoji: "🚤",
    color: "sky",
    fact: "Sui engineers joined older waterways into a vast transport artery carrying grain toward northern capitals.",
    bonusFacts: ["Expanded by later dynasties, it became the world's longest artificial waterway."],
  },
  // 098
  {
    id: "tang-dynasty-founded",
    title: "The Tang dynasty begins",
    year: 618,
    category: "world",
    emoji: "🏯",
    color: "coral",
    fact: "Tang rule made Chang'an a cosmopolitan capital visited by merchants and envoys from across Eurasia.",
    bonusFacts: ["Its poetry, fashions, ceramics, and institutions strongly influenced neighboring Korea and Japan."],
  },
  // 099
  {
    id: "hijra-to-medina",
    title: "Muhammad migrates to Medina",
    year: 622,
    category: "world",
    emoji: "🌙",
    color: "coral",
    fact: "The Hijra transformed a persecuted community into a new polity and begins the Islamic calendar's year count.",
    bonusFacts: ["The calendar itself was formally adopted later under Caliph Umar."],
  },
  // 100
  {
    id: "brahmagupta-rules-for-zero",
    title: "Brahmagupta calculates with zero",
    year: 628,
    category: "discovery",
    emoji: "0️⃣",
    color: "mint",
    fact: "Brahmagupta set out arithmetic rules treating zero as a number rather than merely an empty place.",
    bonusFacts: ["His rule for dividing by zero was wrong, but formalizing zero transformed mathematics."],
  },
  // 101
  {
    id: "xuanzang-journey-west",
    title: "Xuanzang sets out for India",
    year: 629,
    category: "discovery",
    emoji: "🐎",
    color: "mint",
    fact: "The monk slipped out of Tang China, crossed Central Asia, studied in India, and returned with hundreds of Buddhist texts.",
  },
  // 102
  {
    id: "arab-army-takes-alexandria",
    title: "Arab forces take Alexandria",
    year: 642,
    category: "world",
    emoji: "🏙️",
    color: "coral",
    fact: "The capture ended centuries of Roman rule in Egypt and connected the Nile valley to a fast-growing caliphate.",
  },
  // 103
  {
    id: "uthman-standardizes-quran",
    title: "The Quran's written text is standardized",
    year: 650,
    category: "culture",
    emoji: "📖",
    color: "lilac",
    fact: "Caliph Uthman sponsored a standard consonantal text and sent authoritative copies to major Muslim centers.",
  },
  // 104
  {
    id: "pakal-buried-palenque",
    title: "Pakal is buried beneath a Maya pyramid",
    year: 683,
    category: "culture",
    emoji: "🌿",
    color: "lilac",
    fact: "Palenque's ruler was placed in an enormous carved sarcophagus inside the Temple of the Inscriptions.",
  },
  // 105
  {
    id: "wu-zetian-emperor",
    title: "Wu Zetian becomes China's emperor",
    year: 690,
    category: "world",
    emoji: "👑",
    color: "coral",
    fact: "Wu Zetian took the imperial title in her own name, the only woman to do so in Chinese history.",
  },
  // 106
  {
    id: "dome-of-rock-completed",
    title: "The Dome of the Rock is completed",
    year: 691,
    category: "tech",
    emoji: "✨",
    color: "sky",
    fact: "Its golden octagonal shrine is the oldest major Islamic monument still standing substantially in its original form.",
  },
  // 107
  {
    id: "nara-becomes-capital",
    title: "Nara becomes Japan's capital",
    year: 710,
    category: "world",
    emoji: "🦌",
    color: "coral",
    fact: "Japan's first permanent capital was laid out as a grid inspired by Tang China's Chang'an.",
  },
  // 108
  {
    id: "kojiki-completed",
    title: "Japan's Kojiki is completed",
    year: 712,
    category: "culture",
    emoji: "📜",
    color: "lilac",
    fact: "Japan's oldest surviving book wove creation myths, songs, genealogies, and royal legitimacy into one chronicle.",
  },
  // 109
  {
    id: "baghdad-founded",
    title: "Baghdad is founded",
    year: 762,
    category: "world",
    emoji: "⭕",
    color: "coral",
    fact: "The Abbasid capital began as a carefully planned circular city and became a magnet for trade and scholarship.",
  },
  // 110
  {
    id: "hyakumanto-darani-printed",
    title: "Japan prints a million tiny prayers",
    year: 770,
    category: "tech",
    emoji: "🖨️",
    color: "sky",
    fact: "Empress Shōtoku commissioned a million wooden pagodas, each containing a small block-printed Buddhist text.",
  },
  // 111
  {
    id: "charlemagne-crowned-emperor",
    title: "Charlemagne is crowned emperor",
    year: 800,
    category: "world",
    emoji: "👑",
    color: "coral",
    fact: "The Christmas Day coronation revived an imperial title in western Europe more than three centuries after Rome's fall.",
  },
  // 112
  {
    id: "khmer-empire-begins",
    title: "Jayavarman II founds the Khmer Empire",
    year: 802,
    category: "world",
    emoji: "🐘",
    color: "coral",
    fact: "A ceremony on Phnom Kulen marked the start of a state that would build the monumental city of Angkor.",
  },
  // 113
  {
    id: "al-khwarizmi-algebra",
    title: "Al-Khwarizmi writes a book of algebra",
    year: 820,
    category: "discovery",
    emoji: "➗",
    color: "mint",
    fact: "His systematic guide to solving equations gave algebra its name from the Arabic word al-jabr.",
  },
  // 114
  {
    id: "borobudur-completed",
    title: "Borobudur is completed",
    year: 825,
    category: "culture",
    emoji: "🛕",
    color: "lilac",
    fact: "The immense Javanese monument guides visitors upward past miles of carved Buddhist stories toward open terraces.",
  },
  // 115
  {
    id: "house-of-wisdom-translation",
    title: "Baghdad's translation movement flourishes",
    year: 830,
    category: "culture",
    emoji: "📚",
    color: "lilac",
    fact: "Scholars associated with the House of Wisdom translated and extended Greek, Persian, and Indian learning in Arabic.",
  },
  // 116
  {
    id: "kairouan-great-mosque-rebuilt",
    title: "Kairouan's Great Mosque takes its classic form",
    year: 836,
    category: "tech",
    emoji: "🕌",
    color: "sky",
    fact: "Aghlabid builders reshaped the Tunisian mosque whose massive square minaret influenced architecture across North Africa.",
  },
  // 117
  {
    id: "banu-musa-ingenious-devices",
    title: "The Banū Mūsā describe ingenious machines",
    year: 850,
    category: "tech",
    emoji: "⚙️",
    color: "sky",
    fact: "Their illustrated book explained fountains, automatic controls, trick vessels, and valves that behaved with surprising sophistication.",
  },
  // 118
  {
    id: "diamond-sutra-printed",
    title: "The Diamond Sutra is printed",
    year: 868,
    category: "tech",
    emoji: "📜",
    color: "sky",
    fact: "A dated Chinese scroll is the earliest complete printed book known, produced centuries before Gutenberg.",
  },
  // 119
  {
    id: "ghana-empire-described",
    title: "A writer describes the Ghana Empire",
    year: 872,
    category: "culture",
    emoji: "🪙",
    color: "lilac",
    fact: "Al-Ya'qubi called Ghana's ruler a great king with other rulers under his authority and rich gold resources.",
  },
  // 120
  {
    id: "iceland-settlement-begins",
    title: "Norse settlers establish themselves in Iceland",
    year: 874,
    category: "discovery",
    emoji: "🌋",
    color: "mint",
    fact: "Tradition names Ingólfur Arnarson as Reykjavík's first permanent Norse settler during a rapid settlement era.",
  },
  // 121
  {
    id: "yasodharapura-founded",
    title: "Angkor's first great capital is founded",
    year: 889,
    category: "world",
    emoji: "🏯",
    color: "coral",
    fact: "King Yasovarman I established Yasodharapura beside a vast reservoir, beginning Angkor's metropolitan expansion.",
  },
  // 122
  {
    id: "al-razi-smallpox-measles",
    title: "Al-Razi distinguishes smallpox from measles",
    year: 910,
    category: "discovery",
    emoji: "🩺",
    color: "mint",
    fact: "The Persian physician carefully compared symptoms of two diseases that had often been confused.",
  },
  // 123
  {
    id: "song-dynasty-founded",
    title: "The Song dynasty begins",
    year: 960,
    category: "world",
    emoji: "🏯",
    color: "coral",
    fact: "Song China became intensely urban and commercial, with giant cities, printed books, and expanding civil examinations.",
  },
  // 124
  {
    id: "cairo-founded",
    title: "Cairo is founded",
    year: 969,
    category: "world",
    emoji: "🏙️",
    color: "coral",
    fact: "The Fatimids built a new royal city beside older settlements that grew into today's Egyptian capital.",
  },
  // 125
  {
    id: "al-azhar-founded",
    title: "Al-Azhar is founded",
    year: 970,
    category: "culture",
    emoji: "🎓",
    color: "lilac",
    fact: "The Cairo mosque became a renowned center of Islamic learning that still teaches students today.",
  },
  // 126
  {
    id: "leif-erikson-vinland",
    title: "Norse voyagers reach North America",
    year: 1000,
    category: "discovery",
    emoji: "⛵",
    color: "mint",
    fact: "Voyages associated with Leif Erikson reached Vinland roughly five centuries before Columbus crossed the Atlantic.",
  },
  // 127
  {
    id: "tale-of-genji",
    title: "The Tale of Genji is written",
    year: 1008,
    category: "culture",
    emoji: "🌸",
    color: "lilac",
    fact: "Murasaki Shikibu's subtle portrait of court life is often called the world's first novel.",
  },
  // 128
  {
    id: "jiaozi-paper-money",
    title: "Government-backed paper money appears",
    year: 1023,
    category: "tech",
    emoji: "💴",
    color: "sky",
    fact: "Song authorities began issuing jiaozi notes in Sichuan, creating the first state-backed paper currency.",
  },
  // 129
  {
    id: "avicenna-canon-medicine",
    title: "Avicenna completes the Canon of Medicine",
    year: 1025,
    category: "discovery",
    emoji: "🩺",
    color: "mint",
    fact: "The Persian polymath organized medical knowledge into a reference used from the Islamic world to European universities.",
  },
  // 130
  {
    id: "chola-srivijaya-expedition",
    title: "A Chola fleet strikes Srivijaya",
    year: 1025,
    category: "world",
    emoji: "🚢",
    color: "coral",
    fact: "Rajendra Chola's ships raided ports across maritime Southeast Asia, demonstrating the reach of a South Indian navy.",
  },
  // 131
  {
    id: "al-biruni-book-india",
    title: "Al-Biruni completes his study of India",
    year: 1030,
    category: "discovery",
    emoji: "🔍",
    color: "mint",
    fact: "He learned Sanskrit and compared Indian religion, science, and custom with unusual care and intellectual openness.",
  },
  // 132
  {
    id: "bi-sheng-movable-type",
    title: "Bi Sheng invents movable type",
    year: 1040,
    category: "tech",
    emoji: "🔠",
    color: "sky",
    fact: "Bi Sheng arranged reusable baked-clay characters for printing about four centuries before Gutenberg's metal system.",
  },
  // 133
  {
    id: "crab-supernova-seen",
    title: "A supernova blazes in daylight",
    year: 1054,
    category: "discovery",
    emoji: "💫",
    color: "mint",
    fact: "Chinese observers tracked a guest star visible by day; its remains now glow as the Crab Nebula.",
  },
  // 134
  {
    id: "bayeux-tapestry-created",
    title: "The Bayeux Tapestry is stitched",
    year: 1070,
    category: "culture",
    emoji: "🧵",
    color: "lilac",
    fact: "Nearly seventy meters of embroidery turned England's Norman conquest into a vivid medieval visual narrative.",
  },
  // 135
  {
    id: "henry-iv-canossa",
    title: "An emperor waits at Canossa",
    year: 1077,
    category: "world",
    emoji: "❄️",
    color: "coral",
    fact: "Excommunicated Henry IV crossed the Alps and sought Pope Gregory VII's forgiveness during their power struggle.",
  },
  // 136
  {
    id: "jalali-calendar",
    title: "Omar Khayyam helps reform a calendar",
    year: 1079,
    category: "discovery",
    emoji: "📅",
    color: "mint",
    fact: "The Persian Jalali calendar used precise astronomical observation to keep the year closely aligned with the seasons.",
  },
  // 137
  {
    id: "domesday-book",
    title: "The Domesday survey is completed",
    year: 1086,
    category: "world",
    emoji: "📋",
    color: "coral",
    fact: "William the Conqueror's officials catalogued land, owners, livestock, and resources across most of England.",
  },
  // 138
  {
    id: "shen-kuo-dream-pool-essays",
    title: "Shen Kuo publishes the Dream Pool Essays",
    year: 1088,
    category: "discovery",
    emoji: "🧭",
    color: "mint",
    fact: "Shen described magnetic navigation, fossil evidence, printing, astronomy, and engineering in one extraordinary collection.",
  },
  // 139
  {
    id: "bologna-university-begins",
    title: "Bologna's Studium emerges",
    year: 1088,
    circa: true,
    category: "culture",
    emoji: "🎓",
    color: "lilac",
    fact: "Bologna's community of scholars became Europe's oldest continuously operating university by traditional foundation date.",
  },
  // 140
  {
    id: "cahokia-monks-mound",
    title: "Cahokia raises Monks Mound",
    year: 1100,
    category: "tech",
    emoji: "⛰️",
    color: "sky",
    fact: "Mississippian builders moved earth basket by basket to create the largest pre-Columbian earthwork north of Mexico.",
  },
  // 141
  {
    id: "great-zimbabwe-building-begins",
    title: "Great Zimbabwe begins to rise",
    year: 1100,
    category: "tech",
    emoji: "🧱",
    color: "sky",
    fact: "Shona builders stacked carefully shaped granite without mortar to create sweeping walls and elite enclosures.",
  },
  // 142
  {
    id: "angkor-wat-construction-begins",
    title: "Construction begins on Angkor Wat",
    year: 1113,
    category: "tech",
    emoji: "🛕",
    color: "sky",
    fact: "Suryavarman II's temple complex combined sacred symbolism with an immense moat, galleries, towers, and carved stories.",
  },
  // 143
  {
    id: "saint-denis-gothic-choir",
    title: "A Gothic choir opens at Saint-Denis",
    year: 1144,
    category: "tech",
    emoji: "🪟",
    color: "sky",
    fact: "Pointed arches and ribbed vaults freed walls for glowing stained glass, helping launch Gothic architecture.",
  },
  // 144
  {
    id: "hildegard-scivias",
    title: "Hildegard completes Scivias",
    year: 1151,
    category: "culture",
    emoji: "🌟",
    color: "lilac",
    fact: "Hildegard of Bingen transformed her vivid visions into an illustrated work of theology, cosmology, and music.",
  },
  // 145
  {
    id: "xativa-paper-industry",
    title: "Xàtiva becomes a European papermaking center",
    year: 1151,
    category: "tech",
    emoji: "📄",
    color: "sky",
    fact: "A thriving paper industry in Islamic Iberia helped the cheaper writing material spread farther through Europe.",
  },
  // 146
  {
    id: "saladin-takes-jerusalem",
    title: "Saladin retakes Jerusalem",
    year: 1187,
    category: "world",
    emoji: "🗝️",
    color: "coral",
    fact: "Jerusalem surrendered after negotiations, and Saladin generally allowed inhabitants to ransom themselves rather than face massacre.",
  },
  // 147
  {
    id: "fibonacci-liber-abaci",
    title: "Fibonacci publishes Liber Abaci",
    year: 1202,
    category: "discovery",
    emoji: "🧮",
    color: "mint",
    fact: "The book showed European merchants how efficient Hindu-Arabic numerals could be for currency, interest, and trade.",
  },
  // 148
  {
    id: "fourth-crusade-sacks-constantinople",
    title: "Crusaders sack Constantinople",
    year: 1204,
    category: "world",
    emoji: "🏛️",
    color: "coral",
    fact: "A crusade intended for Muslim-held territory instead looted the largest Christian city in Europe.",
  },
  // 149
  {
    id: "genghis-khan-proclaimed",
    title: "Genghis Khan unites the Mongols",
    year: 1206,
    category: "world",
    emoji: "🐎",
    color: "coral",
    fact: "Temüjin took the title Genghis Khan and organized rival steppe peoples into a disciplined expansionist state.",
  },
  // 150
  {
    id: "al-jazari-machines-book",
    title: "Al-Jazari illustrates remarkable machines",
    year: 1206,
    category: "tech",
    emoji: "🤖",
    color: "sky",
    fact: "His lavish engineering book described water clocks, pumps, automata, and a hand-washing servant that offered a towel.",
  },
  // 151
  {
    id: "goryeo-metal-movable-type",
    title: "Korea prints with movable metal type",
    year: 1234,
    category: "tech",
    emoji: "🔠",
    color: "sky",
    fact: "Goryeo printers cast reusable metal characters more than two centuries before movable metal type spread through Europe.",
  },
  // 152
  {
    id: "mali-empire-founded",
    title: "Sundiata founds the Mali Empire",
    year: 1235,
    category: "world",
    emoji: "🦁",
    color: "coral",
    fact: "Sundiata Keita united Manding territories into a West African empire enriched by gold and trans-Saharan trade.",
  },
  // 153
  {
    id: "mongols-sack-baghdad",
    title: "Mongol forces sack Baghdad",
    year: 1258,
    category: "world",
    emoji: "🏙️",
    color: "coral",
    fact: "Hülegü's army ended the Abbasid caliphate in Baghdad and devastated one of the world's great intellectual capitals.",
  },
  // 154
  {
    id: "yuan-dynasty-declared",
    title: "Kublai Khan declares the Yuan dynasty",
    year: 1271,
    category: "world",
    emoji: "🐎",
    color: "coral",
    fact: "Kublai adopted a Chinese dynastic name while ruling a realm tied to the wider Mongol world.",
  },
  // 155
  {
    id: "polynesians-settle-new-zealand",
    title: "Polynesian voyagers settle New Zealand",
    year: 1280,
    category: "discovery",
    emoji: "🛶",
    color: "mint",
    fact: "Skilled navigators crossed the southwest Pacific and founded the communities from which Māori culture developed.",
  },
  // 156
  {
    id: "marco-polo-returns-venice",
    title: "Marco Polo returns to Venice",
    year: 1295,
    category: "discovery",
    emoji: "🐫",
    color: "mint",
    fact: "After roughly 24 years away, Polo returned with stories of Yuan China that fascinated European readers.",
  },
  // 157
  {
    id: "ottoman-state-begins",
    title: "The Ottoman state begins",
    year: 1299,
    category: "world",
    emoji: "🌙",
    color: "coral",
    fact: "A small frontier principality associated with Osman I grew into an empire spanning three continents.",
  },
  // 158
  {
    id: "divine-comedy-begun",
    title: "Dante begins the Divine Comedy",
    year: 1308,
    category: "culture",
    emoji: "🔥",
    color: "lilac",
    fact: "Dante's journey through Hell, Purgatory, and Paradise helped make everyday Tuscan a prestigious literary language.",
  },
  // 159
  {
    id: "mansa-musa-pilgrimage",
    title: "Mansa Musa sets out for Mecca",
    year: 1324,
    category: "world",
    emoji: "✨",
    color: "coral",
    fact: "Mali's ruler traveled with such quantities of gold that chroniclers remembered the economic shock in Cairo for years.",
  },
  // 160
  {
    id: "ibn-battuta-leaves-tangier",
    title: "Ibn Battuta leaves home to travel",
    year: 1325,
    category: "discovery",
    emoji: "🧳",
    color: "mint",
    fact: "A pilgrimage from Tangier became a 29-year journey covering much of Africa and Eurasia.",
  },
  // 161
  {
    id: "ibn-battuta-visits-mali",
    title: "Ibn Battuta visits the Mali Empire",
    year: 1352,
    category: "culture",
    emoji: "🐪",
    color: "lilac",
    fact: "His account preserves rare eyewitness observations of Mali's court, customs, security, and Saharan connections.",
  },
  // 162
  {
    id: "ming-dynasty-founded",
    title: "The Ming dynasty begins",
    year: 1368,
    category: "world",
    emoji: "🐉",
    color: "coral",
    fact: "Zhu Yuanzhang drove the Yuan court from China and rose from extreme poverty to become the Hongwu Emperor.",
  },
  // 163
  {
    id: "catalan-atlas-created",
    title: "The Catalan Atlas maps a connected world",
    year: 1375,
    category: "discovery",
    emoji: "🗺️",
    color: "mint",
    fact: "Its richly painted sheets mixed navigation, geography, travelers' reports, and a famous image of Mansa Musa holding gold.",
  },
  // 164
  {
    id: "jikji-printed",
    title: "The Jikji is printed with metal type",
    year: 1377,
    category: "tech",
    emoji: "🖨️",
    color: "sky",
    fact: "This Korean Buddhist book is the oldest surviving work printed with movable metal type.",
  },
  // 165
  {
    id: "canterbury-tales-begun",
    title: "Chaucer begins The Canterbury Tales",
    year: 1387,
    category: "culture",
    emoji: "🐓",
    color: "lilac",
    fact: "A fictional group of pilgrims let Chaucer fill one journey with bawdy jokes, romance, sermons, and social satire.",
  },
  // 166
  {
    id: "joseon-dynasty-founded",
    title: "The Joseon dynasty begins",
    year: 1392,
    category: "world",
    emoji: "🏯",
    color: "coral",
    fact: "Joseon rule reshaped Korea through Confucian institutions and lasted for more than five centuries.",
  },
  // 167
  {
    id: "timur-sacks-delhi",
    title: "Timur sacks Delhi",
    year: 1398,
    category: "world",
    emoji: "🐎",
    color: "coral",
    fact: "Timur's invasion devastated the Delhi Sultanate even though he had no intention of governing India permanently.",
  },
  // 168
  {
    id: "zheng-he-first-voyage",
    title: "Zheng He's first fleet sails",
    year: 1405,
    category: "discovery",
    emoji: "⛵",
    color: "mint",
    fact: "Hundreds of Ming ships carried diplomats, goods, and soldiers through Southeast Asia and across the Indian Ocean.",
  },
  // 169
  {
    id: "yongle-encyclopedia-completed",
    title: "The Yongle Encyclopedia is completed",
    year: 1408,
    category: "culture",
    emoji: "📚",
    color: "lilac",
    fact: "More than two thousand scholars assembled an enormous handwritten collection covering nearly every branch of Chinese knowledge.",
  },
  // 170
  {
    id: "forbidden-city-completed",
    title: "The Forbidden City is completed",
    year: 1420,
    category: "tech",
    emoji: "🏯",
    color: "sky",
    fact: "A vast Beijing palace of nearly a thousand surviving buildings became the Ming and Qing imperial center.",
  },
  // 171
  {
    id: "cape-bojador-rounded",
    title: "Portuguese sailors round Cape Bojador",
    year: 1434,
    category: "discovery",
    emoji: "🌊",
    color: "mint",
    fact: "Gil Eanes passed a feared Atlantic cape, encouraging further Portuguese voyages down the West African coast.",
  },
  // 172
  {
    id: "florence-cathedral-dome",
    title: "Brunelleschi's great dome is completed",
    year: 1436,
    category: "tech",
    emoji: "🏗️",
    color: "sky",
    fact: "Florence's enormous masonry dome rose without the full wooden centering medieval builders normally relied on.",
  },
  // 173
  {
    id: "pachacuti-inca-expansion",
    title: "Pachacuti builds an Inca empire",
    year: 1438,
    category: "world",
    emoji: "☀️",
    color: "coral",
    fact: "After defending Cusco, Pachacuti reorganized the Inca state and launched its dramatic expansion across the Andes.",
  },
  // 174
  {
    id: "hangul-promulgated",
    title: "Korea publishes the Hangul alphabet",
    year: 1446,
    category: "tech",
    emoji: "한",
    color: "sky",
    fact: "King Sejong's scholars designed letters whose shapes reflect how the mouth forms their sounds.",
  },
  // 175
  {
    id: "constantinople-falls",
    title: "Constantinople falls to the Ottomans",
    year: 1453,
    category: "world",
    emoji: "🏰",
    color: "coral",
    fact: "Mehmed II captured the Byzantine capital after a 53-day siege and made it the center of his empire.",
  },
  // 176
  {
    id: "ottoman-great-bombard",
    title: "A giant cannon fires at Constantinople",
    year: 1453,
    category: "tech",
    emoji: "💥",
    color: "sky",
    fact: "Ottoman bombards hurled huge stone balls at walls once considered nearly impregnable, but reloading took hours.",
  },
  // 177
  {
    id: "wars-of-roses-begin",
    title: "The Wars of the Roses begin",
    year: 1455,
    category: "world",
    emoji: "🌹",
    color: "coral",
    fact: "Rival branches of England's royal family fought a shifting series of conflicts rather than one continuous war.",
  },
  // 178
  {
    id: "sistine-chapel-frescoes-unveiled",
    title: "The Sistine Chapel's wall frescoes open",
    year: 1482,
    category: "culture",
    emoji: "🎨",
    color: "lilac",
    fact: "Botticelli, Perugino, Ghirlandaio, and others decorated the chapel decades before Michelangelo painted its ceiling.",
  },
  // 179
  {
    id: "portuguese-reach-benin",
    title: "Portuguese envoys reach the Kingdom of Benin",
    year: 1486,
    category: "world",
    emoji: "🤝",
    color: "coral",
    fact: "The meeting opened direct Atlantic diplomacy and trade with a sophisticated West African kingdom and its immense capital.",
  },
  // 180
  {
    id: "dias-cape-good-hope",
    title: "Bartolomeu Dias rounds southern Africa",
    year: 1488,
    category: "discovery",
    emoji: "⛵",
    color: "mint",
    fact: "Dias proved the Atlantic and Indian oceans connected around Africa's southern tip.",
  },
  // 181
  {
    id: "granada-falls",
    title: "Granada falls",
    year: 1492,
    category: "world",
    emoji: "🗝️",
    color: "coral",
    fact: "The Nasrid ruler surrendered Granada, ending the last Muslim-ruled state in medieval Iberia.",
  },
  // 182
  {
    id: "erdapfel-globe",
    title: "The oldest surviving globe is made",
    year: 1492,
    category: "tech",
    emoji: "🌍",
    color: "sky",
    fact: "Martin Behaim's Erdapfel showed Europe, Africa, and Asia—but no Americas—just as Atlantic geography was changing.",
  },
  // 183
  {
    id: "treaty-of-tordesillas",
    title: "Spain and Portugal divide new claims",
    year: 1494,
    category: "world",
    emoji: "🗺️",
    color: "coral",
    fact: "The Treaty of Tordesillas drew an Atlantic line between two empires without consulting anyone who lived there.",
  },
  // 184
  {
    id: "da-gama-reaches-india",
    title: "Vasco da Gama reaches India by sea",
    year: 1498,
    category: "discovery",
    emoji: "⛵",
    color: "mint",
    fact: "His fleet reached Calicut after rounding Africa, violently reshaping trade across the Indian Ocean.",
  },
  // 185
  {
    id: "safavid-empire-founded",
    title: "The Safavid Empire begins",
    year: 1501,
    category: "world",
    emoji: "🕌",
    color: "coral",
    fact: "Shah Ismail I made Twelver Shi'ism central to a new Iranian empire, decisively shaping the region's identity.",
  },
  // 186
  {
    id: "michelangelo-david-unveiled",
    title: "Michelangelo's David is unveiled",
    year: 1504,
    category: "culture",
    emoji: "🗿",
    color: "lilac",
    fact: "Michelangelo rescued a tall block of marble two earlier sculptors had abandoned and carved Florence's defiant symbol.",
  },
  // 187
  {
    id: "waldseemuller-america-map",
    title: "A map labels America",
    year: 1507,
    category: "discovery",
    emoji: "🗺️",
    color: "mint",
    fact: "Martin Waldseemüller's world map first applied the name America to the newly mapped western lands.",
  },
  // 188
  {
    id: "school-of-athens-painted",
    title: "Raphael paints The School of Athens",
    year: 1511,
    category: "culture",
    emoji: "🎨",
    color: "lilac",
    fact: "Ancient philosophers gather in an imagined hall whose central figures, Plato and Aristotle, gesture toward rival worldviews.",
  },
  // 189
  {
    id: "portugal-captures-malacca",
    title: "Portugal captures Malacca",
    year: 1511,
    category: "world",
    emoji: "⚓",
    color: "coral",
    fact: "Taking the strategic Southeast Asian port gave Portugal a foothold beside one of global trade's busiest straits.",
  },
  // 190
  {
    id: "the-prince-written",
    title: "Machiavelli writes The Prince",
    year: 1513,
    category: "culture",
    emoji: "🦊",
    color: "lilac",
    fact: "Written after political disgrace, the blunt guide examined how rulers gain, use, and lose power.",
  },
  // 191
  {
    id: "piri-reis-map",
    title: "Piri Reis draws his Atlantic map",
    year: 1513,
    category: "discovery",
    emoji: "🗺️",
    color: "mint",
    fact: "The Ottoman admiral combined Portuguese and other sources into a surviving map fragment showing Atlantic coasts.",
  },
  // 192
  {
    id: "aztec-capital-falls",
    title: "The Aztec capital falls",
    year: 1521,
    category: "world",
    emoji: "🦅",
    color: "coral",
    fact: "Spanish forces and tens of thousands of Indigenous allies captured Tenochtitlan after siege, combat, and epidemic disease.",
  },
  // 193
  {
    id: "first-circumnavigation-completed",
    title: "The first circumnavigation is completed",
    year: 1522,
    category: "discovery",
    emoji: "🌍",
    color: "mint",
    fact: "The battered Victoria returned to Spain with 18 survivors from an expedition of roughly 270 people.",
  },
  // 194
  {
    id: "mughal-empire-founded",
    title: "Babur founds the Mughal Empire",
    year: 1526,
    category: "world",
    emoji: "🐘",
    color: "coral",
    fact: "Babur's smaller army used field artillery to defeat the Delhi sultan at Panipat and establish a new dynasty.",
  },
  // 195
  {
    id: "first-siege-vienna",
    title: "Ottoman forces besiege Vienna",
    year: 1529,
    category: "world",
    emoji: "🏰",
    color: "coral",
    fact: "Suleiman's campaign reached deep into central Europe but rain, supply trouble, and strong defenses forced a withdrawal.",
  },
  // 196
  {
    id: "treaty-of-zaragoza",
    title: "Spain and Portugal draw another world line",
    year: 1529,
    category: "world",
    emoji: "🌏",
    color: "coral",
    fact: "The Treaty of Zaragoza tried to settle competing claims in Asia by extending imperial division around the globe.",
  },
  // 197
  {
    id: "spanish-capture-cusco",
    title: "Spanish forces capture Cusco",
    year: 1533,
    category: "world",
    emoji: "☀️",
    color: "coral",
    fact: "The seizure of the Inca capital followed a civil war and the capture and execution of Emperor Atahualpa.",
  },
  // 198
  {
    id: "portuguese-reach-japan",
    title: "Portuguese traders reach Japan",
    year: 1543,
    category: "world",
    emoji: "⛵",
    color: "coral",
    fact: "A storm-blown trading vessel introduced sustained European contact—and matchlock firearms—to Japan.",
  },
  // 199
  {
    id: "vesalius-human-anatomy",
    title: "Vesalius publishes a new human anatomy",
    year: 1543,
    category: "discovery",
    emoji: "🫀",
    color: "mint",
    fact: "Direct dissection let Vesalius expose errors repeated for centuries from ancient animal anatomy.",
  },
  // 200
  {
    id: "potosi-silver-discovered",
    title: "Silver is discovered at Potosí",
    year: 1545,
    category: "world",
    emoji: "⛰️",
    color: "coral",
    fact: "The Bolivian mountain fueled global trade with immense silver output built on coerced Indigenous labor.",
  },
  // 201
  {
    id: "council-of-trent-opens",
    title: "The Council of Trent opens",
    year: 1545,
    category: "culture",
    emoji: "⛪",
    color: "lilac",
    fact: "Catholic leaders met across eighteen years to answer Protestant challenges and reshape worship, education, and church discipline.",
  },
  // 202
  {
    id: "ortelius-modern-atlas",
    title: "The first modern atlas is published",
    year: 1570,
    category: "discovery",
    emoji: "🗺️",
    color: "mint",
    fact: "Abraham Ortelius gathered uniformly sized maps into Theatrum Orbis Terrarum, a bestseller repeatedly expanded by its publisher.",
  },
  // 203
  {
    id: "tycho-supernova",
    title: "Tycho Brahe sees a new star",
    year: 1572,
    category: "discovery",
    emoji: "💫",
    color: "mint",
    fact: "The brilliant supernova showed no measurable parallax, challenging the belief that the distant heavens never changed.",
  },
  // 204
  {
    id: "akbar-ibadat-khana",
    title: "Akbar opens a house of religious debate",
    year: 1575,
    category: "culture",
    emoji: "🗣️",
    color: "lilac",
    fact: "At Fatehpur Sikri, Akbar invited Muslim, Hindu, Jain, Christian, and Zoroastrian thinkers into intense discussions.",
  },
  // 205
  {
    id: "spanish-armada-defeated",
    title: "The Spanish Armada is defeated",
    year: 1588,
    category: "world",
    emoji: "🌊",
    color: "coral",
    fact: "English attacks disrupted Spain's invasion fleet, but storms and a punishing route home destroyed even more ships.",
  },
  // 206
  {
    id: "journey-to-west-published",
    title: "Journey to the West is published",
    year: 1592,
    category: "culture",
    emoji: "🐒",
    color: "lilac",
    fact: "The mischievous, shape-shifting Monkey King helped turn a Buddhist pilgrimage into one of China's most beloved novels.",
  },
  // 207
  {
    id: "tokugawa-shogunate-begins",
    title: "The Tokugawa shogunate begins",
    year: 1603,
    category: "world",
    emoji: "🏯",
    color: "coral",
    fact: "Tokugawa Ieyasu became shogun after decades of civil conflict, beginning more than 250 years of relative stability.",
  },
  // 208
  {
    id: "kepler-supernova",
    title: "Kepler observes a supernova",
    year: 1604,
    category: "discovery",
    emoji: "🌟",
    color: "mint",
    fact: "The new star outshone Jupiter and remains the most recent supernova in our galaxy known to have been plainly visible.",
  },
  // 209
  {
    id: "relation-first-newspaper",
    title: "A weekly printed newspaper appears",
    year: 1605,
    category: "tech",
    emoji: "📰",
    color: "sky",
    fact: "Johann Carolus's Relation in Strasbourg is widely recognized as the first printed newspaper issued on a regular schedule.",
  },
  // 210
  {
    id: "kepler-first-two-laws",
    title: "Kepler publishes two laws of planetary motion",
    year: 1609,
    category: "discovery",
    emoji: "🪐",
    color: "mint",
    fact: "Kepler replaced perfect circular orbits with ellipses and showed that planets sweep equal areas in equal times.",
  },
  // 211
  {
    id: "king-james-bible",
    title: "The King James Bible is published",
    year: 1611,
    category: "culture",
    emoji: "📖",
    color: "lilac",
    fact: "Dozens of scholars produced an English translation whose rhythms profoundly influenced literature and everyday speech.",
  },
  // 212
  {
    id: "harvey-blood-circulation",
    title: "William Harvey explains blood circulation",
    year: 1628,
    category: "discovery",
    emoji: "🫀",
    color: "mint",
    fact: "Experiments and calculations showed the heart pumps the same blood continuously around the body.",
  },
  // 213
  {
    id: "taj-mahal-construction-begins",
    title: "Construction begins on the Taj Mahal",
    year: 1632,
    category: "tech",
    emoji: "🕌",
    color: "sky",
    fact: "Thousands of craftspeople combined stonework, calligraphy, gardens, and precise symmetry into Shah Jahan's memorial to Mumtaz Mahal.",
  },
  // 214
  {
    id: "pascal-mechanical-calculator",
    title: "Pascal builds a mechanical calculator",
    year: 1642,
    category: "tech",
    emoji: "🧮",
    color: "sky",
    fact: "Teenage Blaise Pascal designed geared machines to help his tax-official father add and subtract long columns of numbers.",
  },
  // 215
  {
    id: "qing-takes-beijing",
    title: "The Qing dynasty takes Beijing",
    year: 1644,
    category: "world",
    emoji: "🐉",
    color: "coral",
    fact: "Manchu forces entered the former Ming capital and established a dynasty that ruled China until 1912.",
  },
  // 216
  {
    id: "huygens-pendulum-clock",
    title: "Huygens builds a pendulum clock",
    year: 1656,
    category: "tech",
    emoji: "🕰️",
    color: "sky",
    fact: "The pendulum made clocks dramatically more accurate, shrinking daily errors from minutes toward seconds.",
  },
  // 217
  {
    id: "hooke-micrographia",
    title: "Micrographia reveals an invisible world",
    year: 1665,
    category: "discovery",
    emoji: "🔬",
    color: "mint",
    fact: "Robert Hooke's spectacular drawings showed readers a flea, a louse, and tiny compartments in cork he named cells.",
  },
  // 218
  {
    id: "philosophical-transactions",
    title: "A scientific journal begins publishing",
    year: 1665,
    category: "culture",
    emoji: "📄",
    color: "lilac",
    fact: "Philosophical Transactions created a regular public record for experiments and remains the longest-running scientific journal.",
  },
  // 219
  {
    id: "leeuwenhoek-sees-bacteria",
    title: "Leeuwenhoek sees bacteria",
    year: 1676,
    category: "discovery",
    emoji: "🦠",
    color: "mint",
    fact: "Peering through tiny handmade lenses, he found swarms of living 'animalcules' in water and dental plaque.",
  },
  // 220
  {
    id: "cristofori-piano",
    title: "The piano is invented",
    year: 1700,
    category: "tech",
    emoji: "🎹",
    color: "sky",
    fact: "Bartolomeo Cristofori's hammer mechanism let players control volume by striking keys softly or forcefully.",
  },
  // 221
  {
    id: "daily-courant-newspaper",
    title: "Britain's first daily newspaper appears",
    year: 1702,
    category: "culture",
    emoji: "📰",
    color: "lilac",
    fact: "The Daily Courant fit on a single sheet and promised readers facts without the editor's personal comments.",
  },
  // 222
  {
    id: "halley-predicts-comet-return",
    title: "Halley predicts a comet's return",
    year: 1705,
    category: "discovery",
    emoji: "☄️",
    color: "mint",
    fact: "Edmond Halley realized comets seen decades apart were one object and forecast its return for 1758.",
  },
  // 223
  {
    id: "longitude-prize-created",
    title: "Britain offers a prize for longitude",
    year: 1714,
    category: "tech",
    emoji: "🧭",
    color: "sky",
    fact: "Parliament offered a fortune for a practical way to find east-west position at sea, spurring precision timekeeping.",
  },
  // 224
  {
    id: "linnaeus-systema-naturae",
    title: "Linnaeus publishes Systema Naturae",
    year: 1735,
    category: "discovery",
    emoji: "🌿",
    color: "mint",
    fact: "The tiny first edition grew into a system that popularized two-part scientific names for living things.",
  },
  // 225
  {
    id: "celsius-temperature-scale",
    title: "Celsius proposes a temperature scale",
    year: 1742,
    category: "discovery",
    emoji: "🌡️",
    color: "mint",
    fact: "Anders Celsius's original scale placed water's boiling point at zero and freezing point at 100—the reverse of today.",
  },
  // 226
  {
    id: "lind-scurvy-test",
    title: "James Lind tests scurvy treatments",
    year: 1747,
    category: "discovery",
    emoji: "🍋",
    color: "mint",
    fact: "Sailors given oranges and lemons recovered fastest in a small comparative trial aboard HMS Salisbury.",
  },
  // 227
  {
    id: "encyclopedie-first-volume",
    title: "The Encyclopédie begins publication",
    year: 1751,
    category: "culture",
    emoji: "📚",
    color: "lilac",
    fact: "Diderot and d'Alembert's vast project mapped knowledge while treating craftspeople's practical skills as worthy of serious illustration.",
  },
  // 228
  {
    id: "lisbon-earthquake",
    title: "An earthquake devastates Lisbon",
    year: 1755,
    category: "world",
    emoji: "🌊",
    color: "coral",
    fact: "Shaking, fire, and tsunami struck on All Saints' Day, provoking new thinking about disasters, cities, and divine justice.",
  },
  // 229
  {
    id: "venus-transit-global-observations",
    title: "Astronomers chase a transit of Venus",
    year: 1761,
    category: "discovery",
    emoji: "🔭",
    color: "mint",
    fact: "Observers scattered across continents timed Venus crossing the Sun to estimate the Solar System's scale.",
  },
  // 230
  {
    id: "spinning-jenny-invented",
    title: "The spinning jenny is invented",
    year: 1764,
    category: "tech",
    emoji: "🧵",
    color: "sky",
    fact: "James Hargreaves's hand-powered machine let one worker spin several threads at once, accelerating textile production.",
  },
  // 231
  {
    id: "endeavour-voyage-begins",
    title: "The Endeavour sails into the Pacific",
    year: 1768,
    category: "discovery",
    emoji: "⛵",
    color: "mint",
    fact: "James Cook's expedition combined transit-of-Venus science with secret imperial orders to search and claim territory.",
  },
  // 232
  {
    id: "priestley-isolates-oxygen",
    title: "Priestley isolates oxygen",
    year: 1774,
    category: "discovery",
    emoji: "🫧",
    color: "mint",
    fact: "Joseph Priestley produced a gas that made flames burn fiercely, though he interpreted it using the fading phlogiston theory.",
  },
  // 233
  {
    id: "power-loom-patented",
    title: "The power loom is patented",
    year: 1785,
    category: "tech",
    emoji: "🧶",
    color: "sky",
    fact: "Edmund Cartwright's mechanized loom was initially flawed but helped push weaving from homes into factories.",
  },
  // 234
  {
    id: "mont-blanc-first-ascent",
    title: "Climbers reach the top of Mont Blanc",
    year: 1786,
    category: "discovery",
    emoji: "🏔️",
    color: "mint",
    fact: "Jacques Balmat and Michel Paccard completed the first recorded ascent of western Europe's highest mountain.",
  },
  // 235
  {
    id: "haitian-revolution-begins",
    title: "The Haitian Revolution begins",
    year: 1791,
    category: "world",
    emoji: "⛓️‍💥",
    color: "coral",
    fact: "Enslaved people in Saint-Domingue launched the only uprising to create a state permanently free from slavery.",
  },
  // 236
  {
    id: "vindication-rights-woman",
    title: "A Vindication of the Rights of Woman appears",
    year: 1792,
    category: "culture",
    emoji: "✍️",
    color: "lilac",
    fact: "Mary Wollstonecraft argued that women seemed inferior because society denied them serious education, not because nature did.",
  },
  // 237
  {
    id: "louvre-public-museum",
    title: "The Louvre opens as a public museum",
    year: 1793,
    category: "culture",
    emoji: "🖼️",
    color: "lilac",
    fact: "A former royal palace opened revolutionary France's national art collection to the public.",
  },
  // 238
  {
    id: "lithography-invented",
    title: "Lithography is invented",
    year: 1796,
    category: "tech",
    emoji: "🖨️",
    color: "sky",
    fact: "Alois Senefelder discovered that greasy ink and water could turn flat limestone into a printing surface.",
  },
  // 239
  {
    id: "volta-electric-battery",
    title: "Volta builds an electric battery",
    year: 1800,
    category: "tech",
    emoji: "🔋",
    color: "sky",
    fact: "Alternating metal discs separated by brine-soaked material produced the first steady source of electric current.",
  },
  // 240
  {
    id: "ceres-discovered",
    title: "Ceres is discovered",
    year: 1801,
    category: "discovery",
    emoji: "🪐",
    color: "mint",
    fact: "Giuseppe Piazzi found the first known object in the asteroid belt; today Ceres is classified as a dwarf planet.",
  },
  // 241
  {
    id: "haiti-declares-independence",
    title: "Haiti declares independence",
    year: 1804,
    category: "world",
    emoji: "🇭🇹",
    color: "coral",
    fact: "Haiti became the first independent state in Latin America and the first founded by formerly enslaved people.",
  },
  // 242
  {
    id: "clermont-commercial-steamboat",
    title: "A steamboat proves commercially viable",
    year: 1807,
    category: "tech",
    emoji: "🚢",
    color: "sky",
    fact: "Robert Fulton's North River Steamboat ran a regular passenger service, making steam travel a practical business.",
  },
  // 243
  {
    id: "grimms-fairy-tales",
    title: "The Grimms publish their fairy tales",
    year: 1812,
    category: "culture",
    emoji: "🏰",
    color: "lilac",
    fact: "Their first collection preserved oral stories but was repeatedly edited into forms considered more suitable for children.",
  },
  // 244
  {
    id: "tambora-eruption",
    title: "Mount Tambora erupts",
    year: 1815,
    category: "discovery",
    emoji: "🌋",
    color: "mint",
    fact: "History's largest directly observed eruption cooled the climate and helped make 1816 the Year Without a Summer.",
  },
  // 245
  {
    id: "champollion-hieroglyphs",
    title: "Champollion deciphers Egyptian hieroglyphs",
    year: 1822,
    category: "discovery",
    emoji: "🔤",
    color: "mint",
    fact: "By recognizing that signs could represent both sounds and ideas, Champollion made ancient Egyptian texts readable again.",
  },
  // 246
  {
    id: "braille-system-published",
    title: "Louis Braille publishes his reading system",
    year: 1829,
    category: "tech",
    emoji: "⠿",
    color: "sky",
    fact: "Six-dot cells let blind readers recognize letters rapidly with a fingertip and write them with simple tools.",
  },
  // 247
  {
    id: "faraday-electromagnetic-induction",
    title: "Faraday discovers electromagnetic induction",
    year: 1831,
    category: "discovery",
    emoji: "🧲",
    color: "mint",
    fact: "Moving magnetism could create electric current—the principle behind generators that power modern grids.",
  },
  // 248
  {
    id: "treaty-of-waitangi-signed",
    title: "The Treaty of Waitangi is signed",
    year: 1840,
    category: "world",
    emoji: "🤝",
    color: "coral",
    fact: "Māori and English texts differed in crucial ways, leaving sovereignty and authority contested in New Zealand ever since.",
  },
  // 249
  {
    id: "morse-telegraph-message",
    title: "Morse sends a long-distance telegraph message",
    year: 1844,
    category: "tech",
    emoji: "⚡",
    color: "sky",
    fact: "The words 'What hath God wrought' raced from Washington to Baltimore, demonstrating near-instant communication across distance.",
  },
  // 250
  {
    id: "elizabeth-blackwell-medical-degree",
    title: "Elizabeth Blackwell earns a medical degree",
    year: 1849,
    category: "culture",
    emoji: "👩‍⚕️",
    color: "lilac",
    fact: "Blackwell became the first woman in the United States to receive a medical degree after many schools rejected her.",
  },
] satisfies EventItem[];
