export type EventCategory = "tech" | "culture" | "discovery" | "world";

export type EventColor = "coral" | "sun" | "mint" | "sky" | "lilac";

export type EventItem = {
  id: string;
  title: string;
  year: number;
  category: EventCategory;
  emoji: string;
  color: EventColor;
  fact: string;
};

export type PracticePack = {
  id: "mixed" | "tech" | "culture" | "discovery";
  name: string;
  description: string;
  emoji: string;
  color: EventColor;
  categories: readonly EventCategory[];
  eventIds: readonly string[];
};

export const EVENTS: EventItem[] = [
  {
    id: "oxford-teaching",
    title: "Teaching begins at Oxford",
    year: 1096,
    category: "culture",
    emoji: "🎓",
    color: "lilac",
    fact: "Teaching existed at Oxford by 1096, more than two centuries before the Aztec capital was founded.",
  },
  {
    id: "first-crusade",
    title: "The First Crusade begins",
    year: 1096,
    category: "world",
    emoji: "🛡️",
    color: "coral",
    fact: "The First Crusade set out in the same year students were already gathering to learn at Oxford.",
  },
  {
    id: "magna-carta",
    title: "Magna Carta is sealed",
    year: 1215,
    category: "world",
    emoji: "📜",
    color: "coral",
    fact: "The famous charter was first a failed peace deal between King John and rebellious barons.",
  },
  {
    id: "tenochtitlan-founded",
    title: "Tenochtitlan is founded",
    year: 1325,
    category: "world",
    emoji: "🦅",
    color: "coral",
    fact: "Traditional histories date the island city to 1325, when Oxford had already taught students for over 200 years.",
  },
  {
    id: "gutenberg-press",
    title: "Gutenberg develops his press",
    year: 1450,
    category: "tech",
    emoji: "🖨️",
    color: "sky",
    fact: "Around 1450, reusable metal type made books dramatically faster to copy across Europe.",
  },
  {
    id: "columbus-caribbean",
    title: "Columbus reaches the Caribbean",
    year: 1492,
    category: "world",
    emoji: "⛵",
    color: "coral",
    fact: "The 1492 voyage reached islands already home to thriving Indigenous communities, not an empty new world.",
  },
  {
    id: "mona-lisa-begun",
    title: "Leonardo begins the Mona Lisa",
    year: 1503,
    category: "culture",
    emoji: "🖼️",
    color: "lilac",
    fact: "Leonardo kept refining the portrait for years instead of delivering it quickly to its likely patron.",
  },
  {
    id: "ninety-five-theses",
    title: "Luther publishes the 95 Theses",
    year: 1517,
    category: "world",
    emoji: "📌",
    color: "coral",
    fact: "Printing helped Luther's arguments spread across Europe with a speed earlier reformers never had.",
  },
  {
    id: "copernicus-revolutions",
    title: "Copernicus puts the Sun at the center",
    year: 1543,
    category: "discovery",
    emoji: "☀️",
    color: "mint",
    fact: "His landmark book appeared in the final year of his life and rearranged humanity's place in the cosmos.",
  },
  {
    id: "gregorian-calendar",
    title: "The Gregorian calendar begins",
    year: 1582,
    category: "discovery",
    emoji: "📅",
    color: "mint",
    fact: "Countries adopting the new calendar skipped ten dates to pull the seasons back into alignment.",
  },
  {
    id: "don-quixote",
    title: "Don Quixote is published",
    year: 1605,
    category: "culture",
    emoji: "🐴",
    color: "lilac",
    fact: "Its hero becomes a legend by mistaking ordinary windmills for terrifying giants.",
  },
  {
    id: "jamestown-founded",
    title: "Jamestown is founded",
    year: 1607,
    category: "world",
    emoji: "🏕️",
    color: "coral",
    fact: "England's first lasting American colony nearly collapsed during its brutal early winters.",
  },
  {
    id: "galileo-jupiter-moons",
    title: "Galileo spots moons around Jupiter",
    year: 1610,
    category: "discovery",
    emoji: "🔭",
    color: "mint",
    fact: "Four tiny lights orbiting Jupiter proved that not everything in the heavens circled Earth.",
  },
  {
    id: "shakespeare-first-folio",
    title: "Shakespeare's First Folio appears",
    year: 1623,
    category: "culture",
    emoji: "🎭",
    color: "lilac",
    fact: "Without this posthumous collection, plays including Macbeth may have disappeared entirely.",
  },
  {
    id: "harvard-founded",
    title: "Harvard is founded",
    year: 1636,
    category: "culture",
    emoji: "📚",
    color: "lilac",
    fact: "Harvard opened with one teacher and a tiny handful of students rather than a grand campus.",
  },
  {
    id: "great-fire-london",
    title: "The Great Fire of London",
    year: 1666,
    category: "world",
    emoji: "🔥",
    color: "coral",
    fact: "The blaze destroyed thousands of buildings yet officially recorded remarkably few deaths.",
  },
  {
    id: "newton-principia",
    title: "Newton publishes Principia",
    year: 1687,
    category: "discovery",
    emoji: "🍎",
    color: "mint",
    fact: "One mathematical framework explained both falling objects and the Moon's path around Earth.",
  },
  {
    id: "newcomen-engine",
    title: "The Newcomen steam engine",
    year: 1712,
    category: "tech",
    emoji: "⚙️",
    color: "sky",
    fact: "This giant early engine was built to pump water from mines, not to pull trains.",
  },
  {
    id: "mozart-born",
    title: "Mozart is born",
    year: 1756,
    category: "culture",
    emoji: "🎼",
    color: "lilac",
    fact: "Mozart was performing for European royalty while still young enough to lose his baby teeth.",
  },
  {
    id: "watt-steam-patent",
    title: "Watt patents his steam upgrade",
    year: 1769,
    category: "tech",
    emoji: "♨️",
    color: "sky",
    fact: "Watt's separate condenser saved so much fuel that it helped steam power escape the mines.",
  },
  {
    id: "napoleon-born",
    title: "Napoleon is born",
    year: 1769,
    category: "world",
    emoji: "🎩",
    color: "coral",
    fact: "Napoleon arrived the same year James Watt patented the steam-engine improvement that powered an industrial age.",
  },
  {
    id: "us-declaration",
    title: "The U.S. Declaration is adopted",
    year: 1776,
    category: "world",
    emoji: "🪶",
    color: "coral",
    fact: "The declaration and Adam Smith's Wealth of Nations appeared on opposite sides of the Atlantic in the same year.",
  },
  {
    id: "wealth-of-nations",
    title: "The Wealth of Nations is published",
    year: 1776,
    category: "culture",
    emoji: "📈",
    color: "lilac",
    fact: "Adam Smith's famous economics book landed the same year the United States declared independence.",
  },
  {
    id: "uranus-discovered",
    title: "Uranus is discovered",
    year: 1781,
    category: "discovery",
    emoji: "🪐",
    color: "mint",
    fact: "Uranus was the first planet found with a telescope, suddenly making the known Solar System much larger.",
  },
  {
    id: "first-balloon-flight",
    title: "First crewed hot-air balloon flight",
    year: 1783,
    category: "tech",
    emoji: "🎈",
    color: "sky",
    fact: "The first free-flying passengers drifted over Paris for about 25 minutes in a fire-powered fabric balloon.",
  },
  {
    id: "french-revolution",
    title: "The French Revolution begins",
    year: 1789,
    category: "world",
    emoji: "🏰",
    color: "coral",
    fact: "The storming of the Bastille freed only seven prisoners but became a symbol powerful enough to reshape Europe.",
  },
  {
    id: "smallpox-vaccine",
    title: "The first vaccine is tested",
    year: 1796,
    category: "discovery",
    emoji: "💉",
    color: "mint",
    fact: "Edward Jenner used cowpox to protect against smallpox, giving vaccination its cow-inspired name.",
  },
  {
    id: "steam-locomotive",
    title: "First steam locomotive journey",
    year: 1804,
    category: "tech",
    emoji: "🚂",
    color: "sky",
    fact: "Trevithick's locomotive hauled iron and passengers but was too heavy for the brittle rails beneath it.",
  },
  {
    id: "frankenstein-published",
    title: "Frankenstein is published",
    year: 1818,
    category: "culture",
    emoji: "⚡",
    color: "lilac",
    fact: "Mary Shelley's novel first appeared anonymously when she was only 20 years old.",
  },
  {
    id: "public-railway",
    title: "First public steam railway opens",
    year: 1825,
    category: "tech",
    emoji: "🛤️",
    color: "sky",
    fact: "The opening train carried both coal wagons and hundreds of excited passengers clinging wherever they could.",
  },
  {
    id: "photography-announced",
    title: "Photography is announced to the world",
    year: 1839,
    category: "tech",
    emoji: "📷",
    color: "sky",
    fact: "Early daguerreotype portraits demanded long, statue-still poses because exposure took so much time.",
  },
  {
    id: "first-christmas-card",
    title: "The first Christmas card is sent",
    year: 1843,
    category: "culture",
    emoji: "💌",
    color: "lilac",
    fact: "The first commercial card caused a tiny scandal because its illustration showed a child tasting wine.",
  },
  {
    id: "neptune-discovered",
    title: "Neptune is discovered",
    year: 1846,
    category: "discovery",
    emoji: "🔵",
    color: "mint",
    fact: "Astronomers found Neptune almost exactly where mathematics predicted an unseen planet should be.",
  },
  {
    id: "great-exhibition",
    title: "The Great Exhibition opens",
    year: 1851,
    category: "culture",
    emoji: "💎",
    color: "lilac",
    fact: "Its Crystal Palace used so much glass that visitors compared the vast building to a greenhouse.",
  },
  {
    id: "origin-of-species",
    title: "On the Origin of Species is published",
    year: 1859,
    category: "discovery",
    emoji: "🐦",
    color: "mint",
    fact: "Darwin waited more than two decades after his Beagle voyage before publishing his case for natural selection.",
  },
  {
    id: "london-underground",
    title: "The London Underground opens",
    year: 1863,
    category: "tech",
    emoji: "🚇",
    color: "sky",
    fact: "The world's first underground railway initially used smoky steam trains beneath the streets.",
  },
  {
    id: "alice-wonderland",
    title: "Alice in Wonderland is published",
    year: 1865,
    category: "culture",
    emoji: "🐇",
    color: "lilac",
    fact: "Lewis Carroll's nonsense adventure arrived while London's underground trains were already running.",
  },
  {
    id: "periodic-table",
    title: "Mendeleev presents the periodic table",
    year: 1869,
    category: "discovery",
    emoji: "🧪",
    color: "mint",
    fact: "He deliberately left gaps for elements nobody had found yet, then predicted what they would be like.",
  },
  {
    id: "telephone-patent",
    title: "Bell patents the telephone",
    year: 1876,
    category: "tech",
    emoji: "☎️",
    color: "sky",
    fact: "Bell's patent was filed on the very same day as a rival inventor's telephone paperwork.",
  },
  {
    id: "phonograph",
    title: "Edison unveils the phonograph",
    year: 1877,
    category: "tech",
    emoji: "📻",
    color: "sky",
    fact: "The first machine to play back recorded sound used a sheet of tinfoil wrapped around a cylinder.",
  },
  {
    id: "incandescent-light",
    title: "Edison demonstrates a lasting light bulb",
    year: 1879,
    category: "tech",
    emoji: "💡",
    color: "sun",
    fact: "The breakthrough was not the first bulb, but a practical filament that glowed for many hours.",
  },
  {
    id: "benz-car",
    title: "Benz patents the motorcar",
    year: 1886,
    category: "tech",
    emoji: "🚗",
    color: "sky",
    fact: "The three-wheeled Patent-Motorwagen arrived in the same year Coca-Cola was first served.",
  },
  {
    id: "coca-cola",
    title: "Coca-Cola is first served",
    year: 1886,
    category: "culture",
    emoji: "🥤",
    color: "lilac",
    fact: "The first glasses were sold at an Atlanta pharmacy while the earliest patented car was taking shape in Germany.",
  },
  {
    id: "kodak-camera",
    title: "The Kodak camera goes on sale",
    year: 1888,
    category: "tech",
    emoji: "📸",
    color: "sky",
    fact: "Customers mailed the entire camera back to Kodak to have their hundred pictures developed.",
  },
  {
    id: "eiffel-tower",
    title: "The Eiffel Tower opens",
    year: 1889,
    category: "culture",
    emoji: "🗼",
    color: "sun",
    fact: "The Eiffel Tower opened in 1889, just months before Nintendo began making playing cards.",
  },
  {
    id: "nintendo-founded",
    title: "Nintendo is founded",
    year: 1889,
    category: "culture",
    emoji: "🎴",
    color: "coral",
    fact: "Nintendo began as a handmade playing-card company in the same year the Eiffel Tower opened.",
  },
  {
    id: "x-rays",
    title: "X-rays are discovered",
    year: 1895,
    category: "discovery",
    emoji: "🩻",
    color: "mint",
    fact: "Röntgen's haunting first medical image showed the bones in his wife's hand and her wedding ring.",
  },
  {
    id: "paid-cinema-screening",
    title: "Cinema gets a paying audience",
    year: 1895,
    category: "culture",
    emoji: "🎞️",
    color: "lilac",
    fact: "The Lumière brothers sold tickets to moving pictures in Paris the same year X-rays revealed hidden bones.",
  },
  {
    id: "modern-olympics",
    title: "The first modern Olympics",
    year: 1896,
    category: "culture",
    emoji: "🏅",
    color: "sun",
    fact: "The Athens winners received silver medals because today's gold-first tradition had not been invented.",
  },
  {
    id: "transatlantic-radio",
    title: "Radio crosses the Atlantic",
    year: 1901,
    category: "tech",
    emoji: "📡",
    color: "sky",
    fact: "Marconi listened for a faint Morse-code S in Newfoundland after it traveled from Cornwall without wires.",
  },
  {
    id: "wright-flight",
    title: "The first powered airplane flight",
    year: 1903,
    category: "tech",
    emoji: "✈️",
    color: "sky",
    fact: "The Wright brothers' first flight lasted only 12 seconds and covered less than a modern airliner's wingspan.",
  },
  {
    id: "special-relativity",
    title: "Einstein publishes special relativity",
    year: 1905,
    category: "discovery",
    emoji: "⏱️",
    color: "mint",
    fact: "Einstein reshaped space and time while working at a patent office, not a university.",
  },
  {
    id: "model-t",
    title: "The Ford Model T launches",
    year: 1908,
    category: "tech",
    emoji: "🚙",
    color: "sky",
    fact: "The Model T came before Ford's moving assembly line, which later made it much cheaper.",
  },
  {
    id: "south-pole",
    title: "Humans reach the South Pole",
    year: 1911,
    category: "discovery",
    emoji: "🧭",
    color: "mint",
    fact: "Amundsen's team arrived 34 days before Scott's party by relying heavily on skis and sled dogs.",
  },
  {
    id: "oreo-debut",
    title: "The Oreo cookie debuts",
    year: 1912,
    category: "culture",
    emoji: "🍪",
    color: "lilac",
    fact: "Oreo cookies first went on sale only weeks before Titanic began its doomed maiden voyage.",
  },
  {
    id: "titanic-sinks",
    title: "Titanic sinks",
    year: 1912,
    category: "world",
    emoji: "🚢",
    color: "coral",
    fact: "Titanic sank in the same spring that the brand-new Oreo cookie reached American shops.",
  },
  {
    id: "first-crossword",
    title: "The first modern crossword appears",
    year: 1913,
    category: "culture",
    emoji: "✏️",
    color: "lilac",
    fact: "Arthur Wynne's diamond-shaped Word-Cross appeared in the Sunday fun section of the New York World.",
  },
  {
    id: "first-world-war",
    title: "The First World War begins",
    year: 1914,
    category: "world",
    emoji: "🌍",
    color: "coral",
    fact: "A chain of alliance declarations turned a crisis in the Balkans into a global war within weeks.",
  },
  {
    id: "tutankhamun-tomb",
    title: "Tutankhamun's tomb is uncovered",
    year: 1922,
    category: "discovery",
    emoji: "⚱️",
    color: "mint",
    fact: "A water boy reportedly found the step that led archaeologists to the nearly intact royal tomb.",
  },
  {
    id: "great-gatsby",
    title: "The Great Gatsby is published",
    year: 1925,
    category: "culture",
    emoji: "🥂",
    color: "lilac",
    fact: "Fitzgerald's now-famous novel sold modestly in his lifetime and surged only after his death.",
  },
  {
    id: "talking-picture",
    title: "The first feature-length talkie arrives",
    year: 1927,
    category: "culture",
    emoji: "🎙️",
    color: "lilac",
    fact: "The Jazz Singer was mostly silent, but a few synchronized spoken lines transformed the movie business.",
  },
  {
    id: "sliced-bread",
    title: "Pre-sliced bread goes on sale",
    year: 1928,
    category: "tech",
    emoji: "🍞",
    color: "sun",
    fact: "Sliced bread reached shops in 1928, the same year Mickey Mouse debuted and penicillin was noticed.",
  },
  {
    id: "mickey-mouse",
    title: "Mickey Mouse makes his debut",
    year: 1928,
    category: "culture",
    emoji: "🐭",
    color: "lilac",
    fact: "Steamboat Willie premiered in the same year sliced bread arrived and Fleming spotted penicillin.",
  },
  {
    id: "penicillin-discovered",
    title: "Penicillin is discovered",
    year: 1928,
    category: "discovery",
    emoji: "🦠",
    color: "mint",
    fact: "A contaminated dish led Fleming to penicillin in the same year Mickey Mouse and sliced bread appeared.",
  },
  {
    id: "pluto-discovered",
    title: "Pluto is discovered",
    year: 1930,
    category: "discovery",
    emoji: "🌑",
    color: "mint",
    fact: "An 11-year-old British schoolgirl suggested the name Pluto and received a small reward from her grandfather.",
  },
  {
    id: "lego-founded",
    title: "LEGO is founded",
    year: 1932,
    category: "culture",
    emoji: "🧱",
    color: "lilac",
    fact: "LEGO began with wooden toys; its name comes from Danish words meaning play well.",
  },
  {
    id: "bbc-television",
    title: "Regular BBC television begins",
    year: 1936,
    category: "tech",
    emoji: "📺",
    color: "sky",
    fact: "Britain's early high-definition service counted a 240-line picture as one of its competing standards.",
  },
  {
    id: "golden-gate-bridge",
    title: "The Golden Gate Bridge opens",
    year: 1937,
    category: "tech",
    emoji: "🌉",
    color: "sky",
    fact: "Its vivid International Orange coating was chosen partly because it stayed visible through San Francisco fog.",
  },
  {
    id: "superman-debut",
    title: "Superman makes his debut",
    year: 1938,
    category: "culture",
    emoji: "🦸",
    color: "lilac",
    fact: "Superman's creators sold the character rights for $130 before he helped create the superhero genre.",
  },
  {
    id: "wizard-of-oz",
    title: "The Wizard of Oz premieres",
    year: 1939,
    category: "culture",
    emoji: "👠",
    color: "lilac",
    fact: "Dorothy entered Technicolor Oz in cinemas the same year Europe entered the Second World War.",
  },
  {
    id: "second-world-war",
    title: "The Second World War begins",
    year: 1939,
    category: "world",
    emoji: "🌐",
    color: "coral",
    fact: "War began in Europe the same year movie audiences first followed the yellow brick road to Oz.",
  },
  {
    id: "mcdonalds-opens",
    title: "The first McDonald's opens",
    year: 1940,
    category: "culture",
    emoji: "🍔",
    color: "sun",
    fact: "The original restaurant began as a barbecue drive-in before the brothers rebuilt it around speedy burgers.",
  },
  {
    id: "first-nuclear-reactor",
    title: "The first nuclear reactor goes critical",
    year: 1942,
    category: "discovery",
    emoji: "⚛️",
    color: "mint",
    fact: "Chicago Pile-1 achieved its chain reaction beneath the stands of a university football field.",
  },
  {
    id: "microwave-oven-idea",
    title: "Microwave cooking is discovered",
    year: 1945,
    category: "tech",
    emoji: "🍫",
    color: "sky",
    fact: "Percy Spencer noticed radar microwaves had melted a candy bar in his pocket and started experimenting with food.",
  },
  {
    id: "second-world-war-ends",
    title: "The Second World War ends",
    year: 1945,
    category: "world",
    emoji: "🕊️",
    color: "coral",
    fact: "The war ended in the same year an accidentally melted candy bar inspired microwave cooking.",
  },
  {
    id: "transistor",
    title: "The transistor is invented",
    year: 1947,
    category: "tech",
    emoji: "🔌",
    color: "sky",
    fact: "The tiny switch that powers modern electronics began as a clumsy cluster of wires, gold foil, and germanium.",
  },
  {
    id: "dna-double-helix",
    title: "The DNA double helix is described",
    year: 1953,
    category: "discovery",
    emoji: "🧬",
    color: "mint",
    fact: "The famous model depended on X-ray evidence produced by Rosalind Franklin and her colleagues.",
  },
  {
    id: "godzilla-premiere",
    title: "Godzilla stomps into cinemas",
    year: 1954,
    category: "culture",
    emoji: "🦖",
    color: "lilac",
    fact: "The monster's roar was created by dragging a resin-coated glove along a double bass string.",
  },
  {
    id: "disneyland-opens",
    title: "Disneyland opens",
    year: 1955,
    category: "culture",
    emoji: "🏰",
    color: "lilac",
    fact: "Opening day was so overcrowded and chaotic that Disney staff later nicknamed it Black Sunday.",
  },
  {
    id: "sputnik",
    title: "Sputnik reaches orbit",
    year: 1957,
    category: "discovery",
    emoji: "🛰️",
    color: "mint",
    fact: "The first artificial satellite was a polished metal ball whose simple beeps could be heard by radio amateurs.",
  },
  {
    id: "lego-brick-patent",
    title: "The modern LEGO brick is patented",
    year: 1958,
    category: "tech",
    emoji: "🧱",
    color: "sky",
    fact: "A brick made in 1958 still clicks neatly into one made today because the core design never changed.",
  },
  {
    id: "first-laser",
    title: "The first working laser",
    year: 1960,
    category: "tech",
    emoji: "🔴",
    color: "sky",
    fact: "The first laser used a synthetic ruby and was initially dismissed as a solution looking for a problem.",
  },
  {
    id: "first-human-space",
    title: "The first human enters space",
    year: 1961,
    category: "discovery",
    emoji: "👨‍🚀",
    color: "mint",
    fact: "Yuri Gagarin completed one orbit in a capsule whose controls were mostly locked for the flight.",
  },
  {
    id: "beatles-first-single",
    title: "The Beatles release their first single",
    year: 1962,
    category: "culture",
    emoji: "🎸",
    color: "lilac",
    fact: "Love Me Do reached shops in the same year programmers were battling spaceships in the game Spacewar!",
  },
  {
    id: "spacewar",
    title: "Spacewar! is created",
    year: 1962,
    category: "tech",
    emoji: "🕹️",
    color: "sky",
    fact: "The influential early game appeared on a room-sized computer as the Beatles released their first single.",
  },
  {
    id: "compact-cassette",
    title: "The compact cassette is introduced",
    year: 1963,
    category: "tech",
    emoji: "📼",
    color: "sky",
    fact: "Philips licensed the cassette format freely, helping mixtapes spread across the world.",
  },
  {
    id: "bullet-train",
    title: "The bullet train launches",
    year: 1964,
    category: "tech",
    emoji: "🚄",
    color: "sky",
    fact: "Japan's Shinkansen began days before the Tokyo Olympics and immediately cut hours from the journey to Osaka.",
  },
  {
    id: "star-trek",
    title: "Star Trek premieres",
    year: 1966,
    category: "culture",
    emoji: "🖖",
    color: "lilac",
    fact: "The original series struggled in the ratings, yet fan letters helped rescue it from early cancellation.",
  },
  {
    id: "heart-transplant",
    title: "The first human heart transplant",
    year: 1967,
    category: "discovery",
    emoji: "🫀",
    color: "mint",
    fact: "The operation proved a heart could be transplanted even though its first recipient survived only 18 days.",
  },
  {
    id: "moon-landing",
    title: "Humans land on the Moon",
    year: 1969,
    category: "discovery",
    emoji: "🌕",
    color: "sun",
    fact: "Apollo 11 landed in the same year the first messages traveled across ARPANET, an ancestor of the internet.",
  },
  {
    id: "arpanet",
    title: "The first ARPANET message",
    year: 1969,
    category: "tech",
    emoji: "🖥️",
    color: "sky",
    fact: "The intended word was LOGIN, but the network crashed after only LO in the year humans reached the Moon.",
  },
  {
    id: "microprocessor",
    title: "The first commercial microprocessor",
    year: 1971,
    category: "tech",
    emoji: "💾",
    color: "sky",
    fact: "Intel's 4004 was built for a calculator yet helped put a programmable computer onto one tiny chip.",
  },
  {
    id: "network-email",
    title: "The first network email is sent",
    year: 1971,
    category: "tech",
    emoji: "📧",
    color: "sky",
    fact: "Ray Tomlinson chose the @ symbol because it was rarely used in names and neatly meant at a host computer.",
  },
  {
    id: "pong",
    title: "Pong arrives in arcades",
    year: 1972,
    category: "culture",
    emoji: "🏓",
    color: "lilac",
    fact: "The test machine reportedly stopped working because its coin box became packed too full of quarters.",
  },
  {
    id: "mobile-phone-call",
    title: "The first handheld mobile call",
    year: 1973,
    category: "tech",
    emoji: "📱",
    color: "sky",
    fact: "Motorola's Martin Cooper used the first call to ring a rival researcher and tell him it worked.",
  },
  {
    id: "rubiks-cube",
    title: "The Rubik's Cube is invented",
    year: 1974,
    category: "culture",
    emoji: "🟨",
    color: "lilac",
    fact: "Ernő Rubik needed about a month to solve his own twisting puzzle for the first time.",
  },
  {
    id: "microsoft-founded",
    title: "Microsoft is founded",
    year: 1975,
    category: "tech",
    emoji: "🪟",
    color: "sky",
    fact: "Microsoft began in the same year that a giant mechanical shark turned Jaws into a blockbuster.",
  },
  {
    id: "jaws-premiere",
    title: "Jaws hits cinemas",
    year: 1975,
    category: "culture",
    emoji: "🦈",
    color: "lilac",
    fact: "The unreliable mechanical shark forced Spielberg to show it less, making the film far more suspenseful.",
  },
  {
    id: "apple-founded",
    title: "Apple is founded",
    year: 1976,
    category: "tech",
    emoji: "🍏",
    color: "sky",
    fact: "The Apple I was sold as a bare circuit board, so buyers supplied their own keyboard, screen, and case.",
  },
  {
    id: "star-wars",
    title: "Star Wars opens",
    year: 1977,
    category: "culture",
    emoji: "⚔️",
    color: "lilac",
    fact: "Star Wars reached cinemas in the same year the Voyager probes began their real journey to the outer planets.",
  },
  {
    id: "voyager-launch",
    title: "The Voyager probes launch",
    year: 1977,
    category: "discovery",
    emoji: "🌌",
    color: "mint",
    fact: "Each probe carried a golden record of Earth's sounds while Star Wars filled cinemas back home.",
  },
  {
    id: "first-ivf-baby",
    title: "The first IVF baby is born",
    year: 1978,
    category: "discovery",
    emoji: "👶",
    color: "mint",
    fact: "Louise Brown's birth followed a natural delivery and showed that laboratory fertilization could lead to healthy life.",
  },
  {
    id: "sony-walkman",
    title: "The Sony Walkman launches",
    year: 1979,
    category: "tech",
    emoji: "🎧",
    color: "sky",
    fact: "Sony doubted people would buy a tape player that could not record, then sold hundreds of millions.",
  },
  {
    id: "pac-man",
    title: "Pac-Man enters arcades",
    year: 1980,
    category: "culture",
    emoji: "🟡",
    color: "lilac",
    fact: "Pac-Man was designed to welcome a wider audience than the era's many space-shooting games.",
  },
  {
    id: "mtv-launch",
    title: "MTV launches",
    year: 1981,
    category: "culture",
    emoji: "🎬",
    color: "lilac",
    fact: "The channel began with Video Killed the Radio Star, a joke so perfect it sounded planned by history.",
  },
  {
    id: "compact-disc",
    title: "The compact disc goes on sale",
    year: 1982,
    category: "tech",
    emoji: "💿",
    color: "sky",
    fact: "The first commercial CD album released in Japan was Billy Joel's 52nd Street.",
  },
  {
    id: "internet-tcp-ip",
    title: "The internet adopts TCP/IP",
    year: 1983,
    category: "tech",
    emoji: "🌐",
    color: "sky",
    fact: "A coordinated protocol switch on New Year's Day let different networks speak one shared language.",
  },
  {
    id: "macintosh",
    title: "The Macintosh launches",
    year: 1984,
    category: "tech",
    emoji: "🖱️",
    color: "sky",
    fact: "The Macintosh brought a mouse-driven desktop to mainstream buyers in the same year Tetris was created.",
  },
  {
    id: "tetris",
    title: "Tetris is created",
    year: 1984,
    category: "culture",
    emoji: "🧩",
    color: "lilac",
    fact: "Tetris was built on a Soviet research computer in the same year Apple's Macintosh went on sale.",
  },
  {
    id: "super-mario-bros",
    title: "Super Mario Bros. launches",
    year: 1985,
    category: "culture",
    emoji: "🍄",
    color: "lilac",
    fact: "Mario's mustache, hat, and overalls all began as clever shortcuts for drawing a tiny pixel character.",
  },
  {
    id: "chernobyl",
    title: "The Chernobyl disaster",
    year: 1986,
    category: "world",
    emoji: "☢️",
    color: "coral",
    fact: "The plant's other reactors continued generating electricity for years after the catastrophic explosion.",
  },
  {
    id: "world-wide-web-proposal",
    title: "The World Wide Web is proposed",
    year: 1989,
    category: "tech",
    emoji: "🕸️",
    color: "sky",
    fact: "Tim Berners-Lee proposed the web in the same year the Berlin Wall fell and The Simpsons debuted.",
  },
  {
    id: "berlin-wall-falls",
    title: "The Berlin Wall falls",
    year: 1989,
    category: "world",
    emoji: "🧱",
    color: "coral",
    fact: "A confused press-conference answer helped send crowds to the checkpoints while the web was only a proposal.",
  },
  {
    id: "simpsons-premiere",
    title: "The Simpsons premieres",
    year: 1989,
    category: "culture",
    emoji: "🍩",
    color: "lilac",
    fact: "The Simpsons became a full series in the year the Berlin Wall fell and the web was proposed.",
  },
  {
    id: "hubble-launch",
    title: "The Hubble telescope launches",
    year: 1990,
    category: "discovery",
    emoji: "🔭",
    color: "mint",
    fact: "Hubble reached orbit with a flawed mirror, and astronauts later fitted it with corrective optics like glasses.",
  },
  {
    id: "first-website",
    title: "The first website goes online",
    year: 1991,
    category: "tech",
    emoji: "💻",
    color: "sky",
    fact: "The first site simply explained what the World Wide Web was and how other people could join it.",
  },
  {
    id: "first-sms",
    title: "The first text message is sent",
    year: 1992,
    category: "tech",
    emoji: "💬",
    color: "sky",
    fact: "The first SMS said Merry Christmas and traveled from a computer to a mobile phone.",
  },
  {
    id: "jurassic-park",
    title: "Jurassic Park opens",
    year: 1993,
    category: "culture",
    emoji: "🦕",
    color: "lilac",
    fact: "Jurassic Park's digital dinosaurs arrived in the same year the Mosaic browser made the web easier to explore.",
  },
  {
    id: "mosaic-browser",
    title: "The Mosaic web browser launches",
    year: 1993,
    category: "tech",
    emoji: "🌍",
    color: "sky",
    fact: "Mosaic helped ordinary users see pictures and text together online while Jurassic Park filled cinemas.",
  },
  {
    id: "playstation-launch",
    title: "The PlayStation launches",
    year: 1994,
    category: "culture",
    emoji: "🎮",
    color: "lilac",
    fact: "Sony entered gaming after an attempted CD partnership with Nintendo famously fell apart.",
  },
  {
    id: "toy-story",
    title: "Toy Story premieres",
    year: 1995,
    category: "culture",
    emoji: "🤠",
    color: "lilac",
    fact: "The first fully computer-animated feature took hundreds of thousands of machine hours to render.",
  },
  {
    id: "dolly-cloned",
    title: "Dolly the sheep is cloned",
    year: 1996,
    category: "discovery",
    emoji: "🐑",
    color: "mint",
    fact: "Dolly was named after Dolly Parton because her DNA came from a mammary-gland cell.",
  },
  {
    id: "netflix-founded",
    title: "Netflix is founded",
    year: 1997,
    category: "tech",
    emoji: "📀",
    color: "sky",
    fact: "Netflix began with DVDs sent through the mail, a decade before it started streaming.",
  },
  {
    id: "harry-potter-published",
    title: "Harry Potter is published",
    year: 1997,
    category: "culture",
    emoji: "🪄",
    color: "lilac",
    fact: "Harry Potter reached bookshops in the same year Netflix was founded as a DVD rental company.",
  },
  {
    id: "google-founded",
    title: "Google is founded",
    year: 1998,
    category: "tech",
    emoji: "🔎",
    color: "sky",
    fact: "The search engine's name grew from a misspelling of googol, the number one followed by a hundred zeros.",
  },
  {
    id: "spongebob-premiere",
    title: "SpongeBob SquarePants premieres",
    year: 1999,
    category: "culture",
    emoji: "🧽",
    color: "lilac",
    fact: "SpongeBob was created by a former marine-science educator who knew exactly how strange ocean life could be.",
  },
  {
    id: "iss-continuous-crew",
    title: "Continuous life aboard the ISS begins",
    year: 2000,
    category: "discovery",
    emoji: "🧑‍🚀",
    color: "mint",
    fact: "People have lived continuously in orbit since the first long-duration crew entered the station in 2000.",
  },
  {
    id: "wikipedia-launch",
    title: "Wikipedia launches",
    year: 2001,
    category: "tech",
    emoji: "📖",
    color: "sky",
    fact: "Wikipedia began as a quick side project designed to feed articles into a slower expert-written encyclopedia.",
  },
  {
    id: "ipod-launch",
    title: "The iPod launches",
    year: 2001,
    category: "tech",
    emoji: "🎵",
    color: "sky",
    fact: "Apple promised a thousand songs in your pocket in the same year Wikipedia opened its editable pages.",
  },
  {
    id: "human-genome-complete",
    title: "The Human Genome Project is completed",
    year: 2003,
    category: "discovery",
    emoji: "🧬",
    color: "mint",
    fact: "The finished reference showed humans have far fewer protein-coding genes than many scientists had expected.",
  },
  {
    id: "facebook-launch",
    title: "Facebook launches",
    year: 2004,
    category: "tech",
    emoji: "👥",
    color: "sky",
    fact: "The first version was limited to Harvard students before rapidly spreading to other campuses.",
  },
  {
    id: "youtube-launch",
    title: "YouTube launches",
    year: 2005,
    category: "tech",
    emoji: "▶️",
    color: "sky",
    fact: "The first upload was an 18-second zoo clip titled Me at the zoo.",
  },
  {
    id: "twitter-launch",
    title: "Twitter launches",
    year: 2006,
    category: "tech",
    emoji: "🐦",
    color: "sky",
    fact: "Twitter's original 140-character limit came from the constraints of SMS text messages.",
  },
  {
    id: "iphone-launch",
    title: "The first iPhone goes on sale",
    year: 2007,
    category: "tech",
    emoji: "📱",
    color: "sun",
    fact: "The iPhone arrived in 2007, the same year Netflix began sending movies over the internet instead of only by mail.",
  },
  {
    id: "netflix-streaming",
    title: "Netflix begins streaming",
    year: 2007,
    category: "culture",
    emoji: "🍿",
    color: "coral",
    fact: "Netflix switched on streaming in the same year Apple released the first iPhone.",
  },
  {
    id: "bitcoin-paper",
    title: "The Bitcoin paper is published",
    year: 2008,
    category: "tech",
    emoji: "₿",
    color: "sky",
    fact: "The nine-page proposal appeared during a global financial crisis under the still-unknown name Satoshi Nakamoto.",
  },
  {
    id: "minecraft-public",
    title: "Minecraft's first public version",
    year: 2009,
    category: "culture",
    emoji: "⛏️",
    color: "lilac",
    fact: "The first public build was assembled in less than a week before players began reshaping it through feedback.",
  },
  {
    id: "instagram-launch",
    title: "Instagram launches",
    year: 2010,
    category: "tech",
    emoji: "📷",
    color: "sky",
    fact: "Instagram began as a cluttered check-in app before its founders stripped almost everything away except photos.",
  },
  {
    id: "higgs-boson",
    title: "The Higgs boson is discovered",
    year: 2012,
    category: "discovery",
    emoji: "✨",
    color: "mint",
    fact: "A particle predicted nearly half a century earlier was confirmed in the same year Gangnam Style conquered YouTube.",
  },
  {
    id: "gangnam-style",
    title: "Gangnam Style goes global",
    year: 2012,
    category: "culture",
    emoji: "🐎",
    color: "lilac",
    fact: "The horse-dance hit became YouTube's first billion-view video in the year scientists confirmed the Higgs boson.",
  },
  {
    id: "frozen-premiere",
    title: "Frozen premieres",
    year: 2013,
    category: "culture",
    emoji: "❄️",
    color: "lilac",
    fact: "The story transformed during production when Let It Go convinced the filmmakers to make Elsa sympathetic.",
  },
  {
    id: "comet-landing",
    title: "A probe lands on a comet",
    year: 2014,
    category: "discovery",
    emoji: "☄️",
    color: "mint",
    fact: "Philae bounced twice in the comet's feeble gravity before settling in an unexpectedly shadowy spot.",
  },
  {
    id: "gravitational-waves",
    title: "Gravitational waves are detected",
    year: 2015,
    category: "discovery",
    emoji: "〰️",
    color: "mint",
    fact: "Two colliding black holes rippled spacetime in the same year Hamilton opened on Broadway.",
  },
  {
    id: "hamilton-broadway",
    title: "Hamilton opens on Broadway",
    year: 2015,
    category: "culture",
    emoji: "🎤",
    color: "lilac",
    fact: "Hamilton mixed hip-hop with founding-era history while scientists detected gravitational waves for the first time.",
  },
  {
    id: "pokemon-go",
    title: "Pokémon Go launches",
    year: 2016,
    category: "culture",
    emoji: "⚡",
    color: "lilac",
    fact: "Millions suddenly walked real streets to catch virtual creatures, briefly overwhelming parks and public landmarks.",
  },
  {
    id: "falcon-heavy",
    title: "Falcon Heavy's first flight",
    year: 2018,
    category: "tech",
    emoji: "🚀",
    color: "sky",
    fact: "Its test payload was a red sports car playing David Bowie as it headed into space.",
  },
  {
    id: "black-hole-image",
    title: "The first image of a black hole",
    year: 2019,
    category: "discovery",
    emoji: "🕳️",
    color: "mint",
    fact: "A planet-sized network of radio telescopes combined data to reveal a glowing ring 55 million light-years away.",
  },
  {
    id: "animal-crossing-new-horizons",
    title: "Animal Crossing: New Horizons launches",
    year: 2020,
    category: "culture",
    emoji: "🏝️",
    color: "lilac",
    fact: "Its gentle island life arrived just as lockdowns made virtual visits feel unexpectedly vital.",
  },
  {
    id: "mrna-vaccines",
    title: "The first mRNA vaccines are authorized",
    year: 2020,
    category: "discovery",
    emoji: "🧫",
    color: "mint",
    fact: "Decades of quiet research allowed scientists to turn a new virus's genetic sequence into vaccines at record speed.",
  },
  {
    id: "webb-launch",
    title: "The James Webb telescope launches",
    year: 2021,
    category: "discovery",
    emoji: "🪞",
    color: "mint",
    fact: "Its giant mirror folded up for launch like cosmic origami and unfolded on the way to deep space.",
  },
  {
    id: "webb-first-images",
    title: "Webb's first full-color images arrive",
    year: 2022,
    category: "discovery",
    emoji: "🌠",
    color: "mint",
    fact: "Webb revealed galaxies whose light had traveled for more than 13 billion years in the same year ChatGPT launched.",
  },
  {
    id: "chatgpt-launch",
    title: "ChatGPT launches",
    year: 2022,
    category: "tech",
    emoji: "🤖",
    color: "sky",
    fact: "ChatGPT opened to the public in the same year Webb's first full-color images peered deep into cosmic history.",
  },
] satisfies EventItem[];

export const PRACTICE_PACKS: PracticePack[] = [
  {
    id: "mixed",
    name: "Beautiful Chaos",
    description: "Everything collides: empires, snacks, science, games, and very strange timing.",
    emoji: "🎲",
    color: "sun",
    categories: ["world", "tech", "culture", "discovery"],
    eventIds: [],
  },
  {
    id: "tech",
    name: "Future Shock",
    description: "From steam engines to smartphones, place the inventions that changed everyday life.",
    emoji: "⚡",
    color: "sky",
    categories: ["tech"],
    eventIds: EVENTS.filter((event) => event.category === "tech").map((event) => event.id),
  },
  {
    id: "culture",
    name: "Pop Time",
    description: "Books, blockbusters, toys, tunes, and the treats people could not stop talking about.",
    emoji: "🍿",
    color: "lilac",
    categories: ["culture"],
    eventIds: EVENTS.filter((event) => event.category === "culture").map((event) => event.id),
  },
  {
    id: "discovery",
    name: "Big Discoveries",
    description: "Look outward, dig deeper, and order the moments that redrew what humans knew.",
    emoji: "🔭",
    color: "mint",
    categories: ["discovery"],
    eventIds: EVENTS.filter((event) => event.category === "discovery").map((event) => event.id),
  },
] satisfies PracticePack[];
