import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { generateExpandedSchedule, EXPANDED_SCHEDULE_START } from "../app/daily-schedule";
import {
  DAILY_MANIFEST,
  DAILY_MANIFEST_DAYS,
  DAILY_MANIFEST_EVENT_IDS,
  DAILY_MANIFEST_START,
} from "../app/event-data/daily-manifest";
import { EVENTS } from "../app/events";

const DAY_MS = 86_400_000;
const MANIFEST_YEARS = 20;
const allowFrozenRewrite = process.argv.includes("--replace-unpublished");
const start = new Date(`${EXPANDED_SCHEDULE_START}T00:00:00.000Z`);
const end = Date.UTC(start.getUTCFullYear() + MANIFEST_YEARS, start.getUTCMonth(), start.getUTCDate());
const dayCount = Math.round((end - start.getTime()) / DAY_MS);
const eventIds = EVENTS.map((event) => event.id).sort();
const eventIndex = new Map(eventIds.map((id, index) => [id, index]));
const schedule = generateExpandedSchedule(dayCount);

if (DAILY_MANIFEST_START !== EXPANDED_SCHEDULE_START) {
  throw new Error("Refusing to replace a manifest with a different start date.");
}

for (let dayIndex = 0; dayIndex < Math.min(DAILY_MANIFEST_DAYS, schedule.length); dayIndex += 1) {
  const offset = dayIndex * 20;
  const existingIds = Array.from({ length: 10 }, (_, itemIndex) => {
    const token = DAILY_MANIFEST.slice(offset + itemIndex * 2, offset + itemIndex * 2 + 2);
    return DAILY_MANIFEST_EVENT_IDS[Number.parseInt(token, 36)];
  });
  const generatedIds = schedule[dayIndex].map((event) => event.id);
  if (existingIds.some((id, index) => id !== generatedIds[index])) {
    if (!allowFrozenRewrite) {
      throw new Error(`Refusing to rewrite the frozen daily puzzle at day ${dayIndex}.`);
    }
    break;
  }
}

const encoded = schedule
  .flatMap((day) => day.map((event) => eventIndex.get(event.id)!.toString(36).padStart(2, "0")))
  .join("");
const chunks = encoded.match(/.{1,1000}/g) ?? [];
const outputPath = fileURLToPath(new URL("../app/event-data/daily-manifest.ts", import.meta.url));

const source = `// Generated by scripts/generate-daily-manifest.ts. Existing entries are immutable.\n\nexport const DAILY_MANIFEST_START = ${JSON.stringify(EXPANDED_SCHEDULE_START)};\nexport const DAILY_MANIFEST_DAYS = ${dayCount};\nexport const DAILY_MANIFEST_EVENT_IDS = ${JSON.stringify(eventIds, null, 2)} as const;\nexport const DAILY_MANIFEST = [\n${chunks.map((chunk) => `  ${JSON.stringify(chunk)},`).join("\n")}\n].join("");\n`;

writeFileSync(outputPath, source);
console.log(`Generated ${dayCount} frozen daily puzzles through ${new Date(end).toISOString().slice(0, 10)}.`);
